UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B00 - Balancing POS Summary.rpt'	  WHERE template='Office\base\reports\Balancing\B00 - Balancing POS Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B01 - Balancing ATM Summary.rpt'	  WHERE template='Office\base\reports\Balancing\B01 - Balancing ATM Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B01.1 - Balancing ATM Summary for Deposit Automation.rpt'	  WHERE template='Office\base\reports\Balancing\B01.1 - Balancing ATM Summary for Deposit Automation.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B02 - Balancing Terminal Detail.rpt'	  WHERE template='Office\base\reports\Balancing\B02 - Balancing Terminal Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B03 - Balancing Host Summary.rpt'	  WHERE template='Office\base\reports\Balancing\B03 - Balancing Host Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B03.1 - Balancing Host Summary for Deposit Automation.rpt'	  WHERE template='Office\base\reports\Balancing\B03.1 - Balancing Host Summary for Deposit Automation.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Balancing Host Detail.rpt'	  WHERE template='Office\base\reports\Balancing\B04 - Balancing Host Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - POS Detail.rpt'	  WHERE template='Office\base\reports\Balancing\B04 - POS Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B05 - Balancing Switched-In Summary.rpt'	  WHERE template='Office\base\reports\Balancing\B05 - Balancing Switched-In Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B05.1 - Balancing Switched-In Summary for Deposit Automation.rpt'	  WHERE template='Office\base\reports\Balancing\B05.1 - Balancing Switched-In Summary for Deposit Automation.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Balancing Switched-In Detail.rpt'	  WHERE template='Office\base\reports\Balancing\B06 - Balancing Switched-In Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B07 - Balancing Switched-Out Summary.rpt'	  WHERE template='Office\base\reports\Balancing\B07 - Balancing Switched-Out Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B07.1 - Balancing Switched-Out Summary for Deposit Automation.rpt'	  WHERE template='Office\base\reports\Balancing\B07.1 - Balancing Switched-Out Summary for Deposit Automation.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B08 - Balancing Switched-Out Detail.rpt'	  WHERE template='Office\base\reports\Balancing\B08 - Balancing Switched-Out Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B09 - Balancing POS Batch Mismatch.rpt'	  WHERE template='Office\base\reports\Balancing\B09 - Balancing POS Batch Mismatch.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B10 - Balancing ATM Host-Replenishment Summary.rpt'	  WHERE template='Office\base\reports\Balancing\B10 - Balancing ATM Host-Replenishment Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B10.1 - Balancing ATM Replenishment Summary.rpt'	  WHERE template='Office\base\reports\Balancing\B10.1 - Balancing ATM Replenishment Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B12 - Balancing ATM Depositor Summary.rpt'	  WHERE template='Office\base\reports\Balancing\B12 - Balancing ATM Depositor Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B12.1 - Balancing ATM Host-Deposit Replenishment Summary.rpt'	  WHERE template='Office\base\reports\Balancing\B12.1 - Balancing ATM Host-Deposit Replenishment Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B12.3 - Report for Electronic Deposits.rpt'	  WHERE template='Office\base\reports\Balancing\B12.3 - Report for Electronic Deposits.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B14 - Balancing Network-Host Suspense Summary.rpt'	  WHERE template='Office\base\reports\Balancing\B14 - Balancing Network-Host Suspense Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B16 - Balancing Network-ATM Suspense Summary.rpt'	  WHERE template='Office\base\reports\Balancing\B16 - Balancing Network-ATM Suspense Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B18 - Balancing ATM Cash Summary.rpt'	  WHERE template='Office\base\reports\Balancing\B18 - Balancing ATM Cash Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Screening\SCR01 - Screening - Merchant Monitoring.rpt'	  WHERE template='Office\base\reports\Screening\SCR01 - Screening - Merchant Monitoring.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\System\S01 - Host Monthly Volume - TotalTransactions.rpt'	  WHERE template='Office\base\reports\System\S01 - Host Monthly Volume - TotalTransactions.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\System\S02 - Host Response Codes Analysis.rpt'	  WHERE template='Office\base\reports\System\S02 - Host Response Codes Analysis.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\System\S03 - Host Response Times.rpt'	  WHERE template='Office\base\reports\System\S03 - Host Response Times.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\System\S04 - Host Timed-Out Transactions.rpt'	  WHERE template='Office\base\reports\System\S04 - Host Timed-Out Transactions.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\System\S05 - Terminal Declined Transactions.rpt'	  WHERE template='Office\base\reports\System\S05 - Terminal Declined Transactions.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\System\S06 - System Performance - RealTime.rpt'	  WHERE template='Office\base\reports\System\S06 - System Performance - RealTime.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\System\S07 - System Volume Growth.rpt'	  WHERE template='Office\base\reports\System\S07 - System Volume Growth.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\System\S08 - Transaction Detail.rpt'	  WHERE template='Office\base\reports\System\S08 - Transaction Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\System\S09 - System Volume with Breakdown.rpt'	  WHERE template='Office\base\reports\System\S09 - System Volume with Breakdown.rpt'
UPDATE reports_crystal_template SET  template='Office\Recon\base\reports\R01 - Recon Equal.rpt'	  WHERE template='Office\Recon\base\reports\R01 - Recon Equal.rpt'
UPDATE reports_crystal_template SET  template='Office\Recon\base\reports\R02 - Recon NotEqual.rpt'	  WHERE template='Office\Recon\base\reports\R02 - Recon NotEqual.rpt'
UPDATE reports_crystal_template SET  template='Office\Recon\base\reports\R03 - Recon PostOnly.rpt'	  WHERE template='Office\Recon\base\reports\R03 - Recon PostOnly.rpt'
UPDATE reports_crystal_template SET  template='Office\Recon\base\reports\R04 - Recon RemoteOnly.rpt'	  WHERE template='Office\Recon\base\reports\R04 - Recon RemoteOnly.rpt'
UPDATE reports_crystal_template SET  template='Office\Recon\base\reports\R05 - Recon Totals.rpt'	  WHERE template='Office\Recon\base\reports\R05 - Recon Totals.rpt'
UPDATE reports_crystal_template SET  template='Office\Recon\base\reports\R06 - Recon Adjustments.rpt'	  WHERE template='Office\Recon\base\reports\R06 - Recon Adjustments.rpt'
UPDATE reports_crystal_template SET  template='Office\Recon\base\reports\R07 - Recon Missing Files.rpt'	  WHERE template='Office\Recon\base\reports\R07 - Recon Missing Files.rpt'
UPDATE reports_crystal_template SET  template='Office\Recon\base\reports\R08 - Recon Unresolved NotEqual.rpt'	  WHERE template='Office\Recon\base\reports\R08 - Recon Unresolved NotEqual.rpt'
UPDATE reports_crystal_template SET  template='Office\Recon\base\reports\R09 - Recon Unresolved PostOnly.rpt'	  WHERE template='Office\Recon\base\reports\R09 - Recon Unresolved PostOnly.rpt'
UPDATE reports_crystal_template SET  template='Office\Recon\base\reports\R10 - Recon Unresolved RemoteOnly.rpt'	  WHERE template='Office\Recon\base\reports\R10 - Recon Unresolved RemoteOnly.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Acq Proc_Card Count On POS.rpt'	  WHERE template='Office\reports\Balancing\Acq Proc_Card Count On POS.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Acq Proc_Card Count On POS_Verve_Prepaid.rpt'	  WHERE template='Office\reports\Balancing\Acq Proc_Card Count On POS_Verve_Prepaid.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Acq Proc_No of Active POS.rpt'	  WHERE template='Office\reports\Balancing\Acq Proc_No of Active POS.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Acq Proc_POS Acquired Issuer Script.rpt'	  WHERE template='Office\reports\Balancing\Acq Proc_POS Acquired Issuer Script.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\ATM_Late_Reversal_Details_Acquirer.rpt'	  WHERE template='Office\reports\Balancing\ATM_Late_Reversal_Details_Acquirer.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\ATM_Late_Reversal_Details_Remote.rpt'	  WHERE template='Office\reports\Balancing\ATM_Late_Reversal_Details_Remote.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\ATM_Late_Reversal_Details_Summary_Acquirer_PDF.rpt'	  WHERE template='Office\Reports\Balancing\ATM_Late_Reversal_Details_Summary_Acquirer_PDF.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\ATM_Late_Reversal_Details_Summary_Issuer_PDF.rpt'	  WHERE template='Office\Reports\Balancing\ATM_Late_Reversal_Details_Summary_Issuer_PDF.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B00 - Balancing POS Summary.rpt'	  WHERE template='Office\Reports\Balancing\B00 - Balancing POS Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B01 - Balancing ATM Summary.rpt'	  WHERE template='Office\Reports\Balancing\B01 - Balancing ATM Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B01.1 - Balancing ATM Summary for Deposit Automation.rpt'	  WHERE template='Office\Reports\Balancing\B01.1 - Balancing ATM Summary for Deposit Automation.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B02 - Balancing Terminal Detail.rpt'	  WHERE template='Office\Reports\Balancing\B02 - Balancing Terminal Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B03 - Balancing Host Summary.rpt'	  WHERE template='Office\Reports\Balancing\B03 - Balancing Host Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B03.1 - Balancing Host Summary for Deposit Automation.rpt'	  WHERE template='Office\Reports\Balancing\B03.1 - Balancing Host Summary for Deposit Automation.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Balancing Host Detail.rpt'	  WHERE template='Office\Reports\Balancing\B04 - Balancing Host Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Bill Payment Acquirer Detail.rpt'	  WHERE template='Office\reports\Balancing\B04 - Bill Payment Acquirer Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Bill Payment Acquirer Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 - Bill Payment Acquirer Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Bill Payment Issuer Detail.rpt'	  WHERE template='Office\reports\Balancing\B04 - Bill Payment Issuer Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Bill Payment Issuer Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 - Bill Payment Issuer Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Bill Payment Issuer Detail_Shoprite.rpt'	  WHERE template='Office\Reports\Balancing\B04 - Bill Payment Issuer Detail_Shoprite.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Bill Payment VAS_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 - Bill Payment VAS_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - POS Detail.rpt'	  WHERE template='Office\reports\Balancing\B04 - POS Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - POS Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 - POS Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Prepaid Card Load.rpt'	  WHERE template='Office\reports\Balancing\B04 - Prepaid Card Load.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Prepaid Card Load_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 - Prepaid Card Load_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Recharge Transaction Detail.rpt'	  WHERE template='Office\reports\Balancing\B04 - Recharge Transaction Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Recharge Transaction Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 - Recharge Transaction Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Recharge Transaction Detail_mastercard.rpt'	  WHERE template='Office\reports\Balancing\B04 - Recharge Transaction Detail_mastercard.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Recharge VAS_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 - Recharge VAS_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Remote On Us Detail.rpt'	  WHERE template='Office\reports\Balancing\B04 - Remote On Us Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Remote On Us Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 - Remote On Us Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Remote On Us Detail_Verve_Int.rpt'	  WHERE template='Office\Reports\Balancing\B04 - Remote On Us Detail_Verve_Int.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Remote On Us_Discover Detail.rpt'	  WHERE template='Office\reports\Balancing\B04 - Remote On Us_Discover Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Web_Remote_ Detail.rpt'	  WHERE template='Office\reports\Balancing\B04 - Web_Remote_ Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 - Web_Remote_ Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 - Web_Remote_ Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -2New Pos Acquirer Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -2New Pos Acquirer Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Active Pos_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Active Pos_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Card_Count_on_POS_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Card_Count_on_POS_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Count_on_POS_Verveprepaid_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Count_on_POS_Verveprepaid_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -EasyFuel_Pos Acquirer Detail(all)_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -EasyFuel_Pos Acquirer Detail(all)_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -EasyFuel_Pos Acquirer Detail.rpt'	  WHERE template='Office\reports\Balancing\B04 -EasyFuel_Pos Acquirer Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -EasyFuel_Pos Acquirer Detail_all.rpt'	  WHERE template='Office\reports\Balancing\B04 -EasyFuel_Pos Acquirer Detail_all.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -EasyFuel_Pos Acquirer Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -EasyFuel_Pos Acquirer Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Pos Acquirer Detail_ALL_TRXN_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Pos Acquirer Detail_ALL_TRXN_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Pos Acquirer PrepaidMerchandise Detail.rpt'	  WHERE template='Office\reports\Balancing\B04 -Pos Acquirer PrepaidMerchandise Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Pos Cash Advance VAS_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Pos Cash Advance VAS_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Pos PTSP Detail-ALL_CSV.rpt'	  WHERE template='Office\reports\Balancing\B04 -Pos PTSP Detail-ALL_CSV.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Pos PTSP Detail.rpt'	  WHERE template='Office\reports\Balancing\B04 -Pos PTSP Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Pos PTSP Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Pos PTSP Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Pos Terminal Owner Detail-ALL_CSV.rpt'	  WHERE template='Office\reports\Balancing\B04 -Pos Terminal Owner Detail-ALL_CSV.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Pos Terminal Owner Detail.rpt'	  WHERE template='Office\reports\Balancing\B04 -Pos Terminal Owner Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Pos Terminal Owner Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Pos Terminal Owner Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -POS_Acquired_Issued_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -POS_Acquired_Issued_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -transaction_original_pospay_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -transaction_original_pospay_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -transaction_original_switchoffice_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -transaction_original_switchoffice_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -transaction_original_switchofficeFBN_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -transaction_original_switchofficeFBN_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Web Acquirer Detail_mgmt_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Web Acquirer Detail_mgmt_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Web_ Acquirer Detail_standardize.rpt'	  WHERE template='Office\reports\Balancing\B04 -Web_ Acquirer Detail_standardize.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Web_Acquirer Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Web_Acquirer Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail.rpt'	  WHERE template='Office\reports\Balancing\B04 -Web_Pos Acquirer Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Web_Pos Acquirer Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail_csv_Monthly.rpt'	  WHERE template='Office\reports\Balancing\B04 -Web_Pos Acquirer Detail_csv_Monthly.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail_csv_Weekly.rpt'	  WHERE template='Office\reports\Balancing\B04 -Web_Pos Acquirer Detail_csv_Weekly.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail_CUP.rpt'	  WHERE template='Office\reports\Balancing\B04 -Web_Pos Acquirer Detail_CUP.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail_CUP_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Web_Pos Acquirer Detail_CUP_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail_CUPTest_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Web_Pos Acquirer Detail_CUPTest_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail_Skye Acquirer On Record_csv.rpt'	  WHERE template='Office\reports\Balancing\B04 -Web_Pos Acquirer Detail_Skye Acquirer On Record_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B05 - Balancing Switched-In Summary.rpt'	  WHERE template='Office\Reports\Balancing\B05 - Balancing Switched-In Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B05 - Balancing TPP Switched-In Summary.rpt'	  WHERE template='Office\reports\Balancing\B05 - Balancing TPP Switched-In Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B05 - Balancing TPP Switched-Out Summary.rpt'	  WHERE template='Office\reports\Balancing\B05 - Balancing TPP Switched-Out Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B05 - Mastercard Processing.rpt'	  WHERE template='Office\reports\Balancing\B05 - Mastercard Processing.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B05.1 - Balancing Switched-In Summary for Deposit Automation.rpt'	  WHERE template='Office\Reports\Balancing\B05.1 - Balancing Switched-In Summary for Deposit Automation.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 -  Participating Interbank Transfer (Channels)_csv.rpt'	  WHERE template='Office\reports\Balancing\B06 -  Participating Interbank Transfer (Channels)_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Acquired Interbank Transfer (Channels).rpt'	  WHERE template='Office\reports\Balancing\B06 - Acquired Interbank Transfer (Channels).rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Acquired Interbank Transfer (Channels)_csv.rpt'	  WHERE template='Office\reports\Balancing\B06 - Acquired Interbank Transfer (Channels)_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - ATMC Daily Report.rpt'	  WHERE template='Office\reports\Balancing\B06 - ATMC Daily Report.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - AutoPay Detail.rpt'	  WHERE template='Office\reports\Balancing\B06 - AutoPay Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - AutoPay Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B06 - AutoPay Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - AutoPay Detail_Sponsor.rpt'	  WHERE template='Office\reports\Balancing\B06 - AutoPay Detail_Sponsor.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - AutoPay Detail_Sponsor_csv.rpt'	  WHERE template='Office\reports\Balancing\B06 - AutoPay Detail_Sponsor_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Balancing Switched-In Detail.rpt'	  WHERE template='Office\reports\Balancing\B06 - Balancing Switched-In Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Globacom Transaction Detail.rpt'	  WHERE template='Office\reports\Balancing\B06 - Globacom Transaction Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Interbank Transfer (platforms).rpt'	  WHERE template='Office\reports\Balancing\B06 - Interbank Transfer (platforms).rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Interbank Transfer (platforms)_csv.rpt'	  WHERE template='Office\reports\Balancing\B06 - Interbank Transfer (platforms)_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Interbank Transfer (platforms)_remita_csv.rpt'	  WHERE template='Office\reports\Balancing\B06 - Interbank Transfer (platforms)_remita_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - MasterCard Not On Us Detail.rpt'	  WHERE template='Office\reports\Balancing\B06 - MasterCard Not On Us Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Not On Us Detail Smartpoint.rpt'	  WHERE template='Office\reports\Balancing\B06 - Not On Us Detail Smartpoint.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Not On Us Detail Smartpoint_csv.rpt'	  WHERE template='Office\reports\Balancing\B06 - Not On Us Detail Smartpoint_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Not On Us Detail.rpt'	  WHERE template='Office\reports\Balancing\B06 - Not On Us Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Not On Us Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B06 - Not On Us Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Not On Us Detail_Failed_Terminal_Transactions_csv.rpt'	  WHERE template='Office\Reports\Balancing\B06 - Not On Us Detail_Failed_Terminal_Transactions_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Not On Us Detail_Terminal.rpt'	  WHERE template='Office\reports\Balancing\B06 - Not On Us Detail_Terminal.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Not On Us Detail_Terminal_csv.rpt'	  WHERE template='Office\Reports\Balancing\B06 - Not On Us Detail_Terminal_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Not On Us Detail_Verve_Int.rpt'	  WHERE template='Office\Reports\Balancing\B06 - Not On Us Detail_Verve_Int.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Not On Us Detail_Verve_Int_Acquirer.rpt'	  WHERE template='Office\Reports\Balancing\B06 - Not On Us Detail_Verve_Int_Acquirer.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Participating Interbank Transfer (Channels).rpt'	  WHERE template='Office\reports\Balancing\B06 - Participating Interbank Transfer (Channels).rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Participating Interbank Transfer (Channels)1.rpt'	  WHERE template='Office\Reports\Balancing\B06 - Participating Interbank Transfer (Channels)1.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - PTSP Summary Report.rpt'	  WHERE template='Office\reports\Balancing\B06 - PTSP Summary Report.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - PTSP Summary_Backlog Report.rpt'	  WHERE template='Office\reports\Balancing\B06 - PTSP Summary_Backlog Report.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Switch Summary Monthly.rpt'	  WHERE template='Office\reports\Balancing\B06 - Switch Summary Monthly.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Switch Summary(verve billing)_csv.rpt'	  WHERE template='Office\reports\Balancing\B06 - Switch Summary(verve billing)_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Switch Summary.rpt'	  WHERE template='Office\reports\Balancing\B06 - Switch Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Switch Summary_csv.rpt'	  WHERE template='Office\reports\Balancing\B06 - Switch Summary_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Switch Summary_SVA_csv.rpt'	  WHERE template='Office\reports\Balancing\B06 - Switch Summary_SVA_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Terminal Owner Summary Report.rpt'	  WHERE template='Office\reports\Balancing\B06 - Terminal Owner Summary Report.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Terminal Owner Summary_Backlog Report.rpt'	  WHERE template='Office\reports\Balancing\B06 - Terminal Owner Summary_Backlog Report.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - VAS Summary_csv.rpt'	  WHERE template='Office\reports\Balancing\B06 - VAS Summary_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Verve Report_Not_On_Us.rpt'	  WHERE template='Office\reports\Balancing\B06 - Verve Report_Not_On_Us.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B06 - Verve Report1.rpt'	  WHERE template='Office\reports\Balancing\B06 - Verve Report1.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B07 - Balancing Switched-Out Summary.rpt'	  WHERE template='Office\Reports\Balancing\B07 - Balancing Switched-Out Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B07.1 - Balancing Switched-Out Summary for Deposit Automation.rpt'	  WHERE template='Office\Reports\Balancing\B07.1 - Balancing Switched-Out Summary for Deposit Automation.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B08 - Balancing Switched-Out Detail.rpt'	  WHERE template='Office\Reports\Balancing\B08 - Balancing Switched-Out Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B09 - Balancing POS Batch Mismatch.rpt'	  WHERE template='Office\Reports\Balancing\B09 - Balancing POS Batch Mismatch.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B10 - Balancing ATM Host-Replenishment Summary.rpt'	  WHERE template='Office\Reports\Balancing\B10 - Balancing ATM Host-Replenishment Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B10.1 - Balancing ATM Replenishment Summary.rpt'	  WHERE template='Office\Reports\Balancing\B10.1 - Balancing ATM Replenishment Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Acquirer Summary_Web_Pos.rpt'	  WHERE template='Office\reports\Balancing\B11 - Acquirer Summary_Web_Pos.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Acquirer Summary_Web_Pos_CUP.rpt'	  WHERE template='Office\reports\Balancing\B11 - Acquirer Summary_Web_Pos_CUP.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Acquirer Summary_Web_Pos_Mcard_Routing.rpt'	  WHERE template='Office\reports\Balancing\B11 - Acquirer Summary_Web_Pos_Mcard_Routing.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Acquirer Summary_Web_Pos_verve_billing.rpt'	  WHERE template='Office\reports\Balancing\B11 - Acquirer Summary_Web_Pos_verve_billing.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Acquirer Summary_Web_Pos_Visa_CoAcquiring.rpt'	  WHERE template='Office\reports\Balancing\B11 - Acquirer Summary_Web_Pos_Visa_CoAcquiring.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Acquirer Summary_Web_standardized.rpt'	  WHERE template='Office\reports\Balancing\B11 - Acquirer Summary_Web_standardized.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Not On Us CSS Verve Summary.rpt'	  WHERE template='Office\reports\Balancing\B11 - Not On Us CSS Verve Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Not On Us Summary_ATM.rpt'	  WHERE template='Office\reports\Balancing\B11 - Not On Us Summary_ATM.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Not On Us Summary_ATM_(check).rpt'	  WHERE template='Office\reports\Balancing\B11 - Not On Us Summary_ATM_(check).rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Not On Us Summary_ATM_Cardless.rpt'	  WHERE template='Office\reports\Balancing\B11 - Not On Us Summary_ATM_Cardless.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Not On Us Summary_ATM_Smartpoint.rpt'	  WHERE template='Office\reports\Balancing\B11 - Not On Us Summary_ATM_Smartpoint.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Not On Us Summary_ATM_Verve Int.rpt'	  WHERE template='Office\Reports\Balancing\B11 - Not On Us Summary_ATM_Verve Int.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote On Us CSS Verve Summary.rpt'	  WHERE template='Office\reports\Balancing\B11 - Remote On Us CSS Verve Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote On Us Summary_ATM.rpt'	  WHERE template='Office\reports\Balancing\B11 - Remote On Us Summary_ATM.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote On Us Summary_ATM_Cardless.rpt'	  WHERE template='Office\reports\Balancing\B11 - Remote On Us Summary_ATM_Cardless.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote On Us Summary_ATM_Detailed_Discover.rpt'	  WHERE template='Office\reports\Balancing\B11 - Remote On Us Summary_ATM_Detailed_Discover.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote On Us Summary_ATM_Detailed_Verve Int.rpt'	  WHERE template='Office\Reports\Balancing\B11 - Remote On Us Summary_ATM_Detailed_Verve Int.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote On Us Summary_ATM_Discover.rpt'	  WHERE template='Office\reports\Balancing\B11 - Remote On Us Summary_ATM_Discover.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote On Us Summary_ATM_GTBCC_On Us(Mastercard).rpt'	  WHERE template='Office\reports\Balancing\B11 - Remote On Us Summary_ATM_GTBCC_On Us(Mastercard).rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote On Us Summary_ATM_Smartpoint.rpt'	  WHERE template='Office\reports\Balancing\B11 - Remote On Us Summary_ATM_Smartpoint.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote On Us Summary_ATM_Verve Int.rpt'	  WHERE template='Office\Reports\Balancing\B11 - Remote On Us Summary_ATM_Verve Int.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote On Us Summary_Web_Pos.rpt'	  WHERE template='Office\reports\Balancing\B11 - Remote On Us Summary_Web_Pos.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote On Us Summary_Web_Pos_verve_billing.rpt'	  WHERE template='Office\reports\Balancing\B11 - Remote On Us Summary_Web_Pos_verve_billing.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote On Us Summary_Web_standardized.rpt'	  WHERE template='Office\reports\Balancing\B11 - Remote On Us Summary_Web_standardized.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Remote Summary_Web_Pos_Mcard_Routing.rpt'	  WHERE template='Office\reports\Balancing\B11 - Remote Summary_Web_Pos_Mcard_Routing.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - ROU_Web_Mastercard.rpt'	  WHERE template='Office\reports\Balancing\B11 - ROU_Web_Mastercard.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 - Settlement_Bank_Summary_ATM_Verve Int.rpt'	  WHERE template='Office\Reports\Balancing\B11 - Settlement_Bank_Summary_ATM_Verve Int.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 Bill Payment Acquirer Summary.rpt'	  WHERE template='Office\reports\Balancing\B11 Bill Payment Acquirer Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 Bill Payment Issuer Summary.rpt'	  WHERE template='Office\reports\Balancing\B11 Bill Payment Issuer Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B11 Bill Payment Issuer Summary_mastercard.rpt'	  WHERE template='Office\reports\Balancing\B11 Bill Payment Issuer Summary_mastercard.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B12 - Balancing ATM Depositor Summary.rpt'	  WHERE template='Office\Reports\Balancing\B12 - Balancing ATM Depositor Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B12.1 - Balancing ATM Host-Deposit Replenishment Summary.rpt'	  WHERE template='Office\Reports\Balancing\B12.1 - Balancing ATM Host-Deposit Replenishment Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B12.3 - Report for Electronic Deposits.rpt'	  WHERE template='Office\Reports\Balancing\B12.3 - Report for Electronic Deposits.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B14 - Balancing Network-Host Suspense Summary.rpt'	  WHERE template='Office\Reports\Balancing\B14 - Balancing Network-Host Suspense Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B15 - Float Card balance Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B15 - Float Card balance Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B16 - Balancing Network-ATM Suspense Summary.rpt'	  WHERE template='Office\Reports\Balancing\B16 - Balancing Network-ATM Suspense Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B17 - Logical Stock Management Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\B17 - Logical Stock Management Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B18 - Balancing ATM Cash Summary.rpt'	  WHERE template='Office\Reports\Balancing\B18 - Balancing ATM Cash Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B19 - Response Codes Analysis.rpt'	  WHERE template='Office\reports\Balancing\B19 - Response Codes Analysis.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B19 - Response Codes Analysis_periodic.rpt'	  WHERE template='Office\reports\Balancing\B19 - Response Codes Analysis_periodic.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B20 - Acquiring Performance(All).rpt'	  WHERE template='Office\reports\Balancing\B20 - Acquiring Performance(All).rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B20 - Acquiring Performance.rpt'	  WHERE template='Office\reports\Balancing\B20 - Acquiring Performance.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\B20 - Issuing Performance.rpt'	  WHERE template='Office\reports\Balancing\B20 - Issuing Performance.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Card_History_csv.rpt'	  WHERE template='Office\reports\Balancing\Card_History_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_03CAP.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_03CAP.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_3LINE.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_3LINE.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_Abbey.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_Abbey.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_ABP.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_ABP.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_ACCION.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_ACCION.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_ASO.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_ASO.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_CELLULANT.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_CELLULANT.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_CITI.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_CITI.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_DBL.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_DBL.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_ECO.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_ECO.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_EKONDO.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_EKONDO.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_ENT.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_ENT.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_FBN.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_FBN.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_FBP.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_FBP.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_FCMB.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_FCMB.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_GTB.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_GTB.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_HASAL.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_HASAL.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_HBC.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_HBC.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_IBP.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_IBP.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_IBTC.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_IBTC.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_INF.rpt'	  WHERE template=' Office\Reports\Balancing\Comprehensive_Computation_INF.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_JAIZ.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_JAIZ.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_KSB.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_KSB.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_MSB.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_MSB.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_NCS.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_NCS.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_OBI.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_OBI.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_PAYCOM.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_PAYCOM.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_PSH.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_PSH.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_RDY.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_RDY.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_RSL.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_RSL.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_SBP.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_SBP.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_SCB.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_SCB.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_SKYE.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_SKYE.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_UBA.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_UBA.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_UBN.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_UBN.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_UBP.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_UBP.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_UML.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_UML.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_UnC.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_UnC.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_UNICAL.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_UNICAL.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_Wem.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_Wem.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Comprehensive_Computation_ZIB.rpt'	  WHERE template='Office\Reports\Balancing\Comprehensive_Computation_ZIB.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\credit Web_Acquirer Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\credit Web_Acquirer Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\GTB_Summary_Report_csv.rpt'	  WHERE template='Office\reports\Balancing\GTB_Summary_Report_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Late POS Reversal_Acquirer.rpt'	  WHERE template='Office\Reports\Balancing\Late POS Reversal_Acquirer.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Late POS Reversal_Acquirer_Detail.rpt'	  WHERE template='Office\Reports\Balancing\Late POS Reversal_Acquirer_Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Late POS Reversal_Acquirer_Summary.rpt'	  WHERE template='Office\Reports\Balancing\Late POS Reversal_Acquirer_Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Late POS Reversal_Issuer_Summary.rpt'	  WHERE template='Office\Reports\Balancing\Late POS Reversal_Issuer_Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Late POS Reversal_Remote_Detail.rpt'	  WHERE template='Office\Reports\Balancing\Late POS Reversal_Remote_Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\MasterCard Locally Processed Summary.rpt'	  WHERE template='Office\reports\Balancing\MasterCard Locally Processed Summary.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NCS_POS Detail.rpt'	  WHERE template='Office\reports\Balancing\NCS_POS Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_Paid.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_Paid.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_Paid_Via_Acquirer.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_Paid_Via_Acquirer.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_POS _Acquirer Detail.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_POS _Acquirer Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_POS _Acquirer Detail_2nd nov 12.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_POS _Acquirer Detail_2nd nov 12.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_POS _Acquirer Detail_exclusion.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_POS _Acquirer Detail_exclusion.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_POS _Acquirer Detail_instant discount.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_POS _Acquirer Detail_instant discount.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_POS _Acquirer Detail_NCS.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_POS _Acquirer Detail_NCS.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_POS _Acquirer Detail_rejected.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_POS _Acquirer Detail_rejected.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_POS _Acquirer Detail_Visa-AcqOnRec.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_POS _Acquirer Detail_Visa-AcqOnRec.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_Returns.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_Returns.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_Returns_backup.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_Returns_backup.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_ROU_POS Detail.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_ROU_POS Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_ROU_POS Detail_exclusion.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_ROU_POS Detail_exclusion.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\NIBSS_ROU_POS Detail_rejected.rpt'	  WHERE template='Office\reports\Balancing\NIBSS_ROU_POS Detail_rejected.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\POS_Detail_AUT_FOUNDATION_CSV.rpt'	  WHERE template='Office\Reports\Balancing\POS_Detail_AUT_FOUNDATION_CSV.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\PTSP_periodic_backlog.rpt'	  WHERE template='Office\reports\Balancing\PTSP_periodic_backlog.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Reconciliation.rpt'	  WHERE template='Office\reports\Balancing\Reconciliation.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Reward_Money_Fee_Settlement_Report.rpt'	  WHERE template='Office\reports\Balancing\Reward_Money_Fee_Settlement_Report.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\ROU_POS Detail_ISW_RDM.rpt'	  WHERE template='Office\reports\Balancing\ROU_POS Detail_ISW_RDM.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\S06 - System Performance - RealTime.rpt'	  WHERE template='Office\Reports\Balancing\S06 - System Performance - RealTime.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Settlement Bank Net.rpt'	  WHERE template='Office\reports\Balancing\Settlement Bank Net.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Settlement_Computation.rpt'	  WHERE template='Office\reports\Balancing\Settlement_Computation.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Settlement_Computation_All.rpt'	  WHERE template='Office\reports\Balancing\Settlement_Computation_All.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\terminal_owner_periodic_backlog.rpt'	  WHERE template='Office\reports\Balancing\terminal_owner_periodic_backlog.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Verve Billing Member Report.rpt'	  WHERE template='Office\reports\Balancing\Verve Billing Member Report.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Verve Billing Member Report_All.rpt'	  WHERE template='Office\reports\Balancing\Verve Billing Member Report_All.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Verve Billing Member Report_Transfers.rpt'	  WHERE template='Office\reports\Balancing\Verve Billing Member Report_Transfers.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\WEB _Acquirer Detail.rpt'	  WHERE template='Office\reports\Balancing\WEB _Acquirer Detail.rpt'
UPDATE reports_crystal_template SET  template='Office\base\reports\Balancing\Web_Acquirer Monthly Detail_csv.rpt'	  WHERE template='Office\reports\Balancing\Web_Acquirer Monthly Detail_csv.rpt'
UPDATE reports_crystal_template SET  template='Office\Settlement\base\reports\StandardStatementing.rpt'	  WHERE template='Office\Settlement\base\reports\StandardStatementing.rpt'
