 UPDATE reports_crystal_template SET user_params_defs='EDITBOX=StartDate in ''yyyymmdd'' format:; 30;1;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=EndDate in ''yyyymmdd'' format:; 30;1;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=SourceNode:; 1000;0;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=show_full_pan:; 1000;0;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=terminalID:; 40;0;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=TotalsGroup:; 512;0;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=report_date_start in ''yyyymmdd'' format:; 30;1;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=report_date_end in ''yyyymmdd'' format:; 30;1;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=rpt_tran_id:; 1000;0;DEFAULT:NULL' WHERE template='Office\base\reports\Balancing\B06 - Not On Us Detail_csv.rpt'

 UPDATE reports_crystal_template SET user_params_defs='EDITBOX=StartDate in ''yyyymmdd'' format:; 30;1;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=EndDate in ''yyyymmdd'' format:; 30;1;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=SinkNodes:; 510;0;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=SourceNodes:; 1000;0;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=show_full_pan:; 1000;0;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=report_date_start in ''yyyymmdd'' format:; 30;1;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=report_date_end in ''yyyymmdd'' format:; 30;1;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=rpt_tran_id:; 1000;0;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=rpt_tran_id1:; 1000;0;DEFAULT:NULL'
+CHAR(13)+CHAR(10)+'EDITBOX=Extended_tran_type:; 1000;0;DEFAULT:NULL'  WHERE template='Office\base\reports\Balancing\B04 - Web_Remote_ Detail_csv.rpt'
UPDATE reports_crystal set report_params = REPLACE(REPLACE(CONVERT(VARCHAR(MAX), report_params), '~NULL~NULL~NULL~NULL~', '~NULL~NULL~NULL~'),'src~1S', 'src~NULL~1S')WHERE template = 'J:\postilion\Office\reports\Balancing\B06 - Not On Us Detail_csv.rpt'

--SELECT * FROM  reports_crystal_template WHERE template LIKE '%B06 - Not On Us Detail_csv.rpt'

UPDATE  reports_crystal SET report_params = REPLACE(CONVERT(VARCHAR(MAX),report_params), 'src~NULL~NULL~NULL~NULL~NULL~', 'src~NULL~NULL~NULL~NULL~NULL~NULL~') WHERE template ='J:\postilion\Office\reports\Balancing\B04 - Web_Remote_ Detail_csv.rpt'