 ALTER DATABASE postilion_office ADD FILEGROUP [JAN_2015A]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [JAN_2015B]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [JAN_2015C]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [FEB_2015A]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [FEB_2015B]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [FEB_2015C]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [MAR_2015A]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [MAR_2015B]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [MAR_2015C]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [APR_2015A]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [APR_2015B]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [APR_2015C]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [MAY_2015A]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [MAY_2015B]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [MAY_2015C]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [JUN_2015A]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [JUN_2015B]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [JUN_2015C]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [JUL_2015A]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [JUL_2015B]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [JUL_2015C]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [AUG_2015A]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [AUG_2015B]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [AUG_2015C]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [SEP_2015A]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [SEP_2015B]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [SEP_2015C]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [OCT_2015A]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [OCT_2015B]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [OCT_2015C]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [NOV_2015A]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [NOV_2015B]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [NOV_2015C]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [DEC_2015A]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [DEC_2015B]
 GO
  ALTER DATABASE postilion_office ADD FILEGROUP [DEC_2015C]
  GO