ALTER   PROCEDURE   
usp_sync_asp_visa_pos_transactions
 @report_date_start VARCHAR(30),
 @report_date_end VARCHAR(30)
AS
BEGIN

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

DECLARE @sql_query VARCHAR(MAX)
SET @report_date_start = ISNULL(@report_date_start, REPLACE(CONVERT(VARCHAR(10), DATEADD(D,-1, GETDATE()),111),'/', ''))
SET @report_date_end  = ISNULL(@report_date_end, REPLACE(CONVERT(VARCHAR(10), DATEADD(D,-1, GETDATE()),111),'/', ''))

IF NOT EXISTS  (select * from asp_visa_pos (NOLOCK ) WHERE recon_business_date >=REPLACE(CONVERT(VARCHAR(10), GETDATE(),111),'/', '') ) begin
 
		DELETE  FROM VISA_FROM_ASP_Session  WHERE  Business_Date=  REPLACE(CONVERT(VARCHAR(10), GETDATE(),111),'/', '')
		
 
end


EXEC [osp_rpt_b04_POS_VISA_insert_date]   NULL,NULL

set @sql_query = 
'INSERT INTO 
       asp_visa_pos
	   ([post_tran_cust_id]
      ,[abort_rsp_code]
      ,[acquirer_network_id]
      ,[payee]
      ,[pos_condition_code]
      ,[pos_entry_mode]
      ,[post_tran_id]
      ,[prev_post_tran_id]
      ,[prev_tran_approved]
      ,[pt_pos_card_input_mode]
      ,[pt_pos_cardholder_auth_method]
      ,[pt_pos_operating_environment]
      ,[pt_pos_pin_capture_ability]
      ,[pt_pos_terminal_operator]
      ,[realtime_business_date]
      ,[receiving_inst_id_code]
      ,[recon_business_date]
      ,[retention_data]
      ,[retrieval_reference_nr]
      ,[routing_type]
      ,[rsp_code_req]
      ,[rsp_code_rsp]
      ,[settle_amount_impact]
      ,[settle_amount_req]
      ,[settle_amount_rsp]
      ,[settle_cash_req]
      ,[settle_cash_rsp]
      ,[settle_currency_code]
      ,[settle_entity_id]
      ,[settle_proc_fee_req]
      ,[settle_proc_fee_rsp]
      ,[settle_tran_fee_req]
      ,[settle_tran_fee_rsp]
      ,[sink_node_name]
      ,[sponsor_bank]
      ,[structured_data_req]
      ,[structured_data_rsp]
      ,[system_trace_audit_nr]
      ,[to_account_id]
      ,[to_account_type]
      ,[to_account_type_qualifier]
      ,[tran_amount_req]
      ,[tran_amount_rsp]
      ,[tran_cash_req]
      ,[tran_cash_rsp]
      ,[tran_completed]
      ,[tran_currency_code]
      ,[tran_nr]
      ,[tran_postilion_originated]
      ,[tran_proc_fee_currency_code]
      ,[tran_proc_fee_req]
      ,[tran_proc_fee_rsp]
      ,[tran_reversed]
      ,[tran_tran_fee_currency_code]
      ,[tran_tran_fee_req]
      ,[tran_tran_fee_rsp]
      ,[tran_type]
      ,[ucaf_data]
      ,[address_verification_data]
      ,[address_verification_result]
      ,[card_acceptor_id_code]
      ,[card_acceptor_name_loc]
      ,[card_product]
      ,[card_seq_nr]
      ,[check_data]
      ,[draft_capture]
      ,[expiry_date]
      ,[mapped_card_acceptor_id_code]
      ,[merchant_type]
      ,[pan]
      ,[pan_encrypted]
      ,[pan_reference]
      ,[pan_search]
      ,[pos_card_capture_ability]
      ,[pos_card_data_input_ability]
      ,[pos_card_data_input_mode]
      ,[pos_card_data_output_ability]
      ,[pos_card_present]
      ,[pos_cardholder_auth_ability]
      ,[pos_cardholder_auth_entity]
      ,[pos_cardholder_auth_method]
      ,[pos_cardholder_present]
      ,[pos_operating_environment]
      ,[pos_pin_capture_ability]
      ,[pos_terminal_operator]
      ,[pos_terminal_output_ability]
      ,[pos_terminal_type]
      ,[service_restriction_code]
      ,[source_node_name]
      ,[terminal_id]
      ,[terminal_owner]
      ,[totals_group]
      ,[acquiring_inst_id_code]
      ,[additional_rsp_data]
      ,[auth_id_rsp]
      ,[auth_reason]
      ,[auth_type]
      ,[bank_details]
      ,[batch_nr]
      ,[card_verification_result]
      ,[datetime_req]
      ,[datetime_rsp]
      ,[datetime_tran_gmt]
      ,[datetime_tran_local]
      ,[extended_tran_type]
      ,[from_account_id]
      ,[from_account_type]
      ,[from_account_type_qualifier]
      ,[icc_data_req]
      ,[icc_data_rsp]
      ,[issuer_network_id]
      ,[message_reason_code]
      ,[message_type]
      ,[next_post_tran_id]
      ,[online_system_id]
      ,[participant_id]
	  )
	  SELECT [post_tran_cust_id]
      ,[abort_rsp_code]
      ,[acquirer_network_id]
      ,[payee]
      ,[pos_condition_code]
      ,[pos_entry_mode]
      ,[post_tran_id]
      ,[prev_post_tran_id]
      ,[prev_tran_approved]
      ,[pt_pos_card_input_mode]
      ,[pt_pos_cardholder_auth_method]
      ,[pt_pos_operating_environment]
      ,[pt_pos_pin_capture_ability]
      ,[pt_pos_terminal_operator]
      ,[realtime_business_date]
      ,[receiving_inst_id_code]
      ,[recon_business_date]
      ,[retention_data]
      ,[retrieval_reference_nr]
      ,[routing_type]
      ,[rsp_code_req]
      ,[rsp_code_rsp]
      ,[settle_amount_impact]
      ,[settle_amount_req]
      ,[settle_amount_rsp]
      ,[settle_cash_req]
      ,[settle_cash_rsp]
      ,[settle_currency_code]
      ,[settle_entity_id]
      ,[settle_proc_fee_req]
      ,[settle_proc_fee_rsp]
      ,[settle_tran_fee_req]
      ,[settle_tran_fee_rsp]
      ,[sink_node_name]
      ,[sponsor_bank]
      ,[structured_data_req]
      ,[structured_data_rsp]
      ,[system_trace_audit_nr]
      ,[to_account_id]
      ,[to_account_type]
      ,[to_account_type_qualifier]
      ,[tran_amount_req]
      ,[tran_amount_rsp]
      ,[tran_cash_req]
      ,[tran_cash_rsp]
      ,[tran_completed]
      ,[tran_currency_code]
      ,[tran_nr]
      ,[tran_postilion_originated]
      ,[tran_proc_fee_currency_code]
      ,[tran_proc_fee_req]
      ,[tran_proc_fee_rsp]
      ,[tran_reversed]
      ,[tran_tran_fee_currency_code]
      ,[tran_tran_fee_req]
      ,[tran_tran_fee_rsp]
      ,[tran_type]
      ,[ucaf_data]
      ,[address_verification_data]
      ,[address_verification_result]
      ,[card_acceptor_id_code]
      ,[card_acceptor_name_loc]
      ,[card_product]
      ,[card_seq_nr]
      ,[check_data]
      ,[draft_capture]
      ,[expiry_date]
      ,[mapped_card_acceptor_id_code]
      ,[merchant_type]
      ,[pan]
      ,[pan_encrypted]
      ,[pan_reference]
      ,[pan_search]
      ,[pos_card_capture_ability]
      ,[pos_card_data_input_ability]
      ,[pos_card_data_input_mode]
      ,[pos_card_data_output_ability]
      ,[pos_card_present]
      ,[pos_cardholder_auth_ability]
      ,[pos_cardholder_auth_entity]
      ,[pos_cardholder_auth_method]
      ,[pos_cardholder_present]
      ,[pos_operating_environment]
      ,[pos_pin_capture_ability]
      ,[pos_terminal_operator]
      ,[pos_terminal_output_ability]
      ,[pos_terminal_type]
      ,[service_restriction_code]
      ,[source_node_name]
      ,[terminal_id]
      ,[terminal_owner]
      ,[totals_group]
      ,[acquiring_inst_id_code]
      ,[additional_rsp_data]
      ,[auth_id_rsp]
      ,[auth_reason]
      ,[auth_type]
      ,[bank_details]
      ,[batch_nr]
      ,[card_verification_result]
      ,[datetime_req]
      ,[datetime_rsp]
      ,[datetime_tran_gmt]
      ,[datetime_tran_local]
      ,[extended_tran_type]
      ,[from_account_id]
      ,[from_account_type]
      ,[from_account_type_qualifier]
      ,[icc_data_req]
      ,[icc_data_rsp]
      ,[issuer_network_id]
      ,[message_reason_code]
      ,[message_type]
      ,[next_post_tran_id]
      ,[online_system_id]
      ,[participant_id]
        FROM OPENQUERY([172.25.15.15], ''exec [postilion_office].dbo.[osp_rpt_b04_POS_VISA_insert] '''''+@report_date_start+''''','''''+@report_date_end+''''''')';
        
      exec(@sql_query);
      
      END
      
      
      