
ALTER SCHEMA dbo TRANSFER smartpoint_monitor.ssf_media_cassette_history
ALTER SCHEMA dbo TRANSFER smartpoint_monitor.ssf_media_checkpoint
ALTER SCHEMA dbo TRANSFER smartpoint_monitor.ssf_media_class
ALTER SCHEMA dbo TRANSFER smartpoint_monitor.ssf_media_type