SELECT (	SELECT COUNT(*) FROM 	aa_entity_params	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	aa_entity_params	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	aa_lnk_cfg	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	aa_lnk_cfg	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	at_log	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	at_log	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	aud_data	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	aud_data	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	aud_events	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	aud_events	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	aud_extract_session	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	aud_extract_session	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	aud_services	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	aud_services	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	aud_states	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	aud_states	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_class_registry	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_class_registry	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_custom_classes	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_custom_classes	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_custom_libraries	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_custom_libraries	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_languages	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_languages	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_locales	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_locales	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_lookup	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_lookup	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_system_properties	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_system_properties	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_timezones	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_timezones	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_tran_names	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_tran_names	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_tran_set_names	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_tran_set_names	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_account_types	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_account_types	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_bin_list_suppliers	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_bin_list_suppliers	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_card_sets	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_card_sets	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_card_types	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_card_types	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_limits	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_limits	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_limits_classes	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_limits_classes	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_totals_groups	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_totals_groups	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	crypto_dea1_group	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	crypto_dea1_group	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	crypto_dea1_key_transl_str	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	crypto_dea1_key_transl_str	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	crypto_hsm_groups	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	crypto_hsm_groups	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	crypto_hsm_types	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	crypto_hsm_types	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	crypto_keyspace	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	crypto_keyspace	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	dbr_application_operations	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	dbr_application_operations	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	dbr_application_versions	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	dbr_application_versions	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	dbr_dep_rollback_objects	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	dbr_dep_rollback_objects	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	dbr_gate_keeper	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	dbr_gate_keeper	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	dbr_sql_fragments	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	dbr_sql_fragments	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	inject_incoming_files	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	inject_incoming_files	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	inject_interfaces	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	inject_interfaces	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	inject_states	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	inject_states	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	inject_trans	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	inject_trans	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	inject_transmission	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	inject_transmission	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	ipm_incoming_files	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	ipm_incoming_files	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	irp_lazycache_reg	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	irp_lazycache_reg	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	irp_tran_routing	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	irp_tran_routing	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	lc_MEGKREPVB2_ia	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	lc_MEGKREPVB2_ia	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	lc_VCMS_ia	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	lc_VCMS_ia	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	lc_VCMSECREDIT_ia	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	lc_VCMSECREDIT_ia	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	mccredit_acq_mec_acc_ind	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	mccredit_acq_mec_acc_ind	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	mccredit_assigned_id	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	mccredit_assigned_id	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	mccredit_card_types	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	mccredit_card_types	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	mccredit_merc_mec_acc_ind	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	mccredit_merc_mec_acc_ind	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	mccredit_onln_chkout_range	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	mccredit_onln_chkout_range	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	mnt_refresh_proc_plan_lock	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	mnt_refresh_proc_plan_lock	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pin_at_pos_mcc_exclusions	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pin_at_pos_mcc_exclusions	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pki_ca_root_certs	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pki_ca_root_certs	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pki_certmgr_config	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pki_certmgr_config	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pki_exchange_log	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pki_exchange_log	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pki_external_certs	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pki_external_certs	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pki_keys	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pki_keys	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pki_local_certs	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pki_local_certs	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pki_requests	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pki_requests	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pki_trusted_addresses	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pki_trusted_addresses	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pl_lookup_category	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pl_lookup_category	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pl_run	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pl_run	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	postbridge_consl_fld_desc	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	postbridge_consl_fld_desc	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	postbridge_consl_flds	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	postbridge_consl_flds	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	postbridge_mac_config	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	postbridge_mac_config	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	postbridge_mac_flds	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	postbridge_mac_flds	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	prod_obj_cats	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	prod_obj_cats	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	prod_reg	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	prod_reg	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_m1MCCENT	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_m1MCCENT	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_m1MCCFBP	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_m1MCCFBP	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_m1MCCFCMB	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_m1MCCFCMB	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_m1MCCGTB	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_m1MCCGTB	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_m1MCCGTBSL	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_m1MCCGTBSL	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_m1MCCIBP	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_m1MCCIBP	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_m1MCCIBTC	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_m1MCCIBTC	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_m1MCCOBI	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_m1MCCOBI	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_m1MCCUBN	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_m1MCCUBN	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_MEGKREPVB2_sk_v4_1	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_MEGKREPVB2_sk_v4_1	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_VCMS_sk_v4_1	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_VCMS_sk_v4_1	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_VCMSECREDIT_sk_v4_1	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_VCMSECREDIT_sk_v4_1	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pth_VisaSwitchKey_sk_v4_1	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pth_VisaSwitchKey_sk_v4_1	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	qrtz_blob_triggers	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	qrtz_blob_triggers	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	qrtz_calendars	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	qrtz_calendars	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	qrtz_fired_triggers	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	qrtz_fired_triggers	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	qrtz_job_details	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	qrtz_job_details	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	qrtz_locks	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	qrtz_locks	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	qrtz_paused_trigger_grps	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	qrtz_paused_trigger_grps	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	qrtz_scheduler_state	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	qrtz_scheduler_state	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	rb8ea11976_020000_inject_trans_field	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	rb8ea11976_020000_inject_trans_field	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	rollback_table_postinject_2_0_Patch_1_inject_trans	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	rollback_table_postinject_2_0_Patch_1_inject_trans	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	rollback_table_postinject_2_0_Patch_1_inject_transmission	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	rollback_table_postinject_2_0_Patch_1_inject_transmission	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	scheduled_jobs	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	scheduled_jobs	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_auth_token	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_auth_token	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_groups	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_groups	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_ldap_types	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_ldap_types	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_override_type	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_override_type	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_passwords	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_passwords	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_perm_cats	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_perm_cats	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_user_types	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_user_types	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	ssb_fi_ext_config	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	ssb_fi_ext_config	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_email_config	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_email_config	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_email_log	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_email_log	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_event_interfaces	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_event_interfaces	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_event_log	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_event_log	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_regions	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_regions	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	task_uptime	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	task_uptime	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tasks	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tasks	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	term_groups	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	term_groups	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_bus_calendars	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_bus_calendars	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_command_requests	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_command_requests	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_countries	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_countries	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_currencies	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_currencies	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_currencies_shadow	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_currencies_shadow	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_hotcards_1	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_hotcards_1	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_hotcards_2	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_hotcards_2	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_hotcards_lock	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_hotcards_lock	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_loaders_downloads	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_loaders_downloads	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_loaders_loads	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_loaders_loads	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_routing_groups	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_routing_groups	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_routing_priorities	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_routing_priorities	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_settlement_entities	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_settlement_entities	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_surcharge_states	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_surcharge_states	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_groups	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_groups	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_legs_1	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_legs_1	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_legs_2	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_legs_2	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_legs_3	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_legs_3	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_legs_4	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_legs_4	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_matches_1	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_matches_1	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_matches_2	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_matches_2	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_matches_3	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_matches_3	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_matches_4	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_matches_4	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_present_stmt	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_present_stmt	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_profile	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_profile	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_volumes	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_volumes	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_trans_1	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_trans_1	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_trans_2	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_trans_2	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_trans_3	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_trans_3	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_trans_4	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_trans_4	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_trans_ret_1	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_trans_ret_1	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_trans_ret_2	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_trans_ret_2	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_trans_ret_3	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_trans_ret_3	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_trans_ret_4	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_trans_ret_4	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tv_partition_info	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tv_partition_info	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_ui_functions_to_tm	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_ui_functions_to_tm	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_vipcards	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_vipcards	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	visabase12_admin_msg	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	visabase12_admin_msg	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	visabase12_cps_aq_inst_map	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	visabase12_cps_aq_inst_map	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	visabase12_fleetcards	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	visabase12_fleetcards	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	visabase12_incoming_files	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	visabase12_incoming_files	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	visabase12_issuer_rsp_map	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	visabase12_issuer_rsp_map	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	visabase12_map	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	visabase12_map	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	visabase12_mcc_ia	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	visabase12_mcc_ia	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	visabase12_merch_cfg	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	visabase12_merch_cfg	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	visabase12_status_chk_map	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	visabase12_status_chk_map	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	aa_lnk_mon	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	aa_lnk_mon	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	aa_msg_q_cfg	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	aa_msg_q_cfg	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	aud_actions	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	aud_actions	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	aud_records	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	aud_records	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_er_app_scribes	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_er_app_scribes	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_tran_sets	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_tran_sets	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_trends	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_trends	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_account_profiles	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_account_profiles	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_allowed_cards	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_allowed_cards	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_card_profiles	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_card_profiles	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_languages	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_languages	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	crypto_custom_key_types	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	crypto_custom_key_types	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	crypto_dea1_keys	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	crypto_dea1_keys	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	crypto_hsms	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	crypto_hsms	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	crypto_services_hsms	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	crypto_services_hsms	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	crypto_variant_types	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	crypto_variant_types	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	dbr_application_objects	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	dbr_application_objects	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	node_interface	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	node_interface	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pki_ssl_saps	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pki_ssl_saps	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pl_lookup	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pl_lookup	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pl_run_phase	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pl_run_phase	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pp_financial_institutions	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pp_financial_institutions	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	prod_class_reg	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	prod_class_reg	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	qrtz_job_listeners	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	qrtz_job_listeners	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	qrtz_triggers	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	qrtz_triggers	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_authenticators	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_authenticators	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_group_prod_policy	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_group_prod_policy	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_ldap_cfgs	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_ldap_cfgs	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_preferences	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_preferences	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_pwd_policy	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_pwd_policy	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_roles	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_roles	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_users	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_users	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_event_log_bin	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_event_log_bin	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_event_log_open	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_event_log_open	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_event_log_params	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_event_log_params	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_event_log_rsps	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_event_log_rsps	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_events	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_events	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_teams	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_teams	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	term_type	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	term_type	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_acquirer	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_acquirer	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_acquirer_batch_lookup	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_acquirer_batch_lookup	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_batches	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_batches	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_bus_calendar_dates	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_bus_calendar_dates	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_bus_calendar_holidays	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_bus_calendar_holidays	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_card_acceptor	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_card_acceptor	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_cardaccptr_batch_lookup	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_cardaccptr_batch_lookup	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_issuers	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_issuers	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_nodes	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_nodes	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_regions	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_regions	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_switch_batch_lookup	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_switch_batch_lookup	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_term_batch_lookup	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_term_batch_lookup	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_group_defn	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_group_defn	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	visabase12_incoming_excps	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	visabase12_incoming_excps	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	aa_msg_q	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	aa_msg_q	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	applications	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	applications	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_trend_mon_entities	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_trend_mon_entities	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cfg_trend_thresholds	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cfg_trend_thresholds	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_allowed_trans	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_allowed_trans	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_cards	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_cards	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_limits_profiles	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_limits_profiles	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	crypto_dea1_key_group	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	crypto_dea1_key_group	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	crypto_hsm_properties	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	crypto_hsm_properties	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	node	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	node	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	participant	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	participant	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pki_sap_external_certs	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pki_sap_external_certs	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pl_run_phase_detail	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pl_run_phase_detail	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pp_employee	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pp_employee	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pp_fi_issuers	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pp_fi_issuers	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pp_fi_prod_reg	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pp_fi_prod_reg	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	qrtz_cron_triggers	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	qrtz_cron_triggers	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	qrtz_simple_triggers	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	qrtz_simple_triggers	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	qrtz_trigger_listeners	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	qrtz_trigger_listeners	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_group_authenticators	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_group_authenticators	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_group_ldap	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_group_ldap	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_ldap_users	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_ldap_users	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_permissions	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_permissions	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_product_users	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_product_users	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_user_preferences	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_user_preferences	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_user_role_map	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_user_role_map	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_event_descriptions	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_event_descriptions	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	support_members	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	support_members	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	term_hardware_type_descr	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	term_hardware_type_descr	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	term_misc	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	term_misc	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	term_status_type_descr	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	term_status_type_descr	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_control_nodes	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_control_nodes	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_routes	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_routes	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_routes_by_inst	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_routes_by_inst	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_settlement_dependencies	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_settlement_dependencies	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_sink_nodes	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_sink_nodes	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_source_nodes	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_source_nodes	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_tran_notifications	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_tran_notifications	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_accounts	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_accounts	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	cp_bins	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	cp_bins	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	inject_msg_injectors	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	inject_msg_injectors	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	node_saps	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	node_saps	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	participant_user_rights	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	participant_user_rights	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	participants_sink_nodes	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	participants_sink_nodes	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	participants_source_nodes	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	participants_source_nodes	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pl_run_phase_detail_params	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pl_run_phase_detail_params	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	pp_fi_participants	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	pp_fi_participants	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_cat_perm_map	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_cat_perm_map	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_instance_permissions	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_instance_permissions	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_prd_prm_cfg	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_prd_prm_cfg	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_prod_perm_map	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_prod_perm_map	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_product_perm_map	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_product_perm_map	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_pwd_history	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_pwd_history	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_role_perm_map	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_role_perm_map	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_scope	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_scope	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_usr_perm_ovrd	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_usr_perm_ovrd	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	term	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	term	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	term_hardware	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	term_hardware	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	term_hardware_type	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	term_hardware_type	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	term_status	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	term_status	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	term_status_type	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	term_status_type	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_integration_pipeline	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_integration_pipeline	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_routes_by_sink_inst	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_routes_by_sink_inst	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	tm_sink_node_mapped_fields	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	tm_sink_node_mapped_fields	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	visabase12_cards	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	visabase12_cards	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	node_conns	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	node_conns	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_rl_inst_perms	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_rl_inst_perms	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	sec_usr_inst_perms	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	sec_usr_inst_perms	) old_realtime
union all SELECT (	SELECT COUNT(*) FROM 	term_group_terms	) new_realtime,(	SELECT COUNT(*) FROM 	[realtime_old].dbo.	term_group_terms	) old_realtime
