EXEC  

usp_clear_settlement_data_quick

GO

INSERT INTO dbo.sstl_config_set  select * FROM  [172.25.10.89].[postilion_office].[dbo].sstl_config_set 

--INSERT INTO spay_acc_rel_type(acc_rel_type_id,acc_rel_type_name,description,java_class_name,user_param_list_desc) SELECT acc_rel_type_id,acc_rel_type_name,description,java_class_name,user_param_list_desc FROM  [172.25.10.89].[postilion_office].[dbo].[spay_acc_rel_type] 
--INSERT INTO spay_aggr_strategy(strategy_id,strategy_name,java_class_name,user_param_list_desc) SELECT strategy_id,strategy_name,java_class_name,user_param_list_desc FROM  [172.25.10.89].[postilion_office].[dbo].[spay_aggr_strategy] 
INSERT INTO spay_amount_pay_next_date(spay_session_id,config_set_id,se_id,amount_id,next_payment_date) SELECT spay_session_id,config_set_id,se_id,amount_id,next_payment_date FROM  [172.25.10.89].[postilion_office].[dbo].[spay_amount_pay_next_date] 
INSERT INTO spay_fee_pay_next_date(spay_session_id,config_set_id,se_id,fee_id,next_payment_date) SELECT spay_session_id,config_set_id,se_id,fee_id,next_payment_date FROM  [172.25.10.89].[postilion_office].[dbo].[spay_fee_pay_next_date] 
--INSERT INTO spay_plugin(plugin_id,description,java_class_name,user_param_list_desc) SELECT plugin_id,description,java_class_name,user_param_list_desc FROM  [172.25.10.89].[postilion_office].[dbo].[spay_plugin] 
INSERT INTO spay_residue_ach(payment_id,spay_session_id,origin_bank_account,destination_bank_account,aggregation_reference,amount_original,amount_total,amount_paid,residue_prev,residue_unpaid) SELECT payment_id,spay_session_id,origin_bank_account,destination_bank_account,aggregation_reference,amount_original,amount_total,amount_paid,residue_prev,residue_unpaid FROM  [172.25.10.89].[postilion_office].[dbo].[spay_residue_ach] 
--INSERT INTO spay_residue_strategy(strategy_id,strategy_name,java_class_name,user_param_list_desc) SELECT strategy_id,strategy_name,java_class_name,user_param_list_desc FROM  [172.25.10.89].[postilion_office].[dbo].[spay_residue_strategy] 
INSERT INTO spst_aggr_strategy(strategy_id,strategy_name,java_class_name,user_param_list_desc) SELECT strategy_id,strategy_name,java_class_name,user_param_list_desc FROM  [172.25.10.89].[postilion_office].[dbo].[spst_aggr_strategy] 
INSERT INTO spst_amount_pst_next_date(spst_session_id,config_set_id,se_id,amount_id,next_posting_date) SELECT spst_session_id,config_set_id,se_id,amount_id,next_posting_date FROM  [172.25.10.89].[postilion_office].[dbo].[spst_amount_pst_next_date] 
INSERT INTO spst_fee_pst_next_date(spst_session_id,config_set_id,se_id,fee_id,next_posting_date) SELECT spst_session_id,config_set_id,se_id,fee_id,next_posting_date FROM  [172.25.10.89].[postilion_office].[dbo].[spst_fee_pst_next_date] 
INSERT INTO spst_plugin(plugin_id,description,java_class_name,user_param_list_desc) SELECT plugin_id,description,java_class_name,user_param_list_desc FROM  [172.25.10.89].[postilion_office].[dbo].[spst_plugin] 
INSERT INTO spst_residue_strategy(strategy_id,strategy_name,java_class_name,user_param_list_desc) SELECT strategy_id,strategy_name,java_class_name,user_param_list_desc FROM  [172.25.10.89].[postilion_office].[dbo].[spst_residue_strategy] 
--INSERT INTO sstl_config_set(config_set_id,name) SELECT config_set_id,name FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_config_set] 
INSERT INTO sstl_exception(session_id,config_set_id,datetime_added,post_tran_id,sdi_tran_id,state,description,settled_session_id) SELECT session_id,config_set_id,datetime_added,post_tran_id,sdi_tran_id,state,description,settled_session_id FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_exception] 
--INSERT INTO sstl_fee_calc_strat(fee_calc_strat_id,name,description,java_class_name) SELECT fee_calc_strat_id,name,description,java_class_name FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_fee_calc_strat] 
--INSERT INTO sstl_func(func_id,func_cat,func_name,description,param_list_description,java_class_name) SELECT func_id,func_cat,func_name,description,param_list_description,java_class_name FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_func] 
INSERT INTO sstl_journal_1(entry_id,config_set_id,session_id,post_tran_id,post_tran_cust_id,sdi_tran_id,acc_post_id,nt_fee_acc_post_id,coa_id,coa_se_id,se_id,amount,amount_id,amount_value_id,fee,fee_id,fee_value_id,nt_fee,nt_fee_id,nt_fee_value_id,debit_acc_nr_id,debit_acc_id,debit_cardholder_acc_id,debit_cardholder_acc_type,credit_acc_nr_id,credit_acc_id,credit_cardholder_acc_id,credit_cardholder_acc_type,business_date,granularity_element,tag,spay_session_id,spst_session_id) SELECT entry_id,config_set_id,session_id,post_tran_id,post_tran_cust_id,sdi_tran_id,acc_post_id,nt_fee_acc_post_id,coa_id,coa_se_id,se_id,amount,amount_id,amount_value_id,fee,fee_id,fee_value_id,nt_fee,nt_fee_id,nt_fee_value_id,debit_acc_nr_id,debit_acc_id,debit_cardholder_acc_id,debit_cardholder_acc_type,credit_acc_nr_id,credit_acc_id,credit_cardholder_acc_id,credit_cardholder_acc_type,business_date,granularity_element,tag,spay_session_id,spst_session_id FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_1] 
INSERT INTO sstl_journal_adj(adj_id,entry_id,config_set_id,session_id,config_version,post_tran_id,post_tran_cust_id,sdi_tran_id,acc_post_id,nt_fee_acc_post_id,coa_id,coa_se_id,se_id,amount,amount_id,amount_value_id,fee,fee_id,fee_value_id,nt_fee,nt_fee_id,nt_fee_value_id,debit_acc_nr_id,debit_acc_id,debit_cardholder_acc_id,debit_cardholder_acc_type,credit_acc_nr_id,credit_acc_id,credit_cardholder_acc_id,credit_cardholder_acc_type,business_date,granularity_element,tag,spay_session_id,spst_session_id,description) SELECT adj_id,entry_id,config_set_id,session_id,config_version,post_tran_id,post_tran_cust_id,sdi_tran_id,acc_post_id,nt_fee_acc_post_id,coa_id,coa_se_id,se_id,amount,amount_id,amount_value_id,fee,fee_id,fee_value_id,nt_fee,nt_fee_id,nt_fee_value_id,debit_acc_nr_id,debit_acc_id,debit_cardholder_acc_id,debit_cardholder_acc_type,credit_acc_nr_id,credit_acc_id,credit_cardholder_acc_id,credit_cardholder_acc_type,business_date,granularity_element,tag,spay_session_id,spst_session_id,description FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_adj]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
--INSERT INTO sstl_journal_entry_insert_fltr(journal_entry_insert_fltr_id,name,java_class_name) SELECT journal_entry_insert_fltr_id,name,java_class_name FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_entry_insert_fltr] 
--INSERT INTO sstl_journal_fltr(fltr_id,fltr_name,java_class_name,param_list_description) SELECT fltr_id,fltr_name,java_class_name,param_list_description FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr] 
--INSERT INTO sstl_journal_fltr_grp_w(config_set_id,fltr_grp_id,description,config_state) SELECT config_set_id,fltr_grp_id,description,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr_grp_w] 
--INSERT INTO sstl_journal_part_info(partition_nr,min_row_nr,max_row_nr,refresh_row_nr,start_date,end_date,state) SELECT partition_nr,min_row_nr,max_row_nr,refresh_row_nr,start_date,end_date,state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_part_info] 
--INSERT INTO sstl_method(method_name,java_class_name,user_param_list_desc) SELECT method_name,java_class_name,user_param_list_desc FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_method] 
INSERT INTO sstl_nt_fee_calc_strat(nt_fee_calc_strat_id,name,description,java_class_name) SELECT nt_fee_calc_strat_id,name,description,java_class_name FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_nt_fee_calc_strat] 
INSERT INTO sstl_nt_fee_levy_hist(config_set_id,nt_fee_value_id,session_id,date_levied,next_levy_date) SELECT config_set_id,nt_fee_value_id,session_id,date_levied,next_levy_date FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_nt_fee_levy_hist] 
INSERT INTO sstl_table_meta_data(table_name,column_name,type,length,nullable) SELECT table_name,column_name,type,length,nullable FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_table_meta_data] 
--INSERT INTO sstl_tran_set(tran_set_name,java_class_name,user_param_list_desc) SELECT tran_set_name,java_class_name,user_param_list_desc FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_tran_set] 

SET IDENTITY_INSERT sstl_se_nt_fee_value_w ON 
INSERT INTO sstl_se_nt_fee_value_w(config_set_id,nt_fee_value_id,se_id,nt_fee_id,description,frequency,start_date,fixed_amount,nt_fee_calc_strat_id,config_state) SELECT config_set_id,nt_fee_value_id,se_id,nt_fee_id,description,frequency,start_date,fixed_amount,nt_fee_calc_strat_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_nt_fee_value_w] 
 SET IDENTITY_INSERT sstl_se_nt_fee_value_w OFF 

SET IDENTITY_INSERT sstl_se_nt_fee_value_w ON 
INSERT INTO sstl_se_nt_fee_value_w(config_set_id,nt_fee_value_id,se_id,nt_fee_id,description,frequency,start_date,fixed_amount,nt_fee_calc_strat_id,config_state) SELECT config_set_id,nt_fee_value_id,se_id,nt_fee_id,description,frequency,start_date,fixed_amount,nt_fee_calc_strat_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_nt_fee_value_w] 
 SET IDENTITY_INSERT sstl_se_nt_fee_value_w OFF 
INSERT INTO spay_se_amount_pay_freq_w(config_set_id,amount_id,se_id,frequency,start_date,config_state) SELECT config_set_id,amount_id,se_id,frequency,start_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_amount_pay_freq_w] 
INSERT INTO sstl_pred_w(config_set_id,pred_id,description,config_state) SELECT config_set_id,pred_id,description,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_pred_w] 
--INSERT INTO sstl_pred_prop_value_w(config_set_id,pred_id,prop_value_id,prop_id,exclude,config_state) SELECT config_set_id,pred_id,prop_value_id,prop_id,exclude,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_pred_prop_value_w] 
INSERT INTO spay_se_fee_pay_freq_w(config_set_id,fee_id,se_id,frequency,start_date,config_state) SELECT config_set_id,fee_id,se_id,frequency,start_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_fee_pay_freq_w] 

SET IDENTITY_INSERT sstl_se_acc_nr_w ON 
--INSERT INTO sstl_se_acc_nr_w(config_set_id,acc_nr_id,se_id,acc_id,acc_nr,state,config_state) SELECT config_set_id,acc_nr_id,se_id,acc_id,acc_nr,state,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_acc_nr_w] 
 SET IDENTITY_INSERT sstl_se_acc_nr_w OFF 
--INSERT INTO sstl_se_rule_w(config_set_id,rule_id,name,description,se_id,type,pred_id,modified_rule_id,state,active,journal_entry_insert_fltr_id,config_state) SELECT config_set_id,rule_id,name,description,se_id,type,pred_id,modified_rule_id,state,active,journal_entry_insert_fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_rule_w] 

SET IDENTITY_INSERT sstl_coa_w ON 
INSERT INTO sstl_coa_w(config_set_id,coa_id,name,description,type,config_state) SELECT config_set_id,coa_id,name,description,type,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_coa_w] 
 SET IDENTITY_INSERT sstl_coa_w OFF 
--INSERT INTO sstl_se_rule_w(config_set_id,rule_id,name,description,se_id,type,pred_id,modified_rule_id,state,active,journal_entry_insert_fltr_id,config_state) SELECT config_set_id,rule_id,name,description,se_id,type,pred_id,modified_rule_id,state,active,journal_entry_insert_fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_rule_w] 

SET IDENTITY_INSERT sstl_acc_w ON 
--INSERT INTO sstl_acc_w(config_set_id,acc_id,coa_id,name,description,config_state) SELECT config_set_id,acc_id,coa_id,name,description,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_acc_w] 
 SET IDENTITY_INSERT sstl_acc_w OFF 

SET IDENTITY_INSERT sstl_se_rule_acc_post_w ON 
--INSERT INTO sstl_se_rule_acc_post_w(config_set_id,acc_post_id,rule_id,amount_id,fee_id,coa_id,debit_acc_id,debit_cardholder_acc,credit_acc_id,credit_cardholder_acc,expr_granularity_element,expr_tag,config_state) SELECT config_set_id,acc_post_id,rule_id,amount_id,fee_id,coa_id,debit_acc_id,debit_cardholder_acc,credit_acc_id,credit_cardholder_acc,expr_granularity_element,expr_tag,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_rule_acc_post_w] 
 SET IDENTITY_INSERT sstl_se_rule_acc_post_w OFF 
--INSERT INTO spst_proc_ent_w(entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state) SELECT entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_proc_ent_w] 
--INSERT INTO sstl_se_type(config_set_id,se_type_id,name,description,icon_path) SELECT config_set_id,se_type_id,name,description,icon_path FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_type] 
--INSERT INTO spst_proc_ent_w(entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state) SELECT entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_proc_ent_w] 
--INSERT INTO spst_proc_ent_w(entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state) SELECT entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_proc_ent_w] 
--INSERT INTO spst_proc_ent_w(entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state) SELECT entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_proc_ent_w] 


INSERT INTO dbo.sstl_se_type SELECT * FROM [172.25.10.89].[postilion_office].[dbo].sstl_se_type
SET IDENTITY_INSERT sstl_se_w ON 
INSERT INTO sstl_se_w(config_set_id,se_id,name,description,parent_id,coa_id,se_type_id,rel_type,config_state) SELECT config_set_id,se_id,name,description,parent_id,coa_id,se_type_id,rel_type,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_w] 
 SET IDENTITY_INSERT sstl_se_w OFF 
 
 
SET IDENTITY_INSERT sstl_se_amount_w ON 
INSERT INTO sstl_se_amount_w(config_set_id,amount_id,se_id,name,description,config_state) SELECT config_set_id,amount_id,se_id,name,description,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_amount_w] 
 SET IDENTITY_INSERT sstl_se_amount_w OFF 

SET IDENTITY_INSERT sstl_se_fee_w ON 
INSERT INTO sstl_se_fee_w(config_set_id,fee_id,se_id,name,description,type,amount_id,config_state) SELECT config_set_id,fee_id,se_id,name,description,type,amount_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_fee_w] 
 SET IDENTITY_INSERT sstl_se_fee_w OFF 
--INSERT INTO sstl_config_version(config_version,config_set_id,description,datetime_committed,datetime_activated) SELECT config_version,config_set_id,description,datetime_committed,datetime_activated FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_config_version]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))


--INSERT INTO spst_proc_ent_fltr_grp_w(config_set_id,entity_id,fltr_grp_id,config_state) SELECT config_set_id,entity_id,fltr_grp_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_proc_ent_fltr_grp_w] 
--INSERT INTO spst_proc_ent_fltr_grp_w(config_set_id,entity_id,fltr_grp_id,config_state) SELECT config_set_id,entity_id,fltr_grp_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_proc_ent_fltr_grp_w] 
--INSERT INTO sstl_tran_ident_w(config_set_id,tran_ident_id,description,se_id,config_state) SELECT config_set_id,tran_ident_id,description,se_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_tran_ident_w] 
INSERT INTO sstl_se_third_party_w(config_set_id,se_id,third_party_se_id,pred_id,config_state) SELECT config_set_id,se_id,third_party_se_id,pred_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_third_party_w] 
--INSERT INTO sstl_tran_ident_def_w(config_set_id,tran_ident_def_id,tran_ident_id,tran_field_id,field_value,config_state) SELECT config_set_id,tran_ident_def_id,tran_ident_id,tran_field_id,field_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_tran_ident_def_w] 
INSERT INTO spst_se_amount_pst_freq_w(config_set_id,amount_id,se_id,frequency,start_date,config_state) SELECT config_set_id,amount_id,se_id,frequency,start_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_se_amount_pst_freq_w] 

INSERT INTO spst_se_fee_pst_freq_w(config_set_id,fee_id,se_id,frequency,start_date,config_state) SELECT config_set_id,fee_id,se_id,frequency,start_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_se_fee_pst_freq_w] 


SET IDENTITY_INSERT sstl_se_amount_value_w ON 
INSERT INTO sstl_se_amount_value_w(config_set_id,amount_value_id,se_id,amount_id,description,pred_id,tiered,expr_domain,modified_amount_value_id,state,config_state,tax_indicator) SELECT config_set_id,amount_value_id,se_id,amount_id,description,pred_id,tiered,expr_domain,modified_amount_value_id,state,config_state,0 FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_amount_value_w]  --WHERE  tax_indicator IS NOT NULL
 SET IDENTITY_INSERT sstl_se_amount_value_w OFF 
INSERT INTO sstl_journal_fltr_grp_elem_w(config_set_id,fltr_grp_elem_id,fltr_grp_id,fltr_id,config_state) SELECT config_set_id,fltr_grp_elem_id,fltr_grp_id,fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr_grp_elem_w] 
INSERT INTO sstl_journal_fltr_grp_elem_w(config_set_id,fltr_grp_elem_id,fltr_grp_id,fltr_id,config_state) SELECT config_set_id,fltr_grp_elem_id,fltr_grp_id,fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr_grp_elem_w] 
INSERT INTO sstl_journal_fltr_grp_elem_w(config_set_id,fltr_grp_elem_id,fltr_grp_id,fltr_id,config_state) SELECT config_set_id,fltr_grp_elem_id,fltr_grp_id,fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr_grp_elem_w] 
--INSERT INTO sstl_se_amount_value_int_w(config_set_id,amount_value_int_id,amount_value_id,lower_bound,expr_amount,config_state) SELECT config_set_id,amount_value_int_id,amount_value_id,lower_bound,expr_amount,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_amount_value_int_w] 
INSERT INTO sstl_se_cal_w(config_set_id,cal_id,se_id,name,description,priority,config_state) SELECT config_set_id,cal_id,se_id,name,description,priority,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_cal_w] 
INSERT INTO ssdi_proc_ent_w(entity_id,plugin_id,name,config_set_id,input,user_param_list,config_state) SELECT entity_id,plugin_id,name,config_set_id,input,user_param_list,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[ssdi_proc_ent_w] 
INSERT INTO sstl_se_cal_date_range_w(config_set_id,date_range_id,cal_id,start_date,end_date,config_state) SELECT config_set_id,date_range_id,cal_id,start_date,end_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_cal_date_range_w] 
INSERT INTO spay_se_acc_w(config_set_id,se_id,acc_id,bank_name,inst_code,branch_code,bank_routing_nr,account_name,account_nr,account_type,contact_id_bank,contact_id_accountholder,notes,config_state) SELECT config_set_id,se_id,acc_id,bank_name,inst_code,branch_code,bank_routing_nr,account_name,account_nr,account_type,contact_id_bank,contact_id_accountholder,notes,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_acc_w] 


INSERT INTO postilion_office.dbo.sstl_se_fee_priority_w SELECT * FROM  [172.25.10.89].postilion_office.dbo.sstl_se_fee_priority_w
  ALTER TABLE sstl_se_fee_value_w NOCHECK  CONSTRAINT  fk_sstl_fee_val_3  
SET IDENTITY_INSERT sstl_se_fee_value_w ON 
INSERT INTO sstl_se_fee_value_w(config_set_id,fee_value_id,se_id,description,fee_id,pred_id,min_value,max_value,cal_id,percentage,fixed_amount,fee_calc_strat_id,modified_fee_value_id,state,config_state,tax_indicator) SELECT config_set_id,fee_value_id,se_id,description,fee_id,pred_id,min_value,max_value,cal_id,percentage,fixed_amount,fee_calc_strat_id,modified_fee_value_id,state,config_state,0 FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_fee_value_w] -- WHERE  tax_indicator IS NOT NULL
 SET IDENTITY_INSERT sstl_se_fee_value_w OFF 
INSERT INTO spay_se_acc_rel_w(acc_rel_id,config_set_id,se_id,gl_acc_nr_id,origin_acc_id,destination_acc_id,acc_rel_type_id,inverted,config_state) SELECT acc_rel_id,config_set_id,se_id,gl_acc_nr_id,origin_acc_id,destination_acc_id,acc_rel_type_id,inverted,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_acc_rel_w] 
--INSERT INTO sstl_proc_ent_w(entity_id,entity_name,config_set_id,method_name,method_param,import_method_name,import_method_param,tran_set_name,tran_set_param,config_state) SELECT entity_id,entity_name,config_set_id,method_name,method_param,import_method_name,import_method_param,tran_set_name,tran_set_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_proc_ent_w] 
INSERT INTO spay_se_acc_rel_w(acc_rel_id,config_set_id,se_id,gl_acc_nr_id,origin_acc_id,destination_acc_id,acc_rel_type_id,inverted,config_state) SELECT acc_rel_id,config_set_id,se_id,gl_acc_nr_id,origin_acc_id,destination_acc_id,acc_rel_type_id,inverted,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_acc_rel_w] 
--INSERT INTO sstl_proc_ent_w(entity_id,entity_name,config_set_id,method_name,method_param,import_method_name,import_method_param,tran_set_name,tran_set_param,config_state) SELECT entity_id,entity_name,config_set_id,method_name,method_param,import_method_name,import_method_param,tran_set_name,tran_set_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_proc_ent_w] 
--INSERT INTO sstl_proc_ent_w(entity_id,entity_name,config_set_id,method_name,method_param,import_method_name,import_method_param,tran_set_name,tran_set_param,config_state) SELECT entity_id,entity_name,config_set_id,method_name,method_param,import_method_name,import_method_param,tran_set_name,tran_set_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_proc_ent_w] 

SET IDENTITY_INSERT sstl_se_fee_value_w ON 
--INSERT INTO sstl_se_fee_value_w(config_set_id,fee_value_id,se_id,description,fee_id,pred_id,min_value,max_value,cal_id,percentage,fixed_amount,fee_calc_strat_id,modified_fee_value_id,state,config_state,tax_indicator) SELECT config_set_id,fee_value_id,se_id,description,fee_id,pred_id,min_value,max_value,cal_id,percentage,fixed_amount,fee_calc_strat_id,modified_fee_value_id,state,config_state,0 FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_fee_value_w]  ---WHERE  tax_indicator  IS NOT NULL
 SET IDENTITY_INSERT sstl_se_fee_value_w OFF 
--INSERT INTO sstl_session(session_id,entity_id,config_set_id,config_version,datetime_started,last_post_tran_id,last_sdi_tran_id,completed) SELECT session_id,entity_id,config_set_id,config_version,datetime_started,last_post_tran_id,last_sdi_tran_id,completed FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_session]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
--INSERT INTO sstl_se_fee_priority_w(config_set_id,se_id,fee_id,priority) SELECT config_set_id,se_id,fee_id,priority FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_fee_priority_w] 
INSERT INTO sstl_tran_field_w(config_set_id,tran_field_id,tran_field,expr_tran_field,data_type,config_state) SELECT config_set_id,tran_field_id,tran_field,expr_tran_field,data_type,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_tran_field_w] 
INSERT INTO sstl_prop_w(config_set_id,prop_id,prop,default_prop_value,config_state) SELECT config_set_id,prop_id,prop,default_prop_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_prop_w] 
INSERT INTO spay_proc_ent_w(entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state) SELECT entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_proc_ent_w] 

SET IDENTITY_INSERT sstl_se_nt_fee_w ON 
INSERT INTO sstl_se_nt_fee_w(config_set_id,nt_fee_id,se_id,name,description,journal_entry_insert_fltr_id,config_state) SELECT config_set_id,nt_fee_id,se_id,name,description,journal_entry_insert_fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_nt_fee_w] 
 SET IDENTITY_INSERT sstl_se_nt_fee_w OFF 
INSERT INTO spay_proc_ent_w(entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state) SELECT entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_proc_ent_w] 
INSERT INTO spay_proc_ent_w(entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state) SELECT entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_proc_ent_w] 

SET IDENTITY_INSERT sstl_se_nt_fee_w ON 
INSERT INTO sstl_se_nt_fee_w(config_set_id,nt_fee_id,se_id,name,description,journal_entry_insert_fltr_id,config_state) SELECT config_set_id,nt_fee_id,se_id,name,description,journal_entry_insert_fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_nt_fee_w] 
 SET IDENTITY_INSERT sstl_se_nt_fee_w OFF 
INSERT INTO spay_proc_ent_w(entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state) SELECT entity_id,entity_name,config_set_id,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_proc_ent_w] 
INSERT INTO sstl_prop_value_w(config_set_id,prop_value_id,prop_id,prop_value,root_node_id,config_state) SELECT config_set_id,prop_value_id,prop_id,prop_value,root_node_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_prop_value_w] 

SET IDENTITY_INSERT sstl_se_nt_fee_acc_post_w ON 
INSERT INTO sstl_se_nt_fee_acc_post_w(config_set_id,nt_fee_acc_post_id,nt_fee_id,coa_id,debit_acc_id,credit_acc_id,config_state) SELECT config_set_id,nt_fee_acc_post_id,nt_fee_id,coa_id,debit_acc_id,credit_acc_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_nt_fee_acc_post_w] 
 SET IDENTITY_INSERT sstl_se_nt_fee_acc_post_w OFF 
INSERT INTO spay_proc_ent_fltr_grp_w(config_set_id,entity_id,fltr_grp_id,config_state) SELECT config_set_id,entity_id,fltr_grp_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_proc_ent_fltr_grp_w] 
INSERT INTO spay_proc_ent_fltr_grp_w(config_set_id,entity_id,fltr_grp_id,config_state) SELECT config_set_id,entity_id,fltr_grp_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_proc_ent_fltr_grp_w] 
INSERT INTO sstl_prop_value_node_w(config_set_id,node_id,parent_node_id,root_node_id,operator,inherited_prop_value_id,tran_field_id,field_operator,field_value,config_state) SELECT config_set_id,node_id,parent_node_id,root_node_id,operator,inherited_prop_value_id,tran_field_id,field_operator,field_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_prop_value_node_w] 
INSERT INTO spay_se_fee_pay_freq(config_version,config_set_id,fee_id,se_id,frequency,start_date,config_state) SELECT config_version,config_set_id,fee_id,se_id,frequency,start_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_fee_pay_freq]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_se_fee_pay_freq(config_version,config_set_id,fee_id,se_id,frequency,start_date,config_state) SELECT config_version,config_set_id,fee_id,se_id,frequency,start_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_fee_pay_freq]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_session(session_id,entity_id,datetime_started,file_name,config_version,completed) SELECT session_id,entity_id,datetime_started,file_name,config_version,completed FROM  [172.25.10.89].[postilion_office].[dbo].[spay_session]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_journal_fltr_param(config_version,config_set_id,fltr_param_id,fltr_grp_elem_id,fltr_param_value,config_state) SELECT config_version,config_set_id,fltr_param_id,fltr_grp_elem_id,fltr_param_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr_param]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_journal_fltr_param(config_version,config_set_id,fltr_param_id,fltr_grp_elem_id,fltr_param_value,config_state) SELECT config_version,config_set_id,fltr_param_id,fltr_grp_elem_id,fltr_param_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr_param]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_pred(config_version,config_set_id,pred_id,description,config_state) SELECT config_version,config_set_id,pred_id,description,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_pred]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_pred(config_version,config_set_id,pred_id,description,config_state) SELECT config_version,config_set_id,pred_id,description,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_pred]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_rule(config_version,config_set_id,rule_id,name,description,se_id,type,pred_id,modified_rule_id,state,active,journal_entry_insert_fltr_id,config_state) SELECT config_version,config_set_id,rule_id,name,description,se_id,type,pred_id,modified_rule_id,state,active,journal_entry_insert_fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_rule]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_rule(config_version,config_set_id,rule_id,name,description,se_id,type,pred_id,modified_rule_id,state,active,journal_entry_insert_fltr_id,config_state) SELECT config_version,config_set_id,rule_id,name,description,se_id,type,pred_id,modified_rule_id,state,active,journal_entry_insert_fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_rule]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_fee_priority(config_version,config_set_id,se_id,fee_id,priority) SELECT config_version,config_set_id,se_id,fee_id,priority FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_fee_priority]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_fee_priority(config_version,config_set_id,se_id,fee_id,priority) SELECT config_version,config_set_id,se_id,fee_id,priority FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_fee_priority]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_coa(config_version,config_set_id,coa_id,name,description,type,config_state) SELECT config_version,config_set_id,coa_id,name,description,type,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_coa]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_coa(config_version,config_set_id,coa_id,name,description,type,config_state) SELECT config_version,config_set_id,coa_id,name,description,type,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_coa]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_proc_ent(config_version,config_set_id,entity_id,entity_name,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state) SELECT config_version,config_set_id,entity_id,entity_name,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_proc_ent]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_proc_ent(config_version,config_set_id,entity_id,entity_name,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state) SELECT config_version,config_set_id,entity_id,entity_name,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_proc_ent]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_nt_fee(config_version,config_set_id,nt_fee_id,se_id,name,description,journal_entry_insert_fltr_id,config_state) SELECT config_version,config_set_id,nt_fee_id,se_id,name,description,journal_entry_insert_fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_nt_fee]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_nt_fee(config_version,config_set_id,nt_fee_id,se_id,name,description,journal_entry_insert_fltr_id,config_state) SELECT config_version,config_set_id,nt_fee_id,se_id,name,description,journal_entry_insert_fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_nt_fee]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spst_session(session_id,entity_id,datetime_started,file_name,config_version,completed) SELECT session_id,entity_id,datetime_started,file_name,config_version,completed FROM  [172.25.10.89].[postilion_office].[dbo].[spst_session]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spst_se_amount_pst_freq(config_version,config_set_id,amount_id,se_id,frequency,start_date,config_state) SELECT config_version,config_set_id,amount_id,se_id,frequency,start_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_se_amount_pst_freq]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spst_se_amount_pst_freq(config_version,config_set_id,amount_id,se_id,frequency,start_date,config_state) SELECT config_version,config_set_id,amount_id,se_id,frequency,start_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_se_amount_pst_freq]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_journal_fltr_param_w(config_set_id,fltr_param_id,fltr_grp_elem_id,fltr_param_value,config_state) SELECT config_set_id,fltr_param_id,fltr_grp_elem_id,fltr_param_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr_param_w] 
INSERT INTO sstl_journal_fltr_param_w(config_set_id,fltr_param_id,fltr_grp_elem_id,fltr_param_value,config_state) SELECT config_set_id,fltr_param_id,fltr_grp_elem_id,fltr_param_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr_param_w] 
INSERT INTO spay_se_amount_pay_freq(config_version,config_set_id,amount_id,se_id,frequency,start_date,config_state) SELECT config_version,config_set_id,amount_id,se_id,frequency,start_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_amount_pay_freq]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_se_amount_pay_freq(config_version,config_set_id,amount_id,se_id,frequency,start_date,config_state) SELECT config_version,config_set_id,amount_id,se_id,frequency,start_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_amount_pay_freq]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_nt_fee_acc_post(config_version,config_set_id,nt_fee_acc_post_id,nt_fee_id,coa_id,debit_acc_id,credit_acc_id,config_state) SELECT config_version,config_set_id,nt_fee_acc_post_id,nt_fee_id,coa_id,debit_acc_id,credit_acc_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_nt_fee_acc_post]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_nt_fee_acc_post(config_version,config_set_id,nt_fee_acc_post_id,nt_fee_id,coa_id,debit_acc_id,credit_acc_id,config_state) SELECT config_version,config_set_id,nt_fee_acc_post_id,nt_fee_id,coa_id,debit_acc_id,credit_acc_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_nt_fee_acc_post]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_prop(config_version,config_set_id,prop_id,prop,default_prop_value,config_state) SELECT config_version,config_set_id,prop_id,prop,default_prop_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_prop]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_prop(config_version,config_set_id,prop_id,prop,default_prop_value,config_state) SELECT config_version,config_set_id,prop_id,prop,default_prop_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_prop]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_tran_ident(config_version,config_set_id,tran_ident_id,description,se_id,config_state) SELECT config_version,config_set_id,tran_ident_id,description,se_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_tran_ident]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_tran_ident(config_version,config_set_id,tran_ident_id,description,se_id,config_state) SELECT config_version,config_set_id,tran_ident_id,description,se_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_tran_ident]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_amount_value_int(config_version,config_set_id,amount_value_int_id,amount_value_id,lower_bound,expr_amount,config_state) SELECT config_version,config_set_id,amount_value_int_id,amount_value_id,lower_bound,expr_amount,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_amount_value_int]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_amount_value_int(config_version,config_set_id,amount_value_int_id,amount_value_id,lower_bound,expr_amount,config_state) SELECT config_version,config_set_id,amount_value_int_id,amount_value_id,lower_bound,expr_amount,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_amount_value_int]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_amount(config_version,config_set_id,amount_id,se_id,name,description,config_state) SELECT config_version,config_set_id,amount_id,se_id,name,description,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_amount]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_amount(config_version,config_set_id,amount_id,se_id,name,description,config_state) SELECT config_version,config_set_id,amount_id,se_id,name,description,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_amount]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spst_proc_ent(config_version,config_set_id,entity_id,entity_name,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state) SELECT config_version,config_set_id,entity_id,entity_name,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_proc_ent]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spst_proc_ent(config_version,config_set_id,entity_id,entity_name,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state) SELECT config_version,config_set_id,entity_id,entity_name,plugin_id,plugin_user_param,plugin_output,residue_manager_id,residue_manager_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_proc_ent]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_fee_value(config_version,config_set_id,fee_value_id,se_id,description,fee_id,pred_id,min_value,max_value,cal_id,percentage,fixed_amount,fee_calc_strat_id,modified_fee_value_id,state,config_state) SELECT config_version,config_set_id,fee_value_id,se_id,description,fee_id,pred_id,min_value,max_value,cal_id,percentage,fixed_amount,fee_calc_strat_id,modified_fee_value_id,state,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_fee_value]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_fee_value(config_version,config_set_id,fee_value_id,se_id,description,fee_id,pred_id,min_value,max_value,cal_id,percentage,fixed_amount,fee_calc_strat_id,modified_fee_value_id,state,config_state) SELECT config_version,config_set_id,fee_value_id,se_id,description,fee_id,pred_id,min_value,max_value,cal_id,percentage,fixed_amount,fee_calc_strat_id,modified_fee_value_id,state,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_fee_value]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_fee(config_version,config_set_id,fee_id,se_id,name,description,type,amount_id,config_state) SELECT config_version,config_set_id,fee_id,se_id,name,description,type,amount_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_fee]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_fee(config_version,config_set_id,fee_id,se_id,name,description,type,amount_id,config_state) SELECT config_version,config_set_id,fee_id,se_id,name,description,type,amount_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_fee]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_amount_value(config_version,config_set_id,amount_value_id,se_id,amount_id,description,pred_id,tiered,expr_domain,modified_amount_value_id,state,config_state) SELECT config_version,config_set_id,amount_value_id,se_id,amount_id,description,pred_id,tiered,expr_domain,modified_amount_value_id,state,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_amount_value]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_amount_value(config_version,config_set_id,amount_value_id,se_id,amount_id,description,pred_id,tiered,expr_domain,modified_amount_value_id,state,config_state) SELECT config_version,config_set_id,amount_value_id,se_id,amount_id,description,pred_id,tiered,expr_domain,modified_amount_value_id,state,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_amount_value]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_cal(config_version,config_set_id,cal_id,se_id,name,description,priority,config_state) SELECT config_version,config_set_id,cal_id,se_id,name,description,priority,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_cal]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_cal(config_version,config_set_id,cal_id,se_id,name,description,priority,config_state) SELECT config_version,config_set_id,cal_id,se_id,name,description,priority,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_cal]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO ssdi_session(session_id,entity_id,datetime_creation,business_date,config_version,completed) SELECT session_id,entity_id,datetime_creation,business_date,config_version,completed FROM  [172.25.10.89].[postilion_office].[dbo].[ssdi_session]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_tran_ident_def(config_version,config_set_id,tran_ident_id,tran_ident_def_id,tran_field_id,field_value,config_state) SELECT config_version,config_set_id,tran_ident_id,tran_ident_def_id,tran_field_id,field_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_tran_ident_def]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_tran_ident_def(config_version,config_set_id,tran_ident_id,tran_ident_def_id,tran_field_id,field_value,config_state) SELECT config_version,config_set_id,tran_ident_id,tran_ident_def_id,tran_field_id,field_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_tran_ident_def]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_prop_value_node(config_version,config_set_id,node_id,parent_node_id,root_node_id,operator,inherited_prop_value_id,tran_field_id,field_operator,field_value,config_state) SELECT config_version,config_set_id,node_id,parent_node_id,root_node_id,operator,inherited_prop_value_id,tran_field_id,field_operator,field_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_prop_value_node]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_prop_value_node(config_version,config_set_id,node_id,parent_node_id,root_node_id,operator,inherited_prop_value_id,tran_field_id,field_operator,field_value,config_state) SELECT config_version,config_set_id,node_id,parent_node_id,root_node_id,operator,inherited_prop_value_id,tran_field_id,field_operator,field_value,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_prop_value_node]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_tran_field(config_version,config_set_id,tran_field_id,tran_field,expr_tran_field,data_type,config_state) SELECT config_version,config_set_id,tran_field_id,tran_field,expr_tran_field,data_type,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_tran_field]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_tran_field(config_version,config_set_id,tran_field_id,tran_field,expr_tran_field,data_type,config_state) SELECT config_version,config_set_id,tran_field_id,tran_field,expr_tran_field,data_type,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_tran_field]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_nt_fee_value(config_version,config_set_id,nt_fee_value_id,se_id,nt_fee_id,description,frequency,start_date,fixed_amount,nt_fee_calc_strat_id,config_state) SELECT config_version,config_set_id,nt_fee_value_id,se_id,nt_fee_id,description,frequency,start_date,fixed_amount,nt_fee_calc_strat_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_nt_fee_value]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_nt_fee_value(config_version,config_set_id,nt_fee_value_id,se_id,nt_fee_id,description,frequency,start_date,fixed_amount,nt_fee_calc_strat_id,config_state) SELECT config_version,config_set_id,nt_fee_value_id,se_id,nt_fee_id,description,frequency,start_date,fixed_amount,nt_fee_calc_strat_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_nt_fee_value]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_prop_value(config_version,config_set_id,prop_value_id,prop_id,prop_value,root_node_id,config_state) SELECT config_version,config_set_id,prop_value_id,prop_id,prop_value,root_node_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_prop_value]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_prop_value(config_version,config_set_id,prop_value_id,prop_id,prop_value,root_node_id,config_state) SELECT config_version,config_set_id,prop_value_id,prop_id,prop_value,root_node_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_prop_value]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_journal_fltr_grp(config_version,config_set_id,fltr_grp_id,description,config_state) SELECT config_version,config_set_id,fltr_grp_id,description,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr_grp]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_journal_fltr_grp(config_version,config_set_id,fltr_grp_id,description,config_state) SELECT config_version,config_set_id,fltr_grp_id,description,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr_grp]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_proc_ent(config_version,config_set_id,entity_id,entity_name,method_name,method_param,import_method_name,import_method_param,tran_set_name,tran_set_param,config_state) SELECT config_version,config_set_id,entity_id,entity_name,method_name,method_param,import_method_name,import_method_param,tran_set_name,tran_set_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_proc_ent]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_proc_ent(config_version,config_set_id,entity_id,entity_name,method_name,method_param,import_method_name,import_method_param,tran_set_name,tran_set_param,config_state) SELECT config_version,config_set_id,entity_id,entity_name,method_name,method_param,import_method_name,import_method_param,tran_set_name,tran_set_param,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_proc_ent]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_journal_fltr_grp_elem(config_version,config_set_id,fltr_grp_elem_id,fltr_grp_id,fltr_id,config_state) SELECT config_version,config_set_id,fltr_grp_elem_id,fltr_grp_id,fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr_grp_elem]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_journal_fltr_grp_elem(config_version,config_set_id,fltr_grp_elem_id,fltr_grp_id,fltr_id,config_state) SELECT config_version,config_set_id,fltr_grp_elem_id,fltr_grp_id,fltr_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_journal_fltr_grp_elem]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_se_acc_rel(config_version,config_set_id,acc_rel_id,se_id,gl_acc_nr_id,origin_acc_id,destination_acc_id,acc_rel_type_id,inverted,config_state) SELECT config_version,config_set_id,acc_rel_id,se_id,gl_acc_nr_id,origin_acc_id,destination_acc_id,acc_rel_type_id,inverted,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_acc_rel]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_se_acc_rel(config_version,config_set_id,acc_rel_id,se_id,gl_acc_nr_id,origin_acc_id,destination_acc_id,acc_rel_type_id,inverted,config_state) SELECT config_version,config_set_id,acc_rel_id,se_id,gl_acc_nr_id,origin_acc_id,destination_acc_id,acc_rel_type_id,inverted,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_acc_rel]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_se_acc(config_version,config_set_id,se_id,acc_id,bank_name,inst_code,branch_code,bank_routing_nr,account_name,account_nr,account_type,contact_id_bank,contact_id_accountholder,notes,config_state) SELECT config_version,config_set_id,se_id,acc_id,bank_name,inst_code,branch_code,bank_routing_nr,account_name,account_nr,account_type,contact_id_bank,contact_id_accountholder,notes,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_acc]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_se_acc(config_version,config_set_id,se_id,acc_id,bank_name,inst_code,branch_code,bank_routing_nr,account_name,account_nr,account_type,contact_id_bank,contact_id_accountholder,notes,config_state) SELECT config_version,config_set_id,se_id,acc_id,bank_name,inst_code,branch_code,bank_routing_nr,account_name,account_nr,account_type,contact_id_bank,contact_id_accountholder,notes,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_acc]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_acc(config_version,config_set_id,acc_id,coa_id,name,description,config_state) SELECT config_version,config_set_id,acc_id,coa_id,name,description,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_acc]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_acc(config_version,config_set_id,acc_id,coa_id,name,description,config_state) SELECT config_version,config_set_id,acc_id,coa_id,name,description,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_acc]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_se_acc_rel_param_w(acc_rel_param_id,config_set_id,acc_rel_id,param_value) SELECT acc_rel_param_id,config_set_id,acc_rel_id,param_value FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_acc_rel_param_w] 
INSERT INTO spay_se_acc_rel_param_w(acc_rel_param_id,config_set_id,acc_rel_id,param_value) SELECT acc_rel_param_id,config_set_id,acc_rel_id,param_value FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_acc_rel_param_w] 
INSERT INTO sstl_pred_prop_value(config_version,config_set_id,pred_id,prop_value_id,prop_id,exclude,config_state) SELECT config_version,config_set_id,pred_id,prop_value_id,prop_id,exclude,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_pred_prop_value]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_pred_prop_value(config_version,config_set_id,pred_id,prop_value_id,prop_id,exclude,config_state) SELECT config_version,config_set_id,pred_id,prop_value_id,prop_id,exclude,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_pred_prop_value]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_proc_ent_fltr_grp(config_version,config_set_id,entity_id,fltr_grp_id,config_state) SELECT config_version,config_set_id,entity_id,fltr_grp_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_proc_ent_fltr_grp]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_proc_ent_fltr_grp(config_version,config_set_id,entity_id,fltr_grp_id,config_state) SELECT config_version,config_set_id,entity_id,fltr_grp_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spay_proc_ent_fltr_grp]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_se_acc_rel_param(config_version,config_set_id,acc_rel_param_id,acc_rel_id,param_value) SELECT config_version,config_set_id,acc_rel_param_id,acc_rel_id,param_value FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_acc_rel_param]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_se_acc_rel_param(config_version,config_set_id,acc_rel_param_id,acc_rel_id,param_value) SELECT config_version,config_set_id,acc_rel_param_id,acc_rel_id,param_value FROM  [172.25.10.89].[postilion_office].[dbo].[spay_se_acc_rel_param]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO ssdi_proc_ent(config_version,config_set_id,entity_id,plugin_id,name,input,user_param_list,config_state) SELECT config_version,config_set_id,entity_id,plugin_id,name,input,user_param_list,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[ssdi_proc_ent]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO ssdi_proc_ent(config_version,config_set_id,entity_id,plugin_id,name,input,user_param_list,config_state) SELECT config_version,config_set_id,entity_id,plugin_id,name,input,user_param_list,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[ssdi_proc_ent]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_cal_date_range(config_version,config_set_id,date_range_id,cal_id,start_date,end_date,config_state) SELECT config_version,config_set_id,date_range_id,cal_id,start_date,end_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_cal_date_range]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_cal_date_range(config_version,config_set_id,date_range_id,cal_id,start_date,end_date,config_state) SELECT config_version,config_set_id,date_range_id,cal_id,start_date,end_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_cal_date_range]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spst_proc_ent_fltr_grp(config_version,config_set_id,entity_id,fltr_grp_id,config_state) SELECT config_version,config_set_id,entity_id,fltr_grp_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_proc_ent_fltr_grp]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spst_proc_ent_fltr_grp(config_version,config_set_id,entity_id,fltr_grp_id,config_state) SELECT config_version,config_set_id,entity_id,fltr_grp_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_proc_ent_fltr_grp]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spst_se_fee_pst_freq(config_version,config_set_id,fee_id,se_id,frequency,start_date,config_state) SELECT config_version,config_set_id,fee_id,se_id,frequency,start_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_se_fee_pst_freq]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spst_se_fee_pst_freq(config_version,config_set_id,fee_id,se_id,frequency,start_date,config_state) SELECT config_version,config_set_id,fee_id,se_id,frequency,start_date,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[spst_se_fee_pst_freq]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se(config_version,config_set_id,se_id,name,description,parent_id,coa_id,se_type_id,rel_type,config_state) SELECT config_version,config_set_id,se_id,name,description,parent_id,coa_id,se_type_id,rel_type,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se(config_version,config_set_id,se_id,name,description,parent_id,coa_id,se_type_id,rel_type,config_state) SELECT config_version,config_set_id,se_id,name,description,parent_id,coa_id,se_type_id,rel_type,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_acc_nr(config_version,config_set_id,acc_nr_id,se_id,acc_id,acc_nr,state,config_state) SELECT config_version,config_set_id,acc_nr_id,se_id,acc_id,acc_nr,state,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_acc_nr]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_acc_nr(config_version,config_set_id,acc_nr_id,se_id,acc_id,acc_nr,state,config_state) SELECT config_version,config_set_id,acc_nr_id,se_id,acc_id,acc_nr,state,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_acc_nr]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_third_party(config_version,config_set_id,se_id,third_party_se_id,pred_id,config_state) SELECT config_version,config_set_id,se_id,third_party_se_id,pred_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_third_party]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_third_party(config_version,config_set_id,se_id,third_party_se_id,pred_id,config_state) SELECT config_version,config_set_id,se_id,third_party_se_id,pred_id,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_third_party]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_rule_acc_post(config_version,config_set_id,acc_post_id,rule_id,amount_id,fee_id,coa_id,debit_acc_id,debit_cardholder_acc,credit_acc_id,credit_cardholder_acc,expr_granularity_element,expr_tag,config_state) SELECT config_version,config_set_id,acc_post_id,rule_id,amount_id,fee_id,coa_id,debit_acc_id,debit_cardholder_acc,credit_acc_id,credit_cardholder_acc,expr_granularity_element,expr_tag,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_rule_acc_post]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO sstl_se_rule_acc_post(config_version,config_set_id,acc_post_id,rule_id,amount_id,fee_id,coa_id,debit_acc_id,debit_cardholder_acc,credit_acc_id,credit_cardholder_acc,expr_granularity_element,expr_tag,config_state) SELECT config_version,config_set_id,acc_post_id,rule_id,amount_id,fee_id,coa_id,debit_acc_id,debit_cardholder_acc,credit_acc_id,credit_cardholder_acc,expr_granularity_element,expr_tag,config_state FROM  [172.25.10.89].[postilion_office].[dbo].[sstl_se_rule_acc_post]  WITH (NOLOCK) WHERE config_version IN (SELECT config_version FROM sstl_config_version WITH (NOLOCK))
INSERT INTO spay_unpaid_payments(unpaid_id,spay_session_id,journal_entry_id,adj_id,origin_account_id,destination_account_id,inverted,session_completed) SELECT unpaid_id,spay_session_id,journal_entry_id,adj_id,origin_account_id,destination_account_id,inverted,session_completed FROM  [172.25.10.89].[postilion_office].[dbo].[spay_unpaid_payments] 
INSERT INTO spay_bdate_fltr_ssn(bdate_id,spay_session_id,business_date) SELECT bdate_id,spay_session_id,business_date FROM  [172.25.10.89].[postilion_office].[dbo].[spay_bdate_fltr_ssn] 
INSERT INTO spst_bdate_fltr_ssn(bdate_id,spst_session_id,business_date) SELECT bdate_id,spst_session_id,business_date FROM  [172.25.10.89].[postilion_office].[dbo].[spst_bdate_fltr_ssn] 
