SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

DECLARE @minID BIGINT
DECLARE @maxID BIGINT
DECLARE @counter BIGINT 
select @minID =    min ([TransactionId]) from   [FundsTransferLog_part]  (nolock)
SELECT @counter =   MAX([TransactionId]) from   [FundsTransferLog]   (nolock)
WHILE (@counter>=@minID) BEGIN
IF NOT EXISTS (SELECT TransactionId FROM  [FundsTransferLog_part]  (nolock) WHERE [TransactionId] = @counter)BEGIN
--SET IDENTITY_INSERT [FundsTransferLog_part] ON
INSERT INTO [FundsTransferLog_part](
[TransactionId]
      ,[TransferCode]
      ,[InitiatingAccountNumber]
      ,[InitiatingAccountName]
      ,[InitiatingAccountType]
      ,[InitiatingChequeNumber]
      ,[InitiatingEntityId]
      ,[InitiatingEntityCode]
      ,[InitiatingEntityName]
      ,[InitiatingEntityLocationId]
      ,[InitiatingEntityLocationCode]
      ,[InitiatingEntityLocationFundsDirectCode]
      ,[InitiatingEntityLocationName]
      ,[InitiatingProcessorId]
      ,[InitiatingProcessorLastName]
      ,[InitiatingProcessorOthernames]
      ,[InitiatingProcessorUsername]
      ,[BeneficiaryName]
      ,[BeneficiaryPhone]
      ,[BeneficiaryEmail]
      ,[TerminatingDateTime]
      ,[TerminatingPaymentMethodId]
      ,[TerminatingPaymentMethod]
      ,[TerminatingChannelId]
      ,[TerminatingChannel]
      ,[TerminatingAmount]
      ,[TerminatingCurrencyCode]
      ,[TerminatingCurrencyName]
      ,[TerminatingAccountNumber]
      ,[TerminatingAccountType]
      ,[TerminatingAccountBankCBNCode]
      ,[TerminatingCountryCode]
      ,[TerminatingCountryName]
      ,[TerminatingEntityId]
      ,[TerminatingEntityCode]
      ,[TerminatingEntityName]
      ,[TerminatingEntityLocationId]
      ,[TerminatingEntityLocationCode]
      ,[TerminatingEntityLocationFundsDirectCode]
      ,[TerminatingEntityLocationName]
      ,[TerminatingEntityLocalAreaId]
      ,[TerminatingEntityLocalAreaName]
      ,[TerminatingEntityStateId]
      ,[TerminatingEntityStateName]
      ,[TerminatingBankId]
      ,[TerminatingBankCode]
      ,[TerminatingBankCBNCode]
      ,[TerminatingBankName]
      ,[IsComplete]
      ,[IsAuthorised]
      ,[AuthorisationLimit]
      ,[AuthorisingOfficerId]
      ,[AuthorisingOfficerLastname]
      ,[AuthorisingOfficerOthernames]
      ,[AuthorisingOfficerUsername]
      ,[IPAddress]
      ,[CashReceivableTypeId]
      ,[CashReceivableTypeName]
      ,[IsTransactionApproved]
      ,[SettleInQTFT]
      ,[TransferReason]
      ,[TerminatingTerminalId]
      ,[TerminatingStan]
)
SELECT [TransactionId]
      ,[TransferCode]
      ,[InitiatingAccountNumber]
      ,[InitiatingAccountName]
      ,[InitiatingAccountType]
      ,[InitiatingChequeNumber]
      ,[InitiatingEntityId]
      ,[InitiatingEntityCode]
      ,[InitiatingEntityName]
      ,[InitiatingEntityLocationId]
      ,[InitiatingEntityLocationCode]
      ,[InitiatingEntityLocationFundsDirectCode]
      ,[InitiatingEntityLocationName]
      ,[InitiatingProcessorId]
      ,[InitiatingProcessorLastName]
      ,[InitiatingProcessorOthernames]
      ,[InitiatingProcessorUsername]
      ,[BeneficiaryName]
      ,[BeneficiaryPhone]
      ,[BeneficiaryEmail]
      ,[TerminatingDateTime]
      ,[TerminatingPaymentMethodId]
      ,[TerminatingPaymentMethod]
      ,[TerminatingChannelId]
      ,[TerminatingChannel]
      ,[TerminatingAmount]
      ,[TerminatingCurrencyCode]
      ,[TerminatingCurrencyName]
      ,[TerminatingAccountNumber]
      ,[TerminatingAccountType]
      ,[TerminatingAccountBankCBNCode]
      ,[TerminatingCountryCode]
      ,[TerminatingCountryName]
      ,[TerminatingEntityId]
      ,[TerminatingEntityCode]
      ,[TerminatingEntityName]
      ,[TerminatingEntityLocationId]
      ,[TerminatingEntityLocationCode]
      ,[TerminatingEntityLocationFundsDirectCode]
      ,[TerminatingEntityLocationName]
      ,[TerminatingEntityLocalAreaId]
      ,[TerminatingEntityLocalAreaName]
      ,[TerminatingEntityStateId]
      ,[TerminatingEntityStateName]
      ,[TerminatingBankId]
      ,[TerminatingBankCode]
      ,[TerminatingBankCBNCode]
      ,[TerminatingBankName]
      ,[IsComplete]
      ,[IsAuthorised]
      ,[AuthorisationLimit]
      ,[AuthorisingOfficerId]
      ,[AuthorisingOfficerLastname]
      ,[AuthorisingOfficerOthernames]
      ,[AuthorisingOfficerUsername]
      ,[IPAddress]
      ,[CashReceivableTypeId]
      ,[CashReceivableTypeName]
      ,[IsTransactionApproved]
      ,[SettleInQTFT]
      ,[TransferReason]
      ,[TerminatingTerminalId]
      ,[TerminatingStan]
  FROM [quickteller].[dbo].[FundsTransferLog] (NOLOCK)
   WHERE TransactionId   =@counter
  PRINT   'TransactionId value: '+convert(VARCHAR(40),@counter)
END
SET @counter=@counter-1;
END 

--SP_HELP FundsTransferLog

--alter table FundsTransferLog_part nocheck constraint FK_FundsTransferLog_PartTransactions