
create PROCEDURE creation_of_new_bank_entity ( @new_bank_name VARCHAR(MAX))
 as
 BEGIN
 SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
 
 DECLARE @max_id INT

SELECT @max_id = MAX(entity_id) FROM reports_entity (NOLOCK);

		CREATE TABLE #temp_report_results (

		entity_id  INT,
		name VARCHAR(1000),
		plugin_id VARCHAR(1000),
		user_param_list  VARCHAR(MAX),
		template  VARCHAR(MAX),
		destination  VARCHAR(MAX),
		output_format  VARCHAR(MAX),
		output_params  VARCHAR(MAX),
		report_params VARCHAR(MAX),
		crystal_version  VARCHAR(1000),
		retention_period VARCHAR(1000),
		dsn_list VARCHAR(1000)

		)

INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+1,'ATMC_detail_'+@new_bank_name,'Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - ATMC Daily Report.rpt',0,12,'~H:\BANK REPORTS\ATMC\Not_On_Us\'+@new_bank_name+'_BO6_ATMC Daily Reportpdf.pdf~3~1~','~NULL~NULL~SWTATMCsrc,SWTATMC2src~'+@new_bank_name+'~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+2,@new_bank_name+'_PrepaidCardLoad','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Prepaid Card Load.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\CashCard\'+@new_bank_name+'_B04 - PrepaidCard Load_standard_Report.pdf~1~1~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk~NULL~NULL,NULL,NULL~false~NULL~NULL~'+@new_bank_name+','+@new_bank_name+'Group,'+@new_bank_name+'CCGroup~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+3,@new_bank_name+'_GPR_DISK','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Recharge Transaction Detail.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Recharge\'+@new_bank_name+'_B04 - Recharge Transaction standard(FAILED AND REVERSED TXNS ONLY).pdf~1~1~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'CCsnk~GPRsrc,VTUsrc,VTUSTOCKsrc~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+4,@new_bank_name+'_Remote_On_Us_disk','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Remote On Us Detail.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Remote_On_Us\'+@new_bank_name+'_B04 - Remote On Us Standard.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'CCsnk~SWT'+@new_bank_name+'src~NULL~NULL~NULL~NULL~NULL,NULL,NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+5,@new_bank_name+'_Not_On_Us_disk','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - Not On Us Detail.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Not_On_Us\BO6_Not On Us Detail.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'src~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+6,@new_bank_name+'_Mobility','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - Participating Interbank Transfer (Channels).rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Mobility\'+@new_bank_name+'_BO6_Participating Interbank Transfer (Channels)_Standard.pdf~1~1~','~NULL~NULL~SWTMOBILEsrc~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk,'+@new_bank_name+'~NULL,NULL,NULL,NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+7,@new_bank_name+'_WebPay_Acquired_disk','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 -Web_ Acquirer Detail_standardize.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Web_Acquired\'+@new_bank_name+'_B04 -Web_ Acquirer detail_Report.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk~NULL~SWTASPWEBsrc,SWTASPUBAsrc,SWTASPIPDsrc,SWTWEBFEEsrc~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+8,@new_bank_name+'_Payment_Gateway','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - Interbank Transfer (platforms).rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Payment_Gateway\'+@new_bank_name+'_BO6_Interbank Transfer (Platforms)_Standard.pdf~3~1~','~NULL~NULL~SWTASPIPDsrc,SWT'+@new_bank_name+'src~3IGW0001,3ADPS001,3CCW0001,3IBH0003,3NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+9,@new_bank_name+'_POS_acquired_disk','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\POS_Acquired\'+@new_bank_name+'_B04 -Pos Acquirer detail Report.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk~NULL~SWTASPKIMsrc,SWTASPPOSsrc,SWTNCSKI2src,SWTFBPsrc,SWTUBAsrc,SWTFCMBsrc,SWTNCS2src,SWTSHOPRTsrc,SWTASGTVLsrc,SWTNCSKIMsrc,SWTEASYFLsrc,SWTASPKSKsrc,SWT'+@new_bank_name+'src,SWTZIBsrc,SWTASPZIBsrc,SWTFUELsrc,SWTTRAVELsrc,SWTTELCOs~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+10,@new_bank_name+'_Not_On_Us_Terminal','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - Not On Us Detail_Terminal.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\'+@new_bank_name+'_BO6_Not On Us Detail_Terminal.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'src~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+11,@new_bank_name+'_AutoPay','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - AutoPay Detail.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\AutoPay\'+@new_bank_name+'_BO6_AutoPay standard_Report.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'src~3IAP0001~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+12,@new_bank_name+'_NotOnUs_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - Not On Us Detail_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\Not_On_Us\'+@new_bank_name+'_BO6_Not On Us Detail.csv~3~~~','~NULL~NULL~SWT'+@new_bank_name+'src~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+13,@new_bank_name+'_Remote_WEB_disk','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Web_Remote_ Detail.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Remote_WEB\'+@new_bank_name+'_B04 - Remote_Web standard_Report.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'CCsnk~SWTASPWEBsrc,SWTASPUBAsrc,SWTASPIPDsrc,SWTWEBFEEsrc~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+14,@new_bank_name+'_Remote_POS_disk','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - POS Detail.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Remote_Pos\'+@new_bank_name+'_B04 -Remote_POS standard.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'CCsnk~SWTASPKIMsrc,SWTASPPOSsrc,SWTNCSKI2src,SWTFBPsrc,SWTUBAsrc,SWTFCMBsrc,SWTNCS2src,SWTSHOPRTsrc,SWTASGTVLsrc,SWTNCSKIMsrc,SWTEASYFLsrc,SWTASPKSKsrc,SWT'+@new_bank_name+'src,SWTZIBsrc,SWTASPZIBsrc,SWTFUELsrc,SWTTRAVELsrc,SWTT~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+15,@new_bank_name+'_POSRemote_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - POS Detail_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\Remote_Pos\'+@new_bank_name+'_B04 -Remote_POS standard.csv~3~~~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'CCsnk~SWTASPKIMsrc,SWTASPPOSsrc,SWTNCSKI2src,SWTFBPsrc,SWTUBAsrc,SWTFCMBsrc,SWTNCS2src,SWTSHOPRTsrc,SWTASGTVLsrc,SWTNCSKIMsrc,SWTEASYFLsrc,SWTASPKSKsrc,SWT'+@new_bank_name+'src,SWTZIBsrc,SWTASPZIBsrc,SWTFUELsrc,SWTTRAVELsrc,SWTT~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+16,@new_bank_name+'_POSAcquired_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\POS_Acquired\'+@new_bank_name+'_B04 -Pos Acquirer detailReport.csv~3~~~','~NULL~NULL~SWT'+@new_bank_name+'snk~NULL~SWTASPKIMsrc,SWTASPPOSsrc,SWTNCSKI2src,SWTFBPsrc,SWTUBAsrc,SWTFCMBsrc,SWTNCS2src,SWTSHOPRTsrc,SWTASGTVLsrc,SWTNCSKIMsrc,SWTEASYFLsrc,SWTASPKSKsrc,SWT'+@new_bank_name+'src,SWTZIBsrc,SWTASPZIBsrc,SWTFUELsrc,SWTTRAVELsrc,SWTTELCOs~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+17,@new_bank_name+'_Remote_Glo_disk','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - Globacom Transaction Detail.rpt',0,12,'~H:\BANK REPORTS\FBP\Glo\_BO6_Globacom Transaction Detail.pdf~3~1~','~NULL~NULL~SWTASPWEBsrc,SWTASPUBAsrc~4GLO0001~SWT'+@new_bank_name+'snk~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+18,@new_bank_name+'_RemoteOnUs_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Remote On Us Detail_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\Remote_On_Us\'+@new_bank_name+'_B04 - Remote On Us Standard.csv~3~~~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'CCsnk~SWT'+@new_bank_name+'src~NULL~NULL~NULL~NULL~NULL,NULL,NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+19,@new_bank_name+'_Mobility_Acqiured','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - Acquired Interbank Transfer (Channels).rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Mobility\'+@new_bank_name+'_BO6_Acquired Interbank Transfer (Channels)_Standard.pdf~3~1~','~NULL~NULL~SWTMOBILEsrc,SWT'+@new_bank_name+'src,SWTASPPOSsrc~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk,'+@new_bank_name+'~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+20,@new_bank_name+'_Billpayment_issuer','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Bill Payment Issuer Detail.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\BillPayment\'+@new_bank_name+'_B04 - Bill Payment Issuer Standard.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+21,@new_bank_name+'_Billpayment_Acquired','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Bill Payment Acquirer Detail.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\BillPayment\'+@new_bank_name+'_B04 - Bill Payment Acquirer Detail.pdf~3~1~','~NULL~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+22,@new_bank_name+'_Autopay_Summary','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - AutoPay Detail.rpt',0,12,'~H:\BANK REPORTS\SWT\Summary_Reports\Autopay\'+@new_bank_name+'_BO6_AutoPay Standard.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'src~3IAP0001~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+23,@new_bank_name+'_PrepaidCardLoad_Summary','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Prepaid Card Load.rpt',0,12,'~H:\BANK REPORTS\SWT\Summary_Reports\Prepaid CardLoad\'+@new_bank_name+'_B04 - PrepaidCard Load_Standard.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk~NULL~NULL,NULL,NULL~false~NULL~NULL~'+@new_bank_name+','+@new_bank_name+'Group,'+@new_bank_name+'CCGroup~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+24,@new_bank_name+'_GPR_DISK_Summary','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Recharge Transaction Detail.rpt',0,12,'~H:\BANK REPORTS\SWT\Summary_Reports\Recharge\'+@new_bank_name+'_B04 - Recharge Transaction standard(FAILED AND REVERSED TXNS ONLY)_Report.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'CCsnk~GPRsrc,VTUsrc,VTUSTOCKsrc~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+25,@new_bank_name+'_Autopay_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - AutoPay Detail_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\AutoPay\'+@new_bank_name+'_BO6_AutoPay standard_Report.csv~3~,~"~','~NULL~NULL~SWT'+@new_bank_name+'src~3IAP0001~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+26,@new_bank_name+'_WebAcquired_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 -Web_Acquirer Detail_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\Web_Acquired\'+@new_bank_name+'_B04 -Web_ Acquirer detail_Report.csv~3~ ~~','~NULL~NULL~SWT'+@new_bank_name+'snk~NULL~SWTASPWEBsrc,SWTASPUBAsrc,SWTASPIPDsrc,SWTWEBFEEsrc~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+27,@new_bank_name+'_Remote_Web_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Web_Remote_ Detail_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\Remote_WEB\BO4_Web Remote_standard_Report.csv~3~,~"~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'CCsnk~SWTASPWEBsrc,SWTASPUBAsrc,SWTASPIPDsrc,SWTWEBFEEsrc~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+28,@new_bank_name+'_GPR_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Recharge Transaction Detail_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\Recharge\B04 - Recharge Transaction standard(FAILED AND REVERSED TXNS ONLY)_Report.csv~3~,~"~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'CCsnk~GPRsrc,VTUsrc,VTUSTOCKsrc~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+29,@new_bank_name+'_PrepaidCardLoad_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Prepaid Card Load_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\CashCard\B04 - PrepaidCard Load_standard_Report.csv~3~,~"~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk~NULL~NULL,NULL,NULL~false~NULL~NULL~'+@new_bank_name+'~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+30,'ATMC_detail_'+@new_bank_name+'_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - ATMC Daily Report.rpt',0,9,'~H:\BANK REPORTS\ATMC\Not_On_Us\'+@new_bank_name+'_BO6_ATMC Daily Report.csv~3~,~"~','~NULL~NULL~SWTATMCsrc,SWTATMC2src~'+@new_bank_name+'~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+31,@new_bank_name+'_BillPayment_issuer_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Bill Payment Issuer Detail_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\BillPayment\'+@new_bank_name+'_B04 - Bill Payment Issuer Standard.csv~3~,~"~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk~NULL~NULL~NULL~NULL~',90,NULL,NULL)
--INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+32,@new_bank_name+'_GPR_CSV','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Recharge Transaction Detail_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\Recharge\'+@new_bank_name+'_B04 - RechargeTransaction standard(FAILED AND REVERSED TXNS ONLY)_Report_csv~3~~~','~NULL~NULL~SWT'+@new_bank_name+'Snk,SWT'+@new_bank_name+'CCsnk~GPRsrc,VTUsrc,VTUSTOCKsrc~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+33,@new_bank_name+'_Billpayment_Acquirer_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 - Bill Payment Acquirer Detail_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\BillPayment\'+@new_bank_name+'_B04 - Bill Payment Acquirer Detail.csv~3~,~"~','~NULL~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+34,@new_bank_name+'_Mobility_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 -  Participating Interbank Transfer (Channels)_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\Mobility\B06 -  Participating Interbank Transfer (Channels).csv~3~,~"~','~NULL~NULL~SWT'+@new_bank_name+'src~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk,'+@new_bank_name+'~NULL,NULL,NULL,NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+35,@new_bank_name+'_Payment_Gateway_Summary','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - Interbank Transfer (platforms).rpt',0,12,'~H:\BANK REPORTS\SWT\Summary_Reports\Payment Gateway\'+@new_bank_name+'_BO6_Interbank Transfer (Platforms)_Standard.pdf~3~1~','~NULL~NULL~SWTASPIPDsrc,SWT'+@new_bank_name+'src~3IGW0001,3ADPS001,3CCW0001,3IBH0003,3NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk~NULL,NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+36,@new_bank_name+'_Mobility_Acquired_Summary','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - Acquired Interbank Transfer (Channels).rpt',0,12,'~H:\BANK REPORTS\SWT\Summary_Reports\Mobility\'+@new_bank_name+'_BO6_Acquired Interbank Transfer (Channels)_Standard.pdf~3~1~','~NULL~NULL~SWTMOBILEsrc,SWT'+@new_bank_name+'src,SWTASPPOSsrc~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk,'+@new_bank_name+'~NULL,NULL,NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+37,@new_bank_name+'_Mobility_Summary','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - Participating Interbank Transfer (Channels).rpt',0,12,'~H:\BANK REPORTS\SWT\Summary_Reports\Mobility\'+@new_bank_name+'_BO6_Participating Interbank Transfer (Channels)_Standard.pdf~3~1~','~NULL~NULL~SWTMOBILEsrc~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk,'+@new_bank_name+'~NULL,NULL,NULL,NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+38,@new_bank_name+'_COMPUTATION','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\Settlement_Computation.rpt',0,10,'~H:\BANK REPORTS\'+@new_bank_name+'\NIBSS\Daily_Computation_'+@new_bank_name+'.xls~3~','~NULL~NULL~~'+@new_bank_name+'~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+39,'FLP_POS_Acquired_'+@new_bank_name,'Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail_csv.rpt',0,9,'~H:\BANK REPORTS\MERCHANTS\FOREVER\POS_Acquired\FLP_B04 -Pos Acquirer detailReport_'+@new_bank_name+'.csv~3~~~','~NULL~NULL~SWT'+@new_bank_name+'snk~NULL~SWTASPKIMsrc,SWTASPPOSsrc,SWTNCSKI2src,SWTFBPsrc,SWTUBAsrc,SWTFCMBsrc,SWTNCS2src,SWTSHOPRTsrc,SWTASGTVLsrc,SWTNCSKIMsrc,SWTEASYFLsrc,SWTASPKSKsrc,SWT'+@new_bank_name+'src,SWTZIBsrc,SWTASPZIBsrc,SWTFUELsrc,SWTTRAVELsrc,SWTTELCOs',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+40,@new_bank_name+'_MCard_Local_Processing','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B05 - Mastercard Processing.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Mastercard\'+@new_bank_name+'_B05 - Mastercard Local Processing.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk~NULL~NULL~NULL~Last business day~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+41,'EMTS_'+@new_bank_name,'Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail.rpt',0,12,'~H:\BANK REPORTS\MERCHANTS\EMTS\Web_Acquired\EMTS_'+@new_bank_name+'_B04 -Web_Acquirer detail_ReportReportpdf.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk~NULL~SWTASPWEBsrc,SWTASPUBAsrc,SWTASPPOSsrc,SWTNCSKI2src,SWTFBPsrc,SWTUBAsrc,SWTFCMBsrc,SWTNCS2src,SWTSHOPRTsrc,SWTASGTVLsrc,SWTNCSKIMsrc,SWTEASYFLsrc,SWTASPKSKsrc,SWT'+@new_bank_name+'src,SWTZIBsrc,SWTASPZIBsrc,SWTASPIPDsrc,SWTWEBFEEsrc,SWT'+@new_bank_name+'s',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+42,'EMTS_'+@new_bank_name+'_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail_csv.rpt',0,9,'~H:\BANK REPORTS\MERCHANTS\EMTS\Web_Acquired\EMTS_'+@new_bank_name+'_B04 -Web_Acquirer detail_ReportReport.csv~3~,~"~','~NULL~NULL~SWT'+@new_bank_name+'snk~NULL~SWTASPWEBsrc,SWTASPUBAsrc,SWTASPPOSsrc,SWTNCSKI2src,SWTFBPsrc,SWTUBAsrc,SWTFCMBsrc,SWTNCS2src,SWTSHOPRTsrc,SWTASGTVLsrc,SWTNCSKIMsrc,SWTEASYFLsrc,SWTASPKSKsrc,SWT'+@new_bank_name+'src,SWTZIBsrc,SWTASPZIBsrc,SWTASPIPDsrc,SWTWEBFEEsrc,SWT'+@new_bank_name+'s',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+43,@new_bank_name+'_Payment_Gateway_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - Interbank Transfer (platforms)_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\Payment_Gateway\'+@new_bank_name+'_B06 - Interbank Transfer (Platforms)_Standard.csv~3~~~','~NULL~NULL~SWTASPIPDsrc,SWT'+@new_bank_name+'src~3IGW0001,3ADPS001,3CCW0001,3IBH0003,3NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+44,@new_bank_name+'_NIBSS_Returns','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\NIBSS_Returns.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\NIBSS\'+@new_bank_name+'_NIBSS_Returns.csv~3~,~"~','~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+45,@new_bank_name+'_POS_Verve_Billing','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\Verve Billing Member Report.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Verve_Billing\'+@new_bank_name+'_POS_Verve Billing Member Report.pdf~3~1~','~NULL~NULL~NULL,NULL,NULL~'+@new_bank_name+'GROUP,'+@new_bank_name+'CCGROUP~POS MERCHANT PURCHASE~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+46,@new_bank_name+'_NIBSS_Paid','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\NIBSS_Paid.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\NIBSS\'+@new_bank_name+'_NIBSS_Paid.csv~1~,~"~','~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+47,@new_bank_name+'_Mobility_Acquired_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B06 - Acquired Interbank Transfer (Channels)_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\Mobility\'+@new_bank_name+'_B06 - Acquired Interbank Transfer (Channels).csv~3~,~"~','~NULL~NULL~SWTMOBILEsrc,SWT'+@new_bank_name+'src,SWTASPPOSsrc~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'snk,'+@new_bank_name+'~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+48,@new_bank_name+'_Settlement_Net','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\Settlement Bank Net.rpt',0,10,'~H:\BANK REPORTS\'+@new_bank_name+'\NIBSS\'+@new_bank_name+'_Settlement Bank Net.xls~3~','~NULL~NULL~~'+@new_bank_name+'~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+49,@new_bank_name+'_MCard_Local_Processing_Sum','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B05 - Mastercard Processing.rpt',0,12,'~H:\BANK REPORTS\SWT\Mastercard_Summary\'+@new_bank_name+'_B05 - Mastercard Local Processing.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk~NULL~NULL~NULL~Last Business Day~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+50,@new_bank_name+'_Pos_Acqd_Monthly','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail_csv_Monthly.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\POS_acquired\'+@new_bank_name+'_B04 -Pos Acquirer Monthly.csv~3~~~','~NULL~NULL~SWT'+@new_bank_name+'snk~NULL~SWTASPKIMsrc,SWTASPPOSsrc,SWTNCSKI2src,SWTFBPsrc,SWTUBAsrc,SWTFCMBsrc,SWTNCS2src,SWTSHOPRTsrc,SWTASGTVLsrc,SWTNCSKIMsrc,SWTEASYFLsrc,SWTASPKSKsrc,SWT'+@new_bank_name+'src,SWTZIBsrc,SWTASPZIBsrc,SWTFUELsrc,SWTTRAVELsrc,SWTTELCOs',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+51,@new_bank_name+'_CUP_Pos_Acquired_disk','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 -Web_Pos Acquirer Detail_CUP.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\POS_acquired\'+@new_bank_name+'_B04 -CUP_Pos Acquirer detail.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk~NULL~SWTNCS2src,SWTSHOPRTsrc,SWTASGTVLsrc,SWTNCSKIMsrc~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+52,@new_bank_name+'_Pos_BiWeekly','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 -transaction_original_switchofficeFBN_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\POS_acquired\'+@new_bank_name+'_B04 -Pos Acquirer BiWeekly_Nov.csv~3~~~','~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+53,@new_bank_name+'_POS_Acquired_ALL','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B04 -Pos Acquirer Detail_ALL_TRXN_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\POS_Acquired\B04 -Pos Acquirer Detail_ALL_TRXN.csv~3~,~"~','~NULL~NULL~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+54,@new_bank_name+'_Terminal_Owner_Backlog','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\terminal_owner_periodic_backlog.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\POS_ACQUIRED\'+@new_bank_name+'_Terminal_Owner_fee_Weekly_backlog.csv~3~,~"~','~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+55,@new_bank_name+'_NIBSS_Returns_backup','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\NIBSS_Returns_backup.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\NIBSS\'+@new_bank_name+'_NIBSS_Returns_backup.csv~3~,~"~','~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+56,@new_bank_name+'_Web_Verve_Billing','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\Verve Billing Member Report.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Verve_Billing\'+@new_bank_name+'_WEB_Verve Billing Member Report.pdf~3~1~','~NULL~NULL~NULL,NULL,NULL~'+@new_bank_name+'GROUP,'+@new_bank_name+'CCGROUP~WEB MERCHANT PURCHASE~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+57,@new_bank_name+'_Recharge_Verve_Billing','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\Verve Billing Member Report.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Verve_Billing\'+@new_bank_name+'_Recharge_Verve Billing Member Report.pdf~3~1~','~NULL~NULL~NULL,NULL,NULL~'+@new_bank_name+'GROUP,'+@new_bank_name+'CCGROUP~Recharge Purchase~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+58,'B19_Response_code_analysis_'+@new_bank_name,'Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\B19 - Response Codes Analysis_periodic.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Response_Code_Analysis\B19 - '+@new_bank_name+' Response Codes Analysis SWT.pdf~1~1~','~NULL~NULL~SWT'+@new_bank_name+'snk~daily~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+59,@new_bank_name+'_Billpmt_Verve_Billing','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\Verve Billing Member Report.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Verve_Billing\'+@new_bank_name+'_Billpayment_Verve Billing Member Report.pdf~3~1~','~NULL~NULL~NULL,NULL,NULL~'+@new_bank_name+'GROUP,'+@new_bank_name+'CCGROUP~BillPayment~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+60,@new_bank_name+'_Transfers_VBilling','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\Verve Billing Member Report_Transfers.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Verve_Billing\'+@new_bank_name+'_Transfers_Verve Billing Member Report.pdf~3~1~','~NULL~NULL~NULL,NULL,NULL~'+@new_bank_name+'GROUP,'+@new_bank_name+'CCGROUP~Transfers~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+61,@new_bank_name+'_Verve_International','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\verve_int\B04 - Remote On Us Detail_Verve_Int.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Remote_On_Us\'+@new_bank_name+'- Remote On Us Summary_ATM_Verve_Int.pdf~3~1~','~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'CCsnk~NULL~SWT'+@new_bank_name+'src~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+62,@new_bank_name+'_NIBSS_Paid_via_Acquirer','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\NIBSS_Paid_Via_Acquirer.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\NIBSS\'+@new_bank_name+'_NIBSS_Paid_Via_Acquirers CBN Account.csv~3~,~"~','~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+63,@new_bank_name+'_Remote_On_Us_Discover','Crystal',NULL,'C:\Postilion\Office\base\reports\Balancing\B04 - Remote On Us_Discover Detail.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'\Remote_On_Us\'+@new_bank_name+'_B04 - Remote On Us_Discover Detail.pdf~3~1~','~NULL~NULL~NULL~NULL~NULL~NULL~'+@new_bank_name+'~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+64,@new_bank_name+'_ATMLateReversals_Remote','Crystal',NULL,'C:\Postilion\Office\base\reports\Balancing\ATM_Late_Reversal_Details_Remote.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\NIBSS\'+@new_bank_name+'_ATMLateReversals_Remote.csv~3~~~','~NULL~NULL~NULL~NULL~'+@new_bank_name+'Group~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+65,@new_bank_name+'_ATMLateReversals_Acquirer','Crystal',NULL,'C:\Postilion\Office\base\reports\Balancing\ATM_Late_Reversal_Details_Acquirer.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\NIBSS\'+@new_bank_name+'_ATMLateReversals_Acquirer.csv~1~~~','~NULL~NULL~NULL~NULL~SWT'+@new_bank_name+'src~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+66,@new_bank_name+'_COMPREHENSIVE_COMPUTATION','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\Computation\Comprehensive_Computation_FBN.rpt',0,10,'~H:\BANK REPORTS\'+@new_bank_name+'\NIBSS\Daily_Comprehensive_Computation_'+@new_bank_name+'.xls~3~','~NULL~'+@new_bank_name+'~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+67,@new_bank_name+'_POSLateReversals_Acquirer','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\Late POS Reversal_Acquirer_Detail.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\NIBSS\'+@new_bank_name+'_POSLateReversals_Acquirer.csv~1~~~','~NULL~NULL~NULL~NULL~NULL~NULL~NULL~NULL~NULL~NULL~NULL~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+68,@new_bank_name+'_POSLateReversals_Remote','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\Late POS Reversal_Remote_Detail.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\NIBSS\'+@new_bank_name+'_POSLateReversals_Remote.csv~3~~~','~NULL~NULL~NULL~NULL~NULL~NULL~NULL~NULL~'+@new_bank_name+'~',90,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+69,'Verve_Intl_Acquirer_'+@new_bank_name+'GHANA','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\verve_int\B06 - Not On Us Detail_Verve_Int_Acquirer.rpt',0,12,'~H:\BANK REPORTS\'+@new_bank_name+'GH\Verve_International\'+@new_bank_name+'GH_B06 - Not On Us Detail_Verve_Int_Acquirer_2015_0921.pdf~3~1~','~NULL~NULL~SWTMEGAsrc~NULL~NULL~NULL~',115,NULL,NULL)
INSERT INTO  #temp_report_results (entity_id,name,plugin_id,user_param_list,template,destination,output_format,output_params,report_params,crystal_version,retention_period,dsn_list) VALUES (@max_id+70,@new_bank_name+'_Verve_International_csv','Crystal',NULL,'C:\postilion\Office\base\reports\Balancing\verve_int\B04 - Remote On Us Detail_Verve Intl_csv.rpt',0,9,'~H:\BANK REPORTS\'+@new_bank_name+'\Remote_On_Us\'+@new_bank_name+'_Verve International_Remote On Us Report.csv~3~~~','~NULL~NULL~SWTMEGAsrc~NULL~NULL~SWT'+@new_bank_name+'snk,SWT'+@new_bank_name+'CCsnk~',90,NULL,NULL)

--select  name,COUNT(NAME) from  #temp_report_results  GROUP BY name HAVING COUNT(NAME) > 1 
IF EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME ='reports_entity' AND COLUMN_NAME ='template_id')  
BEGIN
insert into[postilion_office].[dbo].[reports_entity]
	  ([entity_id]
		  ,[name]
		  ,[plugin_id]
		  ,[user_param_list]
		  ,[template_id])
	SELECT  distinct [entity_id]
		  ,[name]
		  ,[plugin_id]
		  ,[user_param_list]
		  ,NULL
	  FROM #temp_report_results
	  INSERT INTO [postilion_office].[dbo].[reports_crystal](
	  
	  [entity]
      ,[template]
      ,[destination]
      ,[output_format]
      ,[output_params]
      ,[report_params]
      ,[crystal_version]
      ,[retention_period]
      ,[dsn_list]
      ,[visible_in_portal]
      )
	  SELECT  [entity_id]
      ,[template]
      ,[destination]
      ,[output_format]
      ,[output_params]
      ,[report_params]
      ,[crystal_version]
      ,[retention_period]
      ,[dsn_list]
      ,1
  FROM  #temp_report_results
  
  END
  ELSE BEGIN
  
	  insert into[postilion_office].[dbo].[reports_entity]
	  ([entity_id]
		  ,[name]
		  ,[plugin_id]
		  ,[user_param_list]
		 )
	SELECT [entity_id]
		  ,[name]
		  ,[plugin_id]
		  ,[user_param_list]
	  FROM #temp_report_results
	  
	   INSERT INTO [postilion_office].[dbo].[reports_crystal](
	  
	  [entity]
      ,[template]
      ,[destination]
      ,[output_format]
      ,[output_params]
      ,[report_params]
      ,[crystal_version]
      ,[retention_period]
      ,[dsn_list]
      )
	  SELECT  [entity_id]
      ,[template]
      ,[destination]
      ,[output_format]
      ,[output_params]
      ,[report_params]
      ,[crystal_version]
      ,[retention_period]
      ,[dsn_list]
  FROM  #temp_report_results
  
  END
  
  END