ALTER DATABASE projectx SET ALLOW_SNAPSHOT_ISOLATION ON GO

ALTER DATABASE projectx SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 5 DAYS, AUTO_CLEANUP = ON)

ALTER TABLE projectx.dbo.billers ENABLE CHANGE_TRACKING