SELECT CASE

 WHEN totals_group.Value = 'EBNeACCGroup' THEN 'Verve eAccount'
 WHEN LEFT(pan ,6) = '589019' THEN 'First Bank of Nigeria (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '627480'	THEN	'United Bank for Africa (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '627629'   THEN 'Zenith International Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '627752'   THEN 'United Bank for Africa (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '627787'   THEN 'Guaranty Trust Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '627805'   THEN 'Skye Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '627975'   THEN 'Skye Bank (Magstripe Credit Card)'
 WHEN LEFT(pan ,6) = '628027'	THEN	'Skye Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '603948'   THEN 'Oceanic Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '627821'   THEN 'WEMA Bank Plc (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '628016'   THEN 'WEMA Bank Plc (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '627819'	THEN	'Main Street Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '627858'	THEN	'Stanbic IBTC Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '627955'	THEN	'Keystone Bank(Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '628009'   THEN 'First City Monument Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '628027'   THEN 'EIB International Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '639138'   THEN 'Fidelity Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '639276'   THEN 'Fidelity Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '636088'   THEN 'Intercontinental Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '602980'   THEN 'Union Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '627681'   THEN 'Union Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '627168'   THEN 'Diamond Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '639203'   THEN 'First Inland Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '639249'   THEN 'Equitorial Trust Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '639139'   THEN 'Access Bank Plc (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '636092'   THEN 'Sterling Bank Plc (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '903708'   THEN 'EcoBank Nigeria (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '639609'   THEN 'Unity Bank Plc (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '639563'   THEN 'Enterprise Bank (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '606079'   THEN 'Aso Savings (Magstripe Debit Card)'
 WHEN LEFT(pan ,6) = '639587'   THEN '3LINE (Debit Card)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='UBA'	THEN	'United Bank for Africa (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='ZIB'	THEN	'Zenith International Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='PRU'	THEN	'Skye Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='PLAT'	THEN	'PlatinumHabib Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='CHB'	THEN	'Stanbic IBTC Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='GTB'	THEN	'Guaranty Trust Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='UBA'	THEN	'United Bank for Africa (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='FBN'	THEN	'First Bank of Nigeria (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='OBI'	THEN	'Oceanic Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='WEM'	THEN	'WEMA Bank Plc (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='AFRI'	THEN	'Main Street Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='ETB'	THEN	'Equitorial Trust Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='IBP'	THEN	'Intercontinental Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='IBP'	THEN	'Intercontinental Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='UBN'	THEN	'Union Bank of Nigeria (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='FCMB'	THEN	'First City Monument Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='DBL'	THEN	'Diamond Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='FIB'	THEN	'First Inland Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='EBN'	THEN	'EcoBank Nigeria (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='ABP'	THEN	'Access Bank Plc (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='UBP'	THEN	'Unity Bank Plc (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='SPR'	THEN	'Enterprise Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='SBP'	THEN	'Sterling Bank Plc (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,4 ,3)='CITI'	THEN	'Citi Bank (CashCard)'
 WHEN LEFT(pan ,6) = '628051' and SUBSTRING ( sink_node_name  ,1 ,2)='FD'	THEN	'Cardless'
 WHEN LEFT(pan ,6) = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='UBA'	THEN	'United Bank for Africa (Verve PrepaidCard)'
 WHEN LEFT(pan ,6) = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='ZIB'	THEN	'Zenith International Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6) = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='PRU'	THEN	'Skye Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6) = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='PLAT'	THEN	'Keystone Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6) = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='CHB'	THEN	'Stanbic IBTC Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6) = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='GTB'	THEN	'Guaranty Trust Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='UBA'	THEN	'United Bank for Africa (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='FBN'	THEN	'First Bank of Nigeria (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='OBI'	THEN	'Oceanic Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='WEM'	THEN	'WEMA Bank Plc (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='AFRI'	THEN	'Main Street Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='ETB'	THEN	'Equitorial Trust Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='IBP'	THEN	'Intercontinental Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='IBP'	THEN	'Intercontinental Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='UBN'	THEN	'Union Bank of Nigeria (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='FCMB'	THEN	'First City Monument Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='DBL'	THEN	'Diamond Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='FIB'	THEN	'First Inland Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='EBN'	THEN	'EcoBank Nigeria (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='ABP'	THEN	'Access Bank Plc (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='UBP'	THEN	'Unity Bank Plc (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='SPR'	THEN	'Enterprise Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='SBP'	THEN	'Sterling Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='CITI'	THEN	'Citi Bank (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506100' and SUBSTRING ( sink_node_name  ,4 ,3)='ABS'	THEN	'Abbey (Verve PrepaidCard)'
 WHEN LEFT(pan ,6)  = '506104'	THEN	'Access Bank Plc (Verve Card)'
 WHEN LEFT(pan ,6)  = '506118'	THEN	'EcoBank Nigeria (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506108'	THEN	'First City Monument Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506115'	THEN	'Fidelity Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506114'	THEN	'First Inland Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506105'	THEN	'First Bank of Nigeria (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506103'	THEN	'Guaranty Trust Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506101'	THEN	'Intercontinental Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506110'	THEN	'Platinum Habib Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506106'	THEN	'Skye Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506116'	THEN	'Spring Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506107'	THEN	'Sterling Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506102'	THEN	'United Bank for Africa (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506117'	THEN	'Unity Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506119'	THEN	'Wema Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506109'	THEN	'Zenith Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506120'	THEN	'Stanbic IBTCC Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506122'	THEN	'Oceanic Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506121'	THEN	'ASO Savings (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506127'	THEN	'Hasal MFB (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506128'	THEN	'Afri Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506125'	THEN	'Equitorial Trust Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506111'	THEN	'Micro Finance Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '506129'	THEN	'Skye Mortgage (Verve Card)'
 WHEN LEFT(pan ,6)  = '506133'	THEN	'Resort Savings and Loans PLC (Verve Card)'
 WHEN LEFT(pan ,6)  = '533853'	THEN	'Guaranty Trust Bank (Mastercard Dollar Debit Card)'
 WHEN LEFT(pan ,6)  = '541569'	THEN	'Guaranty Trust Bank (Mastercard Dollar Credit Card)'
 WHEN LEFT(pan ,6)  = '539983'	THEN	'Guaranty Trust Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '533856'	THEN	'Guaranty Trust Bank (Mastercard Prepaid Card)'
 WHEN LEFT(pan ,6)  = '533853'	THEN	'Guaranty Trust Bank (Mastercard World Card)'
 WHEN LEFT(pan ,6)  = '539923'	THEN	'First Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '540761'	THEN	'Guaranty Trust Bank (Mastercard Prepaid Card)'
 WHEN LEFT(pan ,6)  = '520053'	THEN	'Intercontinental Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '521623'	THEN	'Intercontinental Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '557693'	THEN	'Intercontinental Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '526897'	THEN	'Intercontinental Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '531213'	THEN	'Intercontinental Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '557694'	THEN	'Intercontinental Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '512336'	THEN	'Zenith Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '515803'	THEN	'Zenith Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '530519'	THEN	'Zenith Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '531525'	THEN	'Zenith Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '533301'	THEN	'Zenith Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '539941'	THEN	'Zenith Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '547160'	THEN	'Zenith Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '549970'	THEN	'Zenith Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '536399'	THEN	'Unity Bank (Mastercard Prepaid Card)'
 WHEN LEFT(pan ,6)  = '551609'	THEN	'Unity Bank (Mastercard Verve Card)'
 WHEN LEFT(pan ,6)  = '539945'	THEN	'Skye Bank (Mastercard Verve Card)'
 WHEN LEFT(pan ,6)  = '555940'	THEN	'Platinum Habib Bank (Mastercard Naira Debit Card)'
 WHEN LEFT(pan ,6)  = '532732'	THEN	'Guaranty Trust Bank (Platinum Debit MasterCard naira)'
 WHEN LEFT(pan ,6)  = '506138'	THEN	'FinBank Flash Wallet'
 WHEN LEFT(pan ,6)  = '506135'	THEN	'Sterling Bank (Subsidiary)'
 WHEN LEFT(pan ,6)  = '548712'	THEN	'Ecobank (MasterCard Credit)'
 WHEN LEFT(pan ,6)  = '548458'	THEN	'Ecobank (MasterCard Credit)'
 WHEN LEFT(pan ,6)  = '532968'	THEN	'Ecobank (MasterCard Credit)'
 WHEN LEFT(pan ,6)  = '531667'	THEN	'Ecobank (MasterCard Credit)'
 WHEN LEFT(pan ,6)  = '521090'	THEN	'United Bank for Africa (Mastercard Verve Card)'
 WHEN LEFT(pan ,6)  = '528649'	THEN	'Stanbic IBTC Bank (Mastercard Verve Card)'
 WHEN LEFT(pan ,6)  = '506137'	THEN	'Jaiz Bank (Verve Debit Card)'
 WHEN LEFT(pan ,6)  = '528649'	THEN	'Wema Bank (Mastercard Verve Card)'
 WHEN LEFT(pan ,6)  = '506134'	THEN	'Union Homes Bank (Verve Card)'
 WHEN LEFT(pan ,6)  = '506142'	THEN	'Sterling Bank(NPF MFB) (Verve Card)'
 WHEN LEFT(pan ,6)  = '506143'	THEN	'Accion MFB (Verve Card)'
 WHEN LEFT(pan ,6)  = '506141'	THEN	'Post Service Homes Limited (Verve Card)'
 WHEN LEFT(pan ,6)  = '506148'	THEN	'Sterling Bank(Ohafia MFB) (Verve Card)'
 WHEN LEFT(pan ,6)  = '506147'	THEN	'Mutual Benefits Micro Finance bank  (Verve Card)'
 WHEN LEFT(pan ,6)  = '519911'	THEN	'United Bank for Africa (MasterCard)'
 WHEN LEFT(pan ,6)  = '517868'	THEN	'United Bank for Africa (MasterCard)'
 WHEN LEFT(pan ,6)  = '519885'	THEN	'United Bank for Africa (MasterCard)'
 WHEN LEFT(pan ,6)  = '519863'	THEN	'United Bank for Africa (MasterCard)'
 WHEN LEFT(pan ,6)  = '519899' OR  LEFT(pan ,6)  ='519905' OR  LEFT(pan ,6)  ='559424'  THEN 'Stanbic IBTC Bank (MasterCard)'
 WHEN LEFT(pan ,6)  = '527699' OR  LEFT(pan ,6)  ='524282' OR  LEFT(pan ,6)  ='519830' OR  LEFT(pan ,6)  ='521973' THEN 'First City Monumental Bank (MasterCard)'
 WHEN LEFT(pan ,6)  = '537610' OR  LEFT(pan ,6)  ='523776' OR  LEFT(pan ,6)  ='518304'  THEN 'Enterprise Bank (MasterCard)'
 WHEN LEFT(pan ,6)  = '539945' OR  LEFT(pan ,6)  ='519909' THEN 'Skye Bank (Mastercard Verve)'
 WHEN LEFT(pan ,6)  = '519615'	THEN	'First City Monumental Bank (Mastercard Verve)'
 WHEN LEFT(pan ,6)  = '528668' THEN 'Enterprise Bank (Mastercard Verve)'
 WHEN LEFT(pan ,6)  = '521988'	THEN	'Unity Bank (MasterCard Debit Platinum)'
 WHEN LEFT(pan ,6)  = '506124'	THEN	'Sterling Bank (Verve Payday)'
 WHEN LEFT(pan ,6)  = '506140'	THEN	'First Bank (Kakawa Discount House)'
 ELSE 
 'Unknown'
END

