

CASE WHEN  LEFT(extended_tran_type_reward ,4) =  '1000' THEN 'FBN First-Point'
 WHEN  LEFT(extended_tran_type_reward ,4) =  '3000' THEN 'FBN Forte Oil'
 WHEN   rdm_amount <> 0  AND NOT (LEFT(extended_tran_type_reward ,4) =  '1000')   AND NOT (LEFT(extended_tran_type_reward ,4) =  '3000') THEN 'InterSwitch'
 WHEN   payee = 'Verve' then 'InterSwitch'
WHEN @IndustrySegment = 'Intl Visa Transactions (Co-acquired)' then 'UBA Visa Intl'

WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code = '627821' then 'Wema TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code = '627480' then 'UBA TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code = '627805' then 'Skye TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code = '589019' then 'FBN TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code = '627858' then 'CHB TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code = '602980' then 'UBN TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code IN ('639563','512934','457714','506150') then 'HBC TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code IN ('627787','462526') then 'GTB TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code IN ('903708','603948') then 'EBN TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code = '627955' then 'KSB_TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code = '628009' then 'FCMB TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code = '639138' then 'FBP TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code = '639609' then 'UBP TempMcard'
WHEN  source_node_name IN ('SWTNCS2src','SWTNCSKIMsrc','SWTFBPsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code = '639139' then 'ABP TempMcard'
WHEN source_node_name IN  ('SWTNCS2src','SWTNCSKIMsrc','SWTSHOPRTsrc') and sink_node_name = 'ASPPOSLMCsnk' and acquiring_inst_id_code = '627481'  then 'UBA(For Citi) TempMcard'
WHEN source_node_name IN  ('SWTSHOPRTsrc') and sink_node_name = 'ASPPOSLMCsnk'  then 'UBA(For Citi) TempMcard'

WHEN SUBSTRING (extended_tran_type,2,3)='033' and sink_node_name = 'ESBCSOUTsnk' Then 'United Bank for Africa'
WHEN SUBSTRING (extended_tran_type,2,3)='057' and sink_node_name = 'ESBCSOUTsnk' Then 'Zenith International Bank'
WHEN SUBSTRING (extended_tran_type,2,3)='076' and sink_node_name = 'ESBCSOUTsnk' Then 'Skye Bank'
WHEN SUBSTRING (extended_tran_type,2,3)='082' and sink_node_name = 'ESBCSOUTsnk' Then 'Keystone Bank'
WHEN SUBSTRING (extended_tran_type,2,3) IN ('039','221') and sink_node_name = 'ESBCSOUTsnk' Then 'Stanbic IBTCC Bank'
WHEN SUBSTRING (extended_tran_type,2,3)='058' and sink_node_name = 'ESBCSOUTsnk' Then 'Guaranty Trust Bank'
WHEN SUBSTRING (extended_tran_type,2,3) IN ('701','011')  and sink_node_name = 'ESBCSOUTsnk' Then 'First Bank of Nigeria'
WHEN SUBSTRING (extended_tran_type,2,3)='035' and sink_node_name = 'ESBCSOUTsnk' Then 'Wema Bank Plc'
WHEN SUBSTRING (extended_tran_type,2,3)='014' and sink_node_name = 'ESBCSOUTsnk' Then 'Skye Bank'
WHEN SUBSTRING (extended_tran_type,2,3)='032' and sink_node_name = 'ESBCSOUTsnk' Then 'Union Bank of Nigeria'
WHEN SUBSTRING (extended_tran_type,2,3)='214' and sink_node_name = 'ESBCSOUTsnk' Then 'First City Monument Bank'
WHEN SUBSTRING (extended_tran_type,2,3)='063' and sink_node_name = 'ESBCSOUTsnk' Then 'Diamond Bank'
WHEN SUBSTRING (extended_tran_type,2,3)='050' and sink_node_name = 'ESBCSOUTsnk' Then 'EcoBank Nigeria'
WHEN SUBSTRING (extended_tran_type,2,3)='044' and sink_node_name = 'ESBCSOUTsnk' Then 'Access Bank Plc'
WHEN SUBSTRING (extended_tran_type,2,3)='215' and sink_node_name = 'ESBCSOUTsnk' Then 'Unity Bank Plc'
WHEN SUBSTRING (extended_tran_type,2,3)='030' and sink_node_name = 'ESBCSOUTsnk' Then 'Heritage Bank'
WHEN SUBSTRING (extended_tran_type,2,3)='232' and sink_node_name = 'ESBCSOUTsnk' Then 'Sterling Bank Plc'
WHEN SUBSTRING (extended_tran_type,2,3)='023' and sink_node_name = 'ESBCSOUTsnk' Then 'Citi Bank'
WHEN (SUBSTRING(pan, 1,6) = '589019') Then 'FBN Magstrip'
WHEN  (SUBSTRING(pan, 1,6) = '627480') Then 'United Bank for Africa'
WHEN (SUBSTRING(pan, 1,6) = '627629')  Then 'Zenith International Bank'
WHEN (SUBSTRING(pan, 1,6) = '627752')  Then 'United Bank for Africa'
WHEN (SUBSTRING(pan, 1,6) = '627787')  Then 'Guaranty Trust Bank'
WHEN (SUBSTRING(pan, 1,6) = '627805')  Then 'Skye Bank'
WHEN (SUBSTRING(pan, 1,6) = '627975')  Then 'Skye Bank'
WHEN (SUBSTRING(pan, 1,6) = '628027')  Then 'Skye Bank'
WHEN (SUBSTRING(pan, 1,6) = '603948')  Then 'Oceanic Bank'
WHEN (SUBSTRING(pan, 1,6) = '627821')  Then 'Wema Bank Plc'
WHEN (SUBSTRING(pan, 1,6) = '628016')  Then 'Wema Bank Plc'
WHEN (SUBSTRING(pan, 1,6) = '627819')  Then 'Main Street Bank'
WHEN (SUBSTRING(pan, 1,6) = '627858')  Then 'Stanbic IBTCC Bank'
WHEN (SUBSTRING(pan, 1,6) = '627955')  Then 'Keystone Bank'
WHEN (SUBSTRING(pan, 1,6) = '628009')  Then 'First City Monument Bank'
WHEN (SUBSTRING(pan, 1,6) = '628027')  Then 'EIB International Bank'
WHEN (SUBSTRING(pan, 1,6) = '639138')  Then 'Fidelity Bank'
WHEN (SUBSTRING(pan, 1,6) = '639276')  Then 'Fidelity Bank'
WHEN (SUBSTRING(pan, 1,6) = '636088')  Then 'Intercontinental Bank'
WHEN (SUBSTRING(pan, 1,6) = '602980')  Then 'Union Bank'
WHEN (SUBSTRING(pan, 1,6) = '627681')  Then 'Union Bank'
WHEN (SUBSTRING(pan, 1,6) = '627168')  Then 'Diamond Bank'
WHEN (SUBSTRING(pan, 1,6) = '639203')  Then 'First Inland Bank'
WHEN (SUBSTRING(pan, 1,6) = '639249')  Then 'Equitorial Trust Bank'
WHEN (SUBSTRING(pan, 1,6) = '639139')  Then 'Access Bank Plc'
WHEN (SUBSTRING(pan, 1,6) = '636092')  Then 'Sterling Bank Plc'
WHEN (SUBSTRING(pan, 1,6) = '903708')  Then 'EcoBank Nigeria'
WHEN (SUBSTRING(pan, 1,6) = '639609')  Then 'Unity Bank Plc'
WHEN (SUBSTRING(pan, 1,6) = '639563')  Then 'Enterprise Bank Non-Verve'
WHEN (SUBSTRING(pan, 1,6) = '606079')  Then 'Aso Savings'
WHEN (SUBSTRING(pan, 1,6) = '639587')  Then '3LINE'
WHEN SUBSTRING(pan, 1,6) = '521988' then 'Unity Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '506140' then 'First Bank of Nigeria'

WHEN SUBSTRING(pan, 1,6) = '628051' AND SUBSTRING(sink_node_name_node_name,4,3)='UBA' Then 'United Bank for Africa'
WHEN SUBSTRING(pan, 1,6) = '628051' AND SUBSTRING(sink_node_name_node_name,4,3)='ZIB' Then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' AND SUBSTRING(sink_node_name_node_name,4,3)='PRU' Then 'Skye Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' AND SUBSTRING(sink_node_name_node_name,4,3)='PLAT' Then 'Keystone Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' AND SUBSTRING(sink_node_name_node_name,4,3)='CHB' Then 'Stanbic IBTCC Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' AND SUBSTRING(sink_node_name_node_name,4,3)='GTB' Then 'Guaranty Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='UBA' Then 'United Bank for Africa'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='FBN' Then 'First Bank of Nigeria'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='OBI' Then 'Oceanic Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='WEM' Then 'Wema Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='AFRI' Then 'Main Street Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='ETB' Then 'Equitorial Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='IBP' Then 'Intercontinental Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='IBP' Then 'Intercontinental Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='UBN' Then 'Union Bank of Nigeria'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,4)='FCMB' Then 'First City Monument Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='DBL' Then 'Diamond Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='FIB' Then 'First Inland Bank'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='EBN' Then 'EcoBank Nigeria'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='ABP' Then 'Access Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='UBP' Then 'Unity Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='SPR' Then 'Enterprise Bank Non-Verve'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,3)='SBP' Then 'Sterling Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '628051' and SUBSTRING(sink_node_name_node_name,4,4)='CITI' Then 'Citi Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='UBA' Then 'United Bank for Africa'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='ZIB' Then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='PRU' Then 'Skye Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,4)='PLAT' Then 'Keystone Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='CHB' Then 'Stanbic IBTCC Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='GTB' Then 'Guaranty Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='UBA' Then 'United Bank for Africa'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='FBN' Then 'FBN CashCard'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='OBI' Then 'Oceanic Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='WEM' Then 'Wema Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,4)='AFRI' Then 'Main Street Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='ETB' Then 'Equitorial Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='IBP' Then 'Intercontinental Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='IBP' Then 'Intercontinental Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='UBN' Then 'Union Bank of Nigeria'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,4)='FCMB' Then 'First City Monument Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='DBL' Then 'Diamond Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='FIB' Then 'First Inland Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='EBN' Then 'EcoBank Nigeria'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='ABP' Then 'Access Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='UBP' Then 'Unity Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='SPR' Then 'Enterprise Bank Verve'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='SBP' Then 'Sterling Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,4)='CITI' Then 'Citi Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and SUBSTRING(sink_node_name_node_name,4,3)='ABS' Then 'Abbey Mortgage Bank'
WHEN SUBSTRING(pan, 1,6) = '506100' and MID ({osp_rpt_b04_web;1.sink_node_name_node_name},4,6)='PAYCOM' Then 'Paycom'
WHEN SUBSTRING(pan, 1,6) = '782427' and SUBSTRING(sink_node_name_node_name,4,3)='CHB' Then 'Stanbic Easyfuel'
WHEN SUBSTRING(pan, 1,6) = '782427' and SUBSTRING(sink_node_name_node_name,4,3)='EBN' Then 'EcoBank EasyFuel'
WHEN SUBSTRING(pan, 1,6) = '506124' and SUBSTRING(sink_node_name_node_name,4,3)='RDY' Then 'Readycash'
WHEN SUBSTRING(pan, 1,6) = '506124' and SUBSTRING(sink_node_name_node_name,4,3)='UNI' Then 'UNICAL MFB'
WHEN SUBSTRING(pan, 1,6) = '506124' and SUBSTRING(sink_node_name_node_name,4,3)='CON' Then 'Covenant MFB'
WHEN SUBSTRING(pan, 1,6) = '506124' and SUBSTRING(sink_node_name_node_name,4,3)='NPR' Then 'NPR'
WHEN SUBSTRING(pan, 1,6) = '506124' and SUBSTRING(sink_node_name_node_name,4,3)='AGH' Then 'AGHomes'
WHEN SUBSTRING(pan, 1,6) = '506124' and SUBSTRING(sink_node_name_node_name,4,3)='NPM' Then 'Nigerian Police'
WHEN SUBSTRING(pan, 1,6) = '506124' and SUBSTRING(sink_node_name_node_name,4,3)='WET' Then 'Wetland MFB'
WHEN SUBSTRING(pan, 1,6) = '506124' and SUBSTRING(sink_node_name_node_name,4,3)='MUT' Then 'Mutual Alliance'
WHEN SUBSTRING(pan, 1,6) = '506124' and SUBSTRING(sink_node_name_node_name,4,3)='OMO' Then 'OMOLUABI SAVINGS AND LOANS'
WHEN SUBSTRING(pan, 1,6) = '506104' then 'Access Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '506118' then 'EcoBank Nigeria'
WHEN SUBSTRING(pan, 1,6) = '506108' then 'First City Monument Bank'
WHEN SUBSTRING(pan, 1,6) = '506115' then 'Fidelity Bank'
WHEN SUBSTRING(pan, 1,6) = '506114' then 'First Inland Bank'
WHEN SUBSTRING(pan, 1,6) = '506105' then 'First Bank of Nigeria'
WHEN SUBSTRING(pan, 1,6) = '506103' then 'Guaranty Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '506101' then 'Intercontinental Bank'
WHEN SUBSTRING(pan, 1,6) = '506110' then 'Keystone Bank'
WHEN SUBSTRING(pan, 1,6) = '506106' then 'Skye Bank'
WHEN SUBSTRING(pan, 1,6) = '506116' then 'Enterprise Bank Verve'
WHEN SUBSTRING(pan, 1,6) = '506107' then 'Sterling Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '506102' then 'United Bank for Africa'
WHEN SUBSTRING(pan, 1,6) = '506117' then 'Unity Bank'
WHEN SUBSTRING(pan, 1,6) = '506119' then 'Wema Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '506109' then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '506120' then 'Stanbic IBTCC Bank'
WHEN SUBSTRING(pan, 1,6) = '506122' then 'Oceanic Bank'
WHEN SUBSTRING(pan, 1,6) = '506123' then 'Union Bank'
WHEN SUBSTRING(pan, 1,6) = '506121' then 'ASO Savings'
WHEN SUBSTRING(pan, 1,6) = '506127' then 'Hasal MFB'
WHEN SUBSTRING(pan, 1,6) = '506128' then 'Main Street Bank'
WHEN SUBSTRING(pan, 1,6) = '506125' then 'Equitorial Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '506111' then 'FBN Micro Finance'
WHEN SUBSTRING(pan, 1,6) = '506129' then 'Skye Bank'
WHEN SUBSTRING(pan, 1,6) = '506133' then 'Resort MFB'
WHEN SUBSTRING(pan, 1,6) = '533853' then 'Guaranty Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '541569' then 'Guaranty Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '539983' then 'Guaranty Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '533856' then 'Guaranty Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '533853' then 'Guaranty Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '539923' then 'FBN Naira Mastercard'
WHEN SUBSTRING(pan, 1,6) = '519878' then 'FBN Naira Mastercard' 
WHEN SUBSTRING(pan, 1,6) = '540761' then 'Guaranty Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '520053' then 'Intercontinental Bank'
WHEN SUBSTRING(pan, 1,6) = '521623' then 'Intercontinental Bank'
WHEN SUBSTRING(pan, 1,6) = '557693' then 'Intercontinental Bank'
WHEN SUBSTRING(pan, 1,6) = '526897' then 'Intercontinental Bank'
WHEN SUBSTRING(pan, 1,6) = '531213' then 'Intercontinental Bank'
WHEN SUBSTRING(pan, 1,6) = '557694' then 'Intercontinental Bank'
WHEN SUBSTRING(pan, 1,6) = '512336' then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '515803' then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '530519' then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '531525' then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '533301' then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '539941' then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '547160' then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '549970' then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '559443' then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '540884' then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '542231' then 'Zenith International Bank'
WHEN SUBSTRING(pan, 1,6) = '536399' then 'Unity Bank'
WHEN SUBSTRING(pan, 1,6) = '551609' then 'Unity Bank'
WHEN SUBSTRING(pan, 1,6) = '521988' then 'Unity Bank'
WHEN SUBSTRING(pan, 1,6) = '539945' then 'Skye Bank'
WHEN SUBSTRING(pan, 1,6) = '555940' then 'Keystone Bank'
WHEN SUBSTRING(pan, 1,6) = '532732' then 'Guaranty Trust Bank'
WHEN SUBSTRING(pan, 1,6) = '548712' then 'Ecobank Nigeria'
WHEN SUBSTRING(pan, 1,6) = '548458' then 'Ecobank Nigeria'
WHEN SUBSTRING(pan, 1,6) = '532968' then 'Ecobank Nigeria'
WHEN SUBSTRING(pan, 1,6) = '531667' then 'Ecobank Nigeria'
WHEN SUBSTRING(pan, 1,6) = '506138' then 'First Inland Bank'
WHEN SUBSTRING(pan, 1,6) = '506135' then 'Sterling Bank Plc'
WHEN SUBSTRING(pan, 1,6) in [ '521090','519911','517868','519885','519863'] then 'United Bank for Africa'
WHEN SUBSTRING(pan, 1,6) = '528649' then 'Stanbic IBTCC Bank'
WHEN SUBSTRING(pan, 1,6) = '506136' then 'Stanbic IBTCC Bank'
WHEN SUBSTRING(pan, 1,6) = '528650' then 'Stanbic IBTCC Bank'
WHEN SUBSTRING(pan, 1,6) = '559424' then 'Stanbic IBTCC Bank'
WHEN SUBSTRING(pan, 1,6) = '559432' then 'Stanbic IBTCC Bank'
WHEN SUBSTRING(pan, 1,6) = '559453' then 'Wema Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '506134' then 'Union Bank'
WHEN SUBSTRING(pan, 1,6) = '506142' then 'Sterling Bank Plc'
WHEN SUBSTRING(pan, 1,6) = '506143' then 'Accion MFB'
WHEN SUBSTRING(pan, 1,6) = '506141' then 'Post Service Homes Limited'
WHEN SUBSTRING(pan, 1,6) = '506148' then 'Sterling Bank(Ohafia MFB)'
WHEN SUBSTRING(pan, 1,6) = '506137' then 'Jaiz Bank'
WHEN SUBSTRING(pan, 1,6) = '553813' then 'Jaiz Bank'
WHEN SUBSTRING(pan, 1,6) = '528668' then 'Enterprise Bank Non-Verve'
WHEN SUBSTRING(pan, 1,6) = '506140' then 'First Bank of Nigeria'
WHEN SUBSTRING(pan, 1,6) = '506150' then 'Heritage Bank'
WHEN SUBSTRING(pan, 1,6) = '514585' then 'Fidelity Bank Mastercard'
WHEN SUBSTRING(pan, 1,6) = '512934' then 'Heritage Bank Mastercard'
WHEN SUBSTRING(pan, 1,6) in ('519899','519905','559424') then 'Stanbic IBTCC Bank'
WHEN SUBSTRING(pan, 1,6) in ('527699','524282','519830','521973','519615') then 'First City Monument Bank'
WHEN SUBSTRING(pan, 1,6) in ('537610','523776','518304','528668') then 'Enterprise Bank Non-Verve'
WHEN SUBSTRING(pan, 1,6) in ('539945','519909') then'Skye Bank'
WHEN SUBSTRING(pan, 1,6) = '506147' then 'Sterling Bank Plc'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='UBA' Then 'United Bank for Africa'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='ZIB' Then 'Zenith International Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='PRU' Then 'Skye Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='PLA' Then 'Keystone Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='CHB' Then 'Stanbic IBTCC Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='GTB' Then 'Guaranty Trust Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='UBA' Then 'United Bank for Africa'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='FBN' and not(SUBSTRING(pan, 1,6) startswith '4')Then 'First Bank of Nigeria'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='OBI' Then 'Oceanic Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='WEM' Then 'Wema Bank Plc'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='AFRI' Then 'Main Street Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='ETB' Then 'Equitorial Trust Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='IBP' Then 'Intercontinental Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='IBP' Then 'Intercontinental Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='UBN' Then 'Union Bank of Nigeria'
WHEN  SUBSTRING(sink_node_name_node_name,4,4)='FCMB' Then 'First City Monument Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='DBL' Then 'Diamond Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='FIB' Then 'First Inland Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='EBN' Then 'EcoBank Nigeria'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='ABP' Then 'Access Bank Plc'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='UBP' Then 'Unity Bank Plc'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='SPR' Then 'Enterprise Bank Non-Verve'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='SBP' Then 'Sterling Bank Plc'
WHEN  SUBSTRING(sink_node_name_node_name,4,4)='CITI' Then 'Citi Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='UBA' Then 'United Bank for Africa'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='ZIB' Then 'Zenith International Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='PRU' Then 'Skye Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,4)='PLAT' Then 'Keystone Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='CHB' Then 'Stanbic IBTCC Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='GTB' Then 'Guaranty Trust Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='UBA' Then 'United Bank for Africa'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='OBI' Then 'Oceanic Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='WEM' Then 'Wema Bank Plc'
WHEN  SUBSTRING(sink_node_name_node_name,4,4)='AFRI' Then 'Main Street Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='ETB' Then 'Equitorial Trust Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='IBP' Then 'Intercontinental Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='IBP' Then 'Intercontinental Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='UBN' Then 'Union Bank of Nigeria'
WHEN  SUBSTRING(sink_node_name_node_name,4,4)='FCMB' Then 'First City Monument Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='DBL' Then 'Diamond Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='FIB' Then 'First Inland Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='EBN' Then 'EcoBank Nigeria'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='ABP' Then 'Access Bank Plc'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='UBP' Then 'Unity Bank Plc'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='SPR' Then 'Enterprise Bank Non-Verve'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='SBP' Then 'Sterling Bank Plc'
WHEN  SUBSTRING(sink_node_name_node_name,4,4)='CITI' Then 'Citi Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='ABS' Then 'Abbey Mortgage Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,6)='PAYCOM' Then 'Paycom'
WHEN  SUBSTRING(sink_node_name_node_name,4,6)='CELCMS' Then 'Cellulant MFB'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='ENT' Then 'Enterprise Bank Non-Verve'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='HBC' Then 'Heritage Bank Mastercard'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='CAP' Then '03 Capital MFB'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='FGM' Then 'First Generation Mortgage Bank'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='MOU' Then 'Michael Okapara University MFB'
WHEN  SUBSTRING(sink_node_name_node_name,4,4)='SMFB' Then 'Seedvest MFB'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='TRU' Then 'TrustBond MFB'
WHEN  SUBSTRING(sink_node_name_node_name,4,4)='NPMB' Then 'Nigerian Police'
WHEN  SUBSTRING(sink_node_name_node_name,4,4)='AMJU' Then 'AMJU'
WHEN  SUBSTRING(sink_node_name_node_name,4,3)='OMO'  Then 'OMOLUABI SAVINGS AND LOANS'
WHEN  SUBSTRING(Totalsgroup,1,3)='UBA' Then 'United Bank for Africa'
WHEN  SUBSTRING(Totalsgroup,Totalsgroup,1,3)='ZIB' Then 'Zenith International Bank'
WHEN  SUBSTRING(Totalsgroup,Totalsgroup,1,3)='PRU' Then 'Skye Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='PLA' Then 'Keystone Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='CHB' Then 'Stanbic IBTCC Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='GTB' Then 'Guaranty Trust Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='UBA' Then 'United Bank for Africa'
WHEN  SUBSTRING(Totalsgroup,1,3)='FBN' and not(SUBSTRING(pan, 1,6) startswith '4') Then 'First Bank of Nigeria'
WHEN  SUBSTRING(Totalsgroup,1,3)='OBI' Then 'Oceanic Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='WEM' Then 'Wema Bank Plc'
WHEN  SUBSTRING(Totalsgroup,1,3)='AFR' Then 'Main Street Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='ETB' Then 'Equitorial Trust Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='IBP' Then 'Intercontinental Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='IBP' Then 'Intercontinental Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='UBN' Then 'Union Bank of Nigeria'
WHEN  SUBSTRING(Totalsgroup,1,4)='FCMB' Then 'First City Monument Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='DBL' Then 'Diamond Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='FIB' Then 'First Inland Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='EBN' Then 'EcoBank Nigeria'
WHEN  SUBSTRING(Totalsgroup,1,3)='ABP' Then 'Access Bank Plc'
WHEN  SUBSTRING(Totalsgroup,1,3)='UBP' Then 'Unity Bank Plc'
WHEN  SUBSTRING(Totalsgroup,1,3)='SPR' Then 'Enterprise Bank Non-Verve'
WHEN  SUBSTRING(Totalsgroup,1,3)='SBP' Then 'Sterling Bank Plc'
WHEN  SUBSTRING(Totalsgroup,1,4)='CITI' Then 'Citi Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='UBA' Then 'United Bank for Africa'
WHEN  SUBSTRING(Totalsgroup,1,3)='ZIB' Then 'Zenith International Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='PRU' Then 'Skye Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='CHB' Then 'Stanbic IBTCC Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='GTB' Then 'Guaranty Trust Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='UBA' Then 'United Bank for Africa'
WHEN  SUBSTRING(Totalsgroup,1,3)='FBN' and SUBSTRING(pan, 1,6) startswith '4' Then 'FBN Visa'
WHEN  SUBSTRING(Totalsgroup,1,3)='OBI' Then 'Oceanic Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='WEM' Then 'Wema Bank Plc'
WHEN  SUBSTRING(Totalsgroup,1,3)='ETB' Then 'Equitorial Trust Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='IBP' Then 'Intercontinental Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='IBP' Then 'Intercontinental Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='UBN' Then 'Union Bank of Nigeria'
WHEN  SUBSTRING(Totalsgroup,1,3)='DBL' Then 'Diamond Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='FIB' Then 'First Inland Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='EBN' Then 'EcoBank Nigeria'
WHEN  SUBSTRING(Totalsgroup,1,3)='ABP' Then 'Access Bank Plc'
WHEN  SUBSTRING(Totalsgroup,1,3)='UBP' Then 'Unity Bank Plc'
WHEN  SUBSTRING(Totalsgroup,1,3)='SPR' Then 'Enterprise Bank Non-Verve'
WHEN  SUBSTRING(Totalsgroup,1,3)='SBP' Then 'Sterling Bank Plc'
WHEN  SUBSTRING(Totalsgroup,1,4)='CITI' Then 'Citi Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='ABS' Then 'Abbey Mortgage Bank'
WHEN  SUBSTRING(Totalsgroup,1,6)='PAYCOM' Then 'Paycom'
WHEN  SUBSTRING(Totalsgroup,1,3)='ENT' Then 'Enterprise Bank Non-Verve'
WHEN  SUBSTRING(Totalsgroup,1,3)='FBP'  Then 'Fidelity Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='SCB'  Then 'Standard Chartered Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='HBC'  Then 'Heritage Bank Mastercard'
WHEN  SUBSTRING(Totalsgroup,1,3)='UML'  Then 'United Mortgage Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='OMO'  Then'OMOLUABI SAVINGS AND LOANS'
WHEN  SUBSTRING(Totalsgroup,1,3)='SUN'  Then 'Suntrust Bank Limited'
WHEN  SUBSTRING(Totalsgroup,1,4)='INFH'  Then 'Infinity Homes'
WHEN  SUBSTRING(Totalsgroup,1,3)='NPM'  Then 'Nigeria Police'
WHEN  SUBSTRING(Totalsgroup,1,3)='ALV'  Then 'ALVANA Bank'
WHEN  SUBSTRING(Totalsgroup,1,3)='POL'  Then 'POLYUNWANA MICROFINANCE BANK'
WHEN  SUBSTRING(Totalsgroup,1,3)='PRO'  Then 'PROVIDUS BANK'
WHEN  SUBSTRING(Totalsgroup,1,3)='MAY'  Then 'MAYFRESH BANK'
WHEN  SUBSTRING(Totalsgroup,1,3)='PAR'  Then 'PARALLEX BANK'
WHEN  SUBSTRING(Totalsgroup,1,4)='UNIL'  Then 'UNILORIN BANK'
else SUBSTRING(pan, 1,6)






