CREATE DATABASE [isw_data] ON  PRIMARY 
( NAME = N'isw_data', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data.mdf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 262144KB ), 
 FILEGROUP [APR] 
( NAME = N'isw_data_apr', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_apr.ndf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 262144KB ), 
 FILEGROUP [AUG] 
( NAME = N'isw_data_aug', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_aug.ndf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 262144KB ), 
 FILEGROUP [DEC] 
( NAME = N'isw_data_dec', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_dec.ndf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 262144KB ), 
 FILEGROUP [FEB] 
( NAME = N'isw_data_feb', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_feb.ndf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 262144KB ), 
 FILEGROUP [JAN] 
( NAME = N'isw_data_jan', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_jan.ndf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 1024KB ), 
 FILEGROUP [JUL] 
( NAME = N'isw_data_jul', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_jul.ndf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 262144KB ), 
 FILEGROUP [JUNE] 
( NAME = N'isw_data_june', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_june.ndf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 262144KB ), 
 FILEGROUP [MAR] 
( NAME = N'isw_data_mar', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_mar.ndf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 262144KB ), 
 FILEGROUP [MAY] 
( NAME = N'isw_data_may', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_may.ndf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 262144KB ), 
 FILEGROUP [NOV] 
( NAME = N'isw_data_nov', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_nov.ndf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 262144KB ), 
 FILEGROUP [SEP] 
( NAME = N'isw_data_oct', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_oct.ndf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 262144KB ), 
( NAME = N'isw_data_sep', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_sep.ndf' , SIZE = 2048KB , MAXSIZE = 40960000KB , FILEGROWTH = 262144KB )
 LOG ON 
( NAME = N'isw_data_log', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\isw_data_log.ldf' , SIZE = 1024KB , FILEGROWTH = 393216KB )
GO
ALTER DATABASE [isw_data] ADD FILEGROUP [OCT]
GO
ALTER DATABASE [isw_data] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [isw_data] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [isw_data] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [isw_data] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [isw_data] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [isw_data] SET ARITHABORT OFF 
GO
ALTER DATABASE [isw_data] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [isw_data] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [isw_data] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [isw_data] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [isw_data] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [isw_data] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [isw_data] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [isw_data] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [isw_data] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [isw_data] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [isw_data] SET  DISABLE_BROKER 
GO
ALTER DATABASE [isw_data] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [isw_data] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [isw_data] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [isw_data] SET  READ_WRITE 
GO
ALTER DATABASE [isw_data] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [isw_data] SET  MULTI_USER 
GO
ALTER DATABASE [isw_data] SET PAGE_VERIFY CHECKSUM  
GO
USE [isw_data]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [isw_data] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
