USE [master]
GO
/****** Object:  Table [dbo].[tbl_xls_settlement]    Script Date: 09/01/2015 10:49:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tbl_xls_settlement](
	[TC_TXN_IID] [numeric](12, 0) NOT NULL,
	[PAN] [nvarchar](19) NULL,
	[TERMINAL_NO] [nvarchar](8) NULL,
	[MERCHANT_NO] [nvarchar](15) NULL,
	[MERCHANT_NAME] [nvarchar](40) NULL,
	[TXN_DATE] [datetime] NOT NULL,
	[ORIGNIAL_PURCHASE_AMT] [numeric](21, 4) NOT NULL,
	[ADJUSTED_SPEND_AMT] [numeric](21, 4) NOT NULL,
	[TXN_TYPE] [numeric](2, 0) NOT NULL,
	[QUANTITY] [numeric](14, 4) NULL,
	[AMOUNT] [numeric](21, 4) NULL,
	[AUX_ENTITY_TYPE] [nvarchar](2) NULL,
	[AUX_ENTITY_IID] [numeric](10, 0) NULL,
	[CAMPAIGN_NAME] [nvarchar](24) NULL,
	[EXTENDED_TRAN_TYPE] [varchar](10) NULL DEFAULT ('9000')
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF


SELECT TC_TXN_IID
,LEFT(SUBSTRING(PAN, 5,LEN(PAN)),6)+'*********'+RIGHT(SUBSTRING(PAN, 5,LEN(PAN)),4) PAN
,TERMINAL_NO
,MERCHANT_NO
,MERCHANT_NAME
,TXN_DATE
,ORIGNIAL_PURCHASE_AMT
,ADJUSTED_SPEND_AMT
,TXN_TYPE
,QUANTITY
,AMOUNT
,AUX_ENTITY_TYPE
,AUX_ENTITY_IID
,CAMPAIGN_NAME
  FROM [XLS]..[XLS_ADMIN].[T_RM_REDEMPTION]

WHERE 
QUANTITY <>0
AND 
LEFT (TERMINAL_NO,1)='2'
--TXN_DATE >=DATEADD(D, -1, GETDATE()) AND  TXN_DATE <=GETDATE()
ORDER BY TXN_DATE DESC