USE [postilion_office]
GO

/****** Object:  View [dbo].[post_tran_summary]    Script Date: 09/02/2016 16:07:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[post_tran_summary]
				as
				
				
				/****** Script for SelectTopNRows command from SSMS  ******/


SELECT * from 

  openquery([172.25.10.89],  'SELECT [post_tran_id]
      ,[post_tran_cust_id]
      ,[prev_post_tran_id]
      ,[sink_node_name]
      ,[tran_postilion_originated]
      ,[tran_completed]
      ,[message_type]
      ,[tran_type]
      ,[tran_nr]
      ,[system_trace_audit_nr]
      ,[rsp_code_req]
      ,[rsp_code_rsp]
      ,[abort_rsp_code]
      ,[auth_id_rsp]
      ,[retention_data]
      ,[acquiring_inst_id_code]
      ,[message_reason_code]
      ,[retrieval_reference_nr]
      ,[datetime_tran_gmt]
      ,[datetime_tran_local]
      ,[datetime_req]
      ,[datetime_rsp]
      ,[realtime_business_date]
      ,[recon_business_date]
      ,[from_account_type]
      ,[to_account_type]
      ,[from_account_id]
      ,[to_account_id]
      ,[tran_amount_req]
      ,[tran_amount_rsp]
      ,[settle_amount_impact]
      ,[tran_cash_req]
      ,[tran_cash_rsp]
      ,[tran_currency_code]
      ,[tran_tran_fee_req]
      ,[tran_tran_fee_rsp]
      ,[tran_tran_fee_currency_code]
      ,[settle_amount_req]
      ,[settle_amount_rsp]
      ,[settle_tran_fee_req]
      ,[settle_tran_fee_rsp]
      ,[settle_currency_code]
	  , receiving_inst_id_code structured_data_req
      ,[tran_reversed]
      ,[prev_tran_approved]
      ,[extended_tran_type]
      ,[payee]
      ,[online_system_id]
      ,[receiving_inst_id_code]
      ,[routing_type]
      ,[source_node_name]
      ,[pan]
      ,[card_seq_nr]
      ,[expiry_date]
      ,[terminal_id]
      ,[terminal_owner]
      ,[card_acceptor_id_code]
      ,[merchant_type]
      ,[card_acceptor_name_loc]
      ,[address_verification_data]
      ,[totals_group]
      ,[pan_encrypted]
  FROM [postilion_office].[dbo].[post_tran_summary_latest]')
					--SELECT  a.[post_tran_id]
					--	  ,a.[post_tran_cust_id]
					--	  ,a.[prev_post_tran_id]
					--	  ,a.[sink_node_name]
					--	  ,a.[tran_postilion_originated]
					--	  ,a.[tran_completed]
					--	  ,a.[message_type]
					--	  ,a.[tran_type]
					--	  ,a.[tran_nr]
					--	  ,a.[system_trace_audit_nr]
					--	  ,a.[rsp_code_req]
					--	  ,a.[rsp_code_rsp]
					--	  ,a.[abort_rsp_code]
					--	  ,a.[auth_id_rsp]
					--	  ,a.[retention_data]
					--	  ,a.[acquiring_inst_id_code]
					--	  ,a.[message_reason_code]
					--	  ,a.[retrieval_reference_nr]
					--	  ,a.[datetime_tran_gmt]
					--	  ,a.[datetime_tran_local]
					--	  ,a.[datetime_req]
					--	  ,a.[datetime_rsp]
					--	  ,a.[realtime_business_date]
					--	  ,a.[recon_business_date]
					--	  ,a.[from_account_type]
					--	  ,a.[to_account_type]
					--	  ,a.[from_account_id]
					--	  ,a.[to_account_id]
					--	  ,a.[tran_amount_req]
					--	  ,a.[tran_amount_rsp]
					--	  ,a.[settle_amount_impact]
					--	  ,a.[tran_cash_req]
					--	  ,a.[tran_cash_rsp]
					--	  ,a.[tran_currency_code]
					--	  ,a.[tran_tran_fee_req]
					--	  ,a.[tran_tran_fee_rsp]
					--	  ,a.[tran_tran_fee_currency_code]
					--	  ,a.[settle_amount_req]
					--	  ,a.[settle_amount_rsp]
					--	  ,a.[settle_tran_fee_req]
					--	  ,a.[settle_tran_fee_rsp]
					--	  ,a.[settle_currency_code]
					--	  , b.structured_data_req
					--	  ,a.[tran_reversed]
					--	  ,a.[prev_tran_approved]
					--	  ,a.[extended_tran_type]
					--	  ,a.[payee]
					--	  ,a.[online_system_id]
					--	  ,a.[receiving_inst_id_code]
					--	  ,a.[routing_type]
					--	  ,a.[source_node_name]
					--	  ,a.[pan]
					--	  ,a.[card_seq_nr]
					--	  ,a.[expiry_date]
					--	  ,a.[terminal_id]
					--	  ,a.[terminal_owner]
					--	  ,a.[card_acceptor_id_code]
					--	  ,a.[merchant_type]
					--	  ,a.[card_acceptor_name_loc]
					--	  ,a.[address_verification_data]
					--	  ,a.[totals_group]
					--	  ,a.[pan_encrypted]
					--  FROM post_tran_summary_20160901 a (NOLOCK)
					  
					-- inner join post_tran b (NOLOCK) on b.post_tran_id  = a.post_tran_id
GO


