dbo	aa_entity_params	0
dbo	aa_lnk_cfg	0
dbo	at_log	0
dbo	aud_data	0
dbo	aud_events	0
dbo	aud_extract_session	0
dbo	aud_services	0
dbo	aud_states	0
dbo	cfg_class_registry	0
dbo	cfg_custom_classes	0
dbo	cfg_custom_libraries	0
dbo	cfg_languages	0
dbo	cfg_locales	0
dbo	cfg_lookup	0
dbo	cfg_system_properties	0
dbo	cfg_timezones	0
dbo	cfg_tran_names	0
dbo	cfg_tran_set_names	0
dbo	cp_account_types	0
dbo	cp_bin_list_suppliers	0
dbo	cp_card_sets	0
dbo	cp_card_types	0
dbo	cp_limits	0
dbo	cp_limits_classes	0
dbo	cp_totals_groups	0
dbo	crypto_dea1_group	0
dbo	crypto_dea1_key_transl_str	0
dbo	crypto_hsm_groups	0
dbo	crypto_hsm_types	0
dbo	crypto_keyspace	0
dbo	dbr_application_operations	0
dbo	dbr_application_versions	0
dbo	dbr_dep_rollback_objects	0
dbo	dbr_gate_keeper	0
dbo	dbr_sql_fragments	0
dbo	inject_incoming_files	0
dbo	inject_interfaces	0
dbo	inject_states	0
dbo	inject_trans	0
dbo	inject_transmission	0
dbo	ipm_incoming_files	0
dbo	irp_lazycache_reg	0
dbo	irp_tran_routing	0
dbo	lc_MEGKREPVB2_ia	0
dbo	lc_VCMS_ia	0
dbo	lc_VCMSECREDIT_ia	0
dbo	mccredit_acq_mec_acc_ind	0
dbo	mccredit_assigned_id	0
dbo	mccredit_card_types	0
dbo	mccredit_merc_mec_acc_ind	0
dbo	mccredit_onln_chkout_range	0
dbo	mnt_refresh_proc_plan_lock	0
dbo	pin_at_pos_mcc_exclusions	0
dbo	pki_ca_root_certs	0
dbo	pki_certmgr_config	0
dbo	pki_exchange_log	0
dbo	pki_external_certs	0
dbo	pki_keys	0
dbo	pki_local_certs	0
dbo	pki_requests	0
dbo	pki_trusted_addresses	0
dbo	pl_lookup_category	0
dbo	pl_run	0
dbo	postbridge_consl_fld_desc	0
dbo	postbridge_consl_flds	0
dbo	postbridge_mac_config	0
dbo	postbridge_mac_flds	0
dbo	prod_obj_cats	0
dbo	prod_reg	0
dbo	pth_m1MCCENT	0
dbo	pth_m1MCCFBP	0
dbo	pth_m1MCCFCMB	0
dbo	pth_m1MCCGTB	0
dbo	pth_m1MCCGTBSL	0
dbo	pth_m1MCCIBP	0
dbo	pth_m1MCCIBTC	0
dbo	pth_m1MCCOBI	0
dbo	pth_m1MCCUBN	0
dbo	pth_MEGKREPVB2_sk_v4_1	0
dbo	pth_VCMS_sk_v4_1	0
dbo	pth_VCMSECREDIT_sk_v4_1	0
dbo	pth_VisaSwitchKey_sk_v4_1	0
dbo	qrtz_blob_triggers	0
dbo	qrtz_calendars	0
dbo	qrtz_fired_triggers	0
dbo	qrtz_job_details	0
dbo	qrtz_locks	0
dbo	qrtz_paused_trigger_grps	0
dbo	qrtz_scheduler_state	0
dbo	rb8ea11976_020000_inject_trans_field	0
dbo	rollback_table_postinject_2_0_Patch_1_inject_trans	0
dbo	rollback_table_postinject_2_0_Patch_1_inject_transmission	0
dbo	scheduled_jobs	0
dbo	sec_auth_token	0
dbo	sec_groups	0
dbo	sec_ldap_types	0
dbo	sec_override_type	0
dbo	sec_passwords	0
dbo	sec_perm_cats	0
dbo	sec_user_types	0
dbo	ssb_fi_ext_config	0
dbo	support_email_config	0
dbo	support_email_log	0
dbo	support_event_interfaces	0
dbo	support_event_log	0
dbo	support_regions	0
dbo	task_uptime	0
dbo	tasks	0
dbo	term_groups	0
dbo	tm_bus_calendars	0
dbo	tm_command_requests	0
dbo	tm_countries	0
dbo	tm_currencies	0
dbo	tm_currencies_shadow	0
dbo	tm_hotcards_1	0
dbo	tm_hotcards_2	0
dbo	tm_hotcards_lock	0
dbo	tm_loaders_downloads	0
dbo	tm_loaders_loads	0
dbo	tm_routing_groups	0
dbo	tm_routing_priorities	0
dbo	tm_settlement_entities	0
dbo	tm_surcharge_states	0
dbo	tm_tran_groups	0
dbo	tm_tran_legs_1	0
dbo	tm_tran_legs_2	0
dbo	tm_tran_legs_3	0
dbo	tm_tran_legs_4	0
dbo	tm_tran_matches_1	0
dbo	tm_tran_matches_2	0
dbo	tm_tran_matches_3	0
dbo	tm_tran_matches_4	0
dbo	tm_tran_present_stmt	0
dbo	tm_tran_profile	0
dbo	tm_tran_volumes	0
dbo	tm_trans_1	0
dbo	tm_trans_2	0
dbo	tm_trans_3	0
dbo	tm_trans_4	0
dbo	tm_trans_ret_1	0
dbo	tm_trans_ret_2	0
dbo	tm_trans_ret_3	0
dbo	tm_trans_ret_4	0
dbo	tm_tv_partition_info	0
dbo	tm_ui_functions_to_tm	0
dbo	tm_vipcards	0
dbo	visabase12_admin_msg	0
dbo	visabase12_cps_aq_inst_map	0
dbo	visabase12_fleetcards	0
dbo	visabase12_incoming_files	0
dbo	visabase12_issuer_rsp_map	0
dbo	visabase12_map	0
dbo	visabase12_mcc_ia	0
dbo	visabase12_merch_cfg	0
dbo	visabase12_status_chk_map	0
dbo	aa_lnk_mon	1
dbo	aa_msg_q_cfg	1
dbo	aud_actions	1
dbo	aud_records	1
dbo	cfg_er_app_scribes	1
dbo	cfg_tran_sets	1
dbo	cfg_trends	1
dbo	cp_account_profiles	1
dbo	cp_allowed_cards	1
dbo	cp_card_profiles	1
dbo	cp_languages	1
dbo	crypto_custom_key_types	1
dbo	crypto_dea1_keys	1
dbo	crypto_hsms	1
dbo	crypto_services_hsms	1
dbo	crypto_variant_types	1
dbo	dbr_application_objects	1
dbo	node_interface	1
dbo	pki_ssl_saps	1
dbo	pl_lookup	1
dbo	pl_run_phase	1
dbo	pp_financial_institutions	1
dbo	prod_class_reg	1
dbo	qrtz_job_listeners	1
dbo	qrtz_triggers	1
dbo	sec_authenticators	1
dbo	sec_group_prod_policy	1
dbo	sec_ldap_cfgs	1
dbo	sec_preferences	1
dbo	sec_pwd_policy	1
dbo	sec_roles	1
dbo	sec_users	1
dbo	support_event_log_bin	1
dbo	support_event_log_open	1
dbo	support_event_log_params	1
dbo	support_event_log_rsps	1
dbo	support_events	1
dbo	support_teams	1
dbo	term_type	1
dbo	tm_acquirer	1
dbo	tm_acquirer_batch_lookup	1
dbo	tm_batches	1
dbo	tm_bus_calendar_dates	1
dbo	tm_bus_calendar_holidays	1
dbo	tm_card_acceptor	1
dbo	tm_cardaccptr_batch_lookup	1
dbo	tm_issuers	1
dbo	tm_nodes	1
dbo	tm_regions	1
dbo	tm_switch_batch_lookup	1
dbo	tm_term_batch_lookup	1
dbo	tm_tran_group_defn	1
dbo	visabase12_incoming_excps	1
dbo	aa_msg_q	2
dbo	applications	2
dbo	cfg_trend_mon_entities	2
dbo	cfg_trend_thresholds	2
dbo	cp_allowed_trans	2
dbo	cp_cards	2
dbo	cp_limits_profiles	2
dbo	crypto_dea1_key_group	2
dbo	crypto_hsm_properties	2
dbo	node	2
dbo	participant	2
dbo	pki_sap_external_certs	2
dbo	pl_run_phase_detail	2
dbo	pp_employee	2
dbo	pp_fi_issuers	2
dbo	pp_fi_prod_reg	2
dbo	qrtz_cron_triggers	2
dbo	qrtz_simple_triggers	2
dbo	qrtz_trigger_listeners	2
dbo	sec_group_authenticators	2
dbo	sec_group_ldap	2
dbo	sec_ldap_users	2
dbo	sec_permissions	2
dbo	sec_product_users	2
dbo	sec_user_preferences	2
dbo	sec_user_role_map	2
dbo	support_event_descriptions	2
dbo	support_members	2
dbo	term_hardware_type_descr	2
dbo	term_misc	2
dbo	term_status_type_descr	2
dbo	tm_control_nodes	2
dbo	tm_routes	2
dbo	tm_routes_by_inst	2
dbo	tm_settlement_dependencies	2
dbo	tm_sink_nodes	2
dbo	tm_source_nodes	2
dbo	tm_tran_notifications	2
dbo	cp_accounts	3
dbo	cp_bins	3
dbo	inject_msg_injectors	3
dbo	node_saps	3
dbo	participant_user_rights	3
dbo	participants_sink_nodes	3
dbo	participants_source_nodes	3
dbo	pl_run_phase_detail_params	3
dbo	pp_fi_participants	3
dbo	sec_cat_perm_map	3
dbo	sec_instance_permissions	3
dbo	sec_prd_prm_cfg	3
dbo	sec_prod_perm_map	3
dbo	sec_product_perm_map	3
dbo	sec_pwd_history	3
dbo	sec_role_perm_map	3
dbo	sec_scope	3
dbo	sec_usr_perm_ovrd	3
dbo	term	3
dbo	term_hardware	3
dbo	term_hardware_type	3
dbo	term_status	3
dbo	term_status_type	3
dbo	tm_integration_pipeline	3
dbo	tm_routes_by_sink_inst	3
dbo	tm_sink_node_mapped_fields	3
dbo	visabase12_cards	3
dbo	node_conns	4
dbo	sec_rl_inst_perms	4
dbo	sec_usr_inst_perms	4
dbo	term_group_terms	4
