JOBS';
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Not_On_Us_disk';
 WAITFOR  DELAY    '00:15:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks WebPay_Acquired_disk';
 WAITFOR  DELAY    '00:10:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Payment_Gateway';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks WebAcquired_csv';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks PrepaidCardLoad_csv';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Payment_Gateway_csv';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks PrepaidCardLoad';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Remote_WEB_disk';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Mobility_csv';
 WAITFOR  DELAY    '00:15:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Mobility_csv1';
 WAITFOR  DELAY    '00:15:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Remote_Web_csv';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks NotOnUs_csv';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks AutoPay_csv';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Mobility_Acqiured';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Mobility';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Billpayment_issuer_csv';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks AutoPay';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Billpayment_issuer';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Billpayment_Acquirer_csv';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Billpayment_Acquired';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Not_On_Us_Terminal';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks GPR_csv';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks GPR_DISK';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks AutoPay_sponsor_csv';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks AutoPay_sponsor_pdf';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Verve_International';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks Remote_On_Us_disk';
 WAITFOR  DELAY    '00:30:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Banks RemoteOnUs_csv';
 WAITFOR  DELAY    '00:30:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - HBC';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - O3 CAPITAL';
 WAITFOR  DELAY    '00:15:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - AMJU ';
 WAITFOR  DELAY    '00:15:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - 3LINE';
 WAITFOR  DELAY    '00:15:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - UML';
 WAITFOR  DELAY    '00:10:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - PTSP - Non-Banks';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - Terminal_Owner - Non-Banks';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - ASO';
 WAITFOR  DELAY    '00:05:00' ;
 exec  msdb.dbo.sp_start_job     @job_name='Postilion Office - Reports - INFH';