SELECT  CONVERT(int,SUBSTRING(TABLE_NAME, (CHARINDEX('ds_', TABLE_NAME)+3), LEN(TABLE_NAME))), *  FROM INFORMATION_SCHEMA.TABLES where  table_type = 'BASE TABLE' AND TABLE_NAME LIKE 'pc_cards_[0-9]%' 
ORDER BY  CONVERT(int,SUBSTRING(TABLE_NAME, (CHARINDEX('ds_', TABLE_NAME)+3), LEN(TABLE_NAME)))  desc

select DISTINCT BUSINESS_DATE from sstl_journal_121 (NOLOCK)