SELECT  'spay_acc_rel_type' ,  COUNT(*)  FROM  spay_acc_rel_type    
UNION  SELECT  'spay_aggregation',  COUNT(*)  FROM  spay_aggregation
UNION  SELECT  'spay_aggregation_w',  COUNT(*)  FROM  spay_aggregation_w
UNION  SELECT  'spay_aggr_strategy',  COUNT(*)  FROM  spay_aggr_strategy
UNION  SELECT  'spay_amount_pay_next_date',  COUNT(*)  FROM  spay_amount_pay_next_date
UNION  SELECT  'spay_bdate_fltr_ssn',  COUNT(*)  FROM  spay_bdate_fltr_ssn
UNION  SELECT  'spay_fee_pay_next_date',  COUNT(*)  FROM  spay_fee_pay_next_date
UNION  SELECT  'spay_plugin',  COUNT(*)  FROM  spay_plugin
UNION  SELECT  'spay_proc_ent',  COUNT(*)  FROM  spay_proc_ent
UNION  SELECT  'spay_proc_ent_fltr_grp',  COUNT(*)  FROM  spay_proc_ent_fltr_grp
UNION  SELECT  'spay_proc_ent_fltr_grp_w',  COUNT(*)  FROM  spay_proc_ent_fltr_grp_w
UNION  SELECT  'spay_proc_ent_w',  COUNT(*)  FROM  spay_proc_ent_w
UNION  SELECT  'spay_residue_ach',  COUNT(*)  FROM  spay_residue_ach
UNION  SELECT  'spay_residue_strategy',  COUNT(*)  FROM  spay_residue_strategy
UNION  SELECT  'spay_session',  COUNT(*)  FROM  spay_session
UNION  SELECT  'spay_se_acc',  COUNT(*)  FROM  spay_se_acc
UNION  SELECT  'spay_se_acc_rel',  COUNT(*)  FROM  spay_se_acc_rel
UNION  SELECT  'spay_se_acc_rel_param',  COUNT(*)  FROM  spay_se_acc_rel_param
UNION  SELECT  'spay_se_acc_rel_param_w',  COUNT(*)  FROM  spay_se_acc_rel_param_w
UNION  SELECT  'spay_se_acc_rel_w',  COUNT(*)  FROM  spay_se_acc_rel_w
UNION  SELECT  'spay_se_acc_w',  COUNT(*)  FROM  spay_se_acc_w
UNION  SELECT  'spay_se_amount_pay_freq',  COUNT(*)  FROM  spay_se_amount_pay_freq
UNION  SELECT  'spay_se_amount_pay_freq_w',  COUNT(*)  FROM  spay_se_amount_pay_freq_w
UNION  SELECT  'spay_se_fee_pay_freq',  COUNT(*)  FROM  spay_se_fee_pay_freq
UNION  SELECT  'spay_se_fee_pay_freq_w',  COUNT(*)  FROM  spay_se_fee_pay_freq_w
UNION  SELECT  'spay_statement_profile',  COUNT(*)  FROM  spay_statement_profile
UNION  SELECT  'spay_statement_profile_w',  COUNT(*)  FROM  spay_statement_profile_w
UNION  SELECT  'spay_unpaid_payments',  COUNT(*)  FROM  spay_unpaid_payments
UNION  SELECT  'spst_aggregation',  COUNT(*)  FROM  spst_aggregation
UNION  SELECT  'spst_aggregation_w',  COUNT(*)  FROM  spst_aggregation_w
UNION  SELECT  'spst_aggr_strategy',  COUNT(*)  FROM  spst_aggr_strategy
UNION  SELECT  'spst_amount_pst_next_date',  COUNT(*)  FROM  spst_amount_pst_next_date
UNION  SELECT  'spst_bdate_fltr_ssn',  COUNT(*)  FROM  spst_bdate_fltr_ssn
UNION  SELECT  'spst_exception',  COUNT(*)  FROM  spst_exception
UNION  SELECT  'spst_fee_pst_next_date',  COUNT(*)  FROM  spst_fee_pst_next_date
UNION  SELECT  'spst_plugin',  COUNT(*)  FROM  spst_plugin
UNION  SELECT  'spst_proc_ent',  COUNT(*)  FROM  spst_proc_ent
UNION  SELECT  'spst_proc_ent_fltr_grp',  COUNT(*)  FROM  spst_proc_ent_fltr_grp
UNION  SELECT  'spst_proc_ent_fltr_grp_w',  COUNT(*)  FROM  spst_proc_ent_fltr_grp_w
UNION  SELECT  'spst_proc_ent_w',  COUNT(*)  FROM  spst_proc_ent_w
UNION  SELECT  'spst_residue_strategy',  COUNT(*)  FROM  spst_residue_strategy
UNION  SELECT  'spst_session',  COUNT(*)  FROM  spst_session
UNION  SELECT  'spst_se_amount_pst_freq',  COUNT(*)  FROM  spst_se_amount_pst_freq
UNION  SELECT  'spst_se_amount_pst_freq_w',  COUNT(*)  FROM  spst_se_amount_pst_freq_w
UNION  SELECT  'spst_se_fee_pst_freq',  COUNT(*)  FROM  spst_se_fee_pst_freq
UNION  SELECT  'spst_se_fee_pst_freq_w',  COUNT(*)  FROM  spst_se_fee_pst_freq_w
UNION  SELECT  'spst_statement_profile',  COUNT(*)  FROM  spst_statement_profile
UNION  SELECT  'spst_statement_profile_w',  COUNT(*)  FROM  spst_statement_profile_w
UNION  SELECT  'ssdi_plugin',  COUNT(*)  FROM  ssdi_plugin
UNION  SELECT  'ssdi_proc_ent',  COUNT(*)  FROM  ssdi_proc_ent
UNION  SELECT  'ssdi_proc_ent_w',  COUNT(*)  FROM  ssdi_proc_ent_w
UNION  SELECT  'ssdi_session',  COUNT(*)  FROM  ssdi_session
UNION  SELECT  'ssdi_tran',  COUNT(*)  FROM  ssdi_tran
UNION  SELECT  'sstl_acc',  COUNT(*)  FROM  sstl_acc
UNION  SELECT  'sstl_acc_w',  COUNT(*)  FROM  sstl_acc_w
UNION  SELECT  'sstl_coa',  COUNT(*)  FROM  sstl_coa
UNION  SELECT  'sstl_coa_w',  COUNT(*)  FROM  sstl_coa_w
UNION  SELECT  'sstl_config_set',  COUNT(*)  FROM  sstl_config_set
UNION  SELECT  'sstl_config_version',  COUNT(*)  FROM  sstl_config_version
UNION  SELECT  'sstl_exception',  COUNT(*)  FROM  sstl_exception
UNION  SELECT  'sstl_fee_calc_strat',  COUNT(*)  FROM  sstl_fee_calc_strat
UNION  SELECT  'sstl_func',  COUNT(*)  FROM  sstl_func
UNION  SELECT  'sstl_journal_1',  COUNT(*)  FROM  sstl_journal_1
UNION  SELECT  'sstl_journal_adj',  COUNT(*)  FROM  sstl_journal_adj
UNION  SELECT  'sstl_journal_entry_insert_fltr',  COUNT(*)  FROM  sstl_journal_entry_insert_fltr
UNION  SELECT  'sstl_journal_fltr',  COUNT(*)  FROM  sstl_journal_fltr
UNION  SELECT  'sstl_journal_fltr_grp',  COUNT(*)  FROM  sstl_journal_fltr_grp
UNION  SELECT  'sstl_journal_fltr_grp_elem',  COUNT(*)  FROM  sstl_journal_fltr_grp_elem
UNION  SELECT  'sstl_journal_fltr_grp_elem_w',  COUNT(*)  FROM  sstl_journal_fltr_grp_elem_w
UNION  SELECT  'sstl_journal_fltr_grp_w',  COUNT(*)  FROM  sstl_journal_fltr_grp_w
UNION  SELECT  'sstl_journal_fltr_param',  COUNT(*)  FROM  sstl_journal_fltr_param
UNION  SELECT  'sstl_journal_fltr_param_w',  COUNT(*)  FROM  sstl_journal_fltr_param_w
UNION  SELECT  'sstl_journal_part_info',  COUNT(*)  FROM  sstl_journal_part_info
UNION  SELECT  'sstl_method',  COUNT(*)  FROM  sstl_method
UNION  SELECT  'sstl_nt_fee_calc_strat',  COUNT(*)  FROM  sstl_nt_fee_calc_strat
UNION  SELECT  'sstl_nt_fee_levy_hist',  COUNT(*)  FROM  sstl_nt_fee_levy_hist
UNION  SELECT  'sstl_pred',  COUNT(*)  FROM  sstl_pred
UNION  SELECT  'sstl_pred_prop_value',  COUNT(*)  FROM  sstl_pred_prop_value
UNION  SELECT  'sstl_pred_prop_value_w',  COUNT(*)  FROM  sstl_pred_prop_value_w
UNION  SELECT  'sstl_pred_w',  COUNT(*)  FROM  sstl_pred_w
UNION  SELECT  'sstl_proc_ent',  COUNT(*)  FROM  sstl_proc_ent
UNION  SELECT  'sstl_proc_ent_w',  COUNT(*)  FROM  sstl_proc_ent_w
UNION  SELECT  'sstl_prop',  COUNT(*)  FROM  sstl_prop
UNION  SELECT  'sstl_prop_value',  COUNT(*)  FROM  sstl_prop_value
UNION  SELECT  'sstl_prop_value_node',  COUNT(*)  FROM  sstl_prop_value_node
UNION  SELECT  'sstl_prop_value_node_w',  COUNT(*)  FROM  sstl_prop_value_node_w
UNION  SELECT  'sstl_prop_value_w',  COUNT(*)  FROM  sstl_prop_value_w
UNION  SELECT  'sstl_prop_w',  COUNT(*)  FROM  sstl_prop_w
UNION  SELECT  'sstl_se',  COUNT(*)  FROM  sstl_se
UNION  SELECT  'sstl_session',  COUNT(*)  FROM  sstl_session
UNION  SELECT  'sstl_se_acc_nr',  COUNT(*)  FROM  sstl_se_acc_nr
UNION  SELECT  'sstl_se_acc_nr_w',  COUNT(*)  FROM  sstl_se_acc_nr_w
UNION  SELECT  'sstl_se_additional_info',  COUNT(*)  FROM  sstl_se_additional_info
UNION  SELECT  'sstl_se_amount',  COUNT(*)  FROM  sstl_se_amount
UNION  SELECT  'sstl_se_amount_value',  COUNT(*)  FROM  sstl_se_amount_value
UNION  SELECT  'sstl_se_amount_value_int',  COUNT(*)  FROM  sstl_se_amount_value_int
UNION  SELECT  'sstl_se_amount_value_int_w',  COUNT(*)  FROM  sstl_se_amount_value_int_w
UNION  SELECT  'sstl_se_amount_value_w',  COUNT(*)  FROM  sstl_se_amount_value_w
UNION  SELECT  'sstl_se_amount_w',  COUNT(*)  FROM  sstl_se_amount_w
UNION  SELECT  'sstl_se_cal',  COUNT(*)  FROM  sstl_se_cal
UNION  SELECT  'sstl_se_cal_date_range',  COUNT(*)  FROM  sstl_se_cal_date_range
UNION  SELECT  'sstl_se_cal_date_range_w',  COUNT(*)  FROM  sstl_se_cal_date_range_w
UNION  SELECT  'sstl_se_cal_w',  COUNT(*)  FROM  sstl_se_cal_w
UNION  SELECT  'sstl_se_fee',  COUNT(*)  FROM  sstl_se_fee
UNION  SELECT  'sstl_se_fee_priority',  COUNT(*)  FROM  sstl_se_fee_priority
UNION  SELECT  'sstl_se_fee_priority_w',  COUNT(*)  FROM  sstl_se_fee_priority_w
UNION  SELECT  'sstl_se_fee_value',  COUNT(*)  FROM  sstl_se_fee_value
UNION  SELECT  'sstl_se_fee_value_w',  COUNT(*)  FROM  sstl_se_fee_value_w
UNION  SELECT  'sstl_se_fee_w',  COUNT(*)  FROM  sstl_se_fee_w
UNION  SELECT  'sstl_se_nt_fee',  COUNT(*)  FROM  sstl_se_nt_fee
UNION  SELECT  'sstl_se_nt_fee_acc_post',  COUNT(*)  FROM  sstl_se_nt_fee_acc_post
UNION  SELECT  'sstl_se_nt_fee_acc_post_w',  COUNT(*)  FROM  sstl_se_nt_fee_acc_post_w
UNION  SELECT  'sstl_se_nt_fee_value',  COUNT(*)  FROM  sstl_se_nt_fee_value
UNION  SELECT  'sstl_se_nt_fee_value_w',  COUNT(*)  FROM  sstl_se_nt_fee_value_w
UNION  SELECT  'sstl_se_nt_fee_w',  COUNT(*)  FROM  sstl_se_nt_fee_w
UNION  SELECT  'sstl_se_rule',  COUNT(*)  FROM  sstl_se_rule
UNION  SELECT  'sstl_se_rule_acc_post',  COUNT(*)  FROM  sstl_se_rule_acc_post
UNION  SELECT  'sstl_se_rule_acc_post_w',  COUNT(*)  FROM  sstl_se_rule_acc_post_w
UNION  SELECT  'sstl_se_rule_w',  COUNT(*)  FROM  sstl_se_rule_w
UNION  SELECT  'sstl_se_statement',  COUNT(*)  FROM  sstl_se_statement
UNION  SELECT  'sstl_se_statement_w',  COUNT(*)  FROM  sstl_se_statement_w
UNION  SELECT  'sstl_se_tax',  COUNT(*)  FROM  sstl_se_tax
UNION  SELECT  'sstl_se_tax_rate',  COUNT(*)  FROM  sstl_se_tax_rate
UNION  SELECT  'sstl_se_tax_rate_w',  COUNT(*)  FROM  sstl_se_tax_rate_w
UNION  SELECT  'sstl_se_tax_w',  COUNT(*)  FROM  sstl_se_tax_w
UNION  SELECT  'sstl_se_third_party',  COUNT(*)  FROM  sstl_se_third_party
UNION  SELECT  'sstl_se_third_party_w',  COUNT(*)  FROM  sstl_se_third_party_w
UNION  SELECT  'sstl_se_type',  COUNT(*)  FROM  sstl_se_type
UNION  SELECT  'sstl_se_w',  COUNT(*)  FROM  sstl_se_w
UNION  SELECT  'sstl_statement_output_method',  COUNT(*)  FROM  sstl_statement_output_method
UNION  SELECT  'sstl_statement_plugin',  COUNT(*)  FROM  sstl_statement_plugin
UNION  SELECT  'sstl_statement_profile',  COUNT(*)  FROM  sstl_statement_profile
UNION  SELECT  'sstl_statement_profile_w',  COUNT(*)  FROM  sstl_statement_profile_w
UNION  SELECT  'sstl_statement_report',  COUNT(*)  FROM  sstl_statement_report
UNION  SELECT  'sstl_stmt_standard_session',  COUNT(*)  FROM  sstl_stmt_standard_session
UNION  SELECT  'sstl_stmt_standard_summary',  COUNT(*)  FROM  sstl_stmt_standard_summary
UNION  SELECT  'sstl_table_meta_data',  COUNT(*)  FROM  sstl_table_meta_data
UNION  SELECT  'sstl_tran_field',  COUNT(*)  FROM  sstl_tran_field
UNION  SELECT  'sstl_tran_field_w',  COUNT(*)  FROM  sstl_tran_field_w
UNION  SELECT  'sstl_tran_ident',  COUNT(*)  FROM  sstl_tran_ident
UNION  SELECT  'sstl_tran_ident_def',  COUNT(*)  FROM  sstl_tran_ident_def
UNION  SELECT  'sstl_tran_ident_def_w',  COUNT(*)  FROM  sstl_tran_ident_def_w
UNION  SELECT  'sstl_tran_ident_w',  COUNT(*)  FROM  sstl_tran_ident_w
UNION  SELECT  'sstl_tran_set',  COUNT(*)  FROM  sstl_tran_set
UNION  SELECT  'sstl_tt_amount_next_date',  COUNT(*)  FROM  sstl_tt_amount_next_date
UNION  SELECT  'sstl_tt_exclude',  COUNT(*)  FROM  sstl_tt_exclude
UNION  SELECT  'sstl_tt_fee_next_date',  COUNT(*)  FROM  sstl_tt_fee_next_date