
			 		SELECT distinct BANK_CODE,trxn_category,  sum(trxn_amount) amount into temp_details_table_20170704_local	 FROM   dbo.sstl_summary_breakdown_details_20170704 (nolock)
			 		WHERE 
			 		trxn_category  NOT IN  
			 		
			 		('SWITCHED_OUT_NONFINANCIAL_FOREIGN_REQUEST',
			 'SWITCHED_IN_FAILED_DOMESTIC_AUTHORIZATION',
			 'MASTERCARD POS PURCHASE PROCESSOR BILLING',
			 'SWITCHED_IN_FAILED_FOREIGN_REQUEST',
			 'SWITCHED_IN_FINANCIAL_FOREIGN_AUTHORIZATION',
			 'SWITCHED_IN_FINANCIAL_DOMESTIC_REQUEST',
			 'SWITCHED_OUT_FINANCIAL_FOREIGN_AUTHORIZATION',
			 'SWITCHED_OUT_FINANCIAL_FOREIGN_COMPLETION',
			 'VISA ATM ROU BILLING',
			 'SWITCHED_IN_FINANCIAL_DOMESTIC_AUTHORIZATION',
			 'SWITCHED_IN_FAILED_FOREIGN_AUTHORIZATION',
			 'MASTERCARD ATM ROU BILLING',
			 'SWITCHED_OUT_FINANCIAL_FOREIGN_REQUEST',
			 'REWARD MONEY (SPEND) POS FEE SETTLEMENT',
			 'SWITCHED_OUT_FAILED_FOREIGN_REQUEST',
			 'SWITCHED_IN_FINANCIAL_FOREIGN_REQUEST',
			 'REWARD MONEY (SPEND) WEB FEE SETTLEMENT',
			 'SWITCHED_IN_NONFINANCIAL_FOREIGN_REQUEST',
			 'MASTERCARD POS PURCHASE PTSP BILLING') 
			 		 group by  	BANK_CODE,trxn_category
			 		 			
			 		SELECT distinct BANK_CODE,trxn_category,  sum(trxn_amount) amount into temp_details_table_20170704	 FROM   dbo.sstl_summary_breakdown_details_20170704(nolock)
			 		WHERE 
			 		trxn_category  NOT IN  
			 		
			 		('SWITCHED_OUT_NONFINANCIAL_FOREIGN_REQUEST',
			 'SWITCHED_IN_FAILED_DOMESTIC_AUTHORIZATION',
			 'MASTERCARD POS PURCHASE PROCESSOR BILLING',
			 'SWITCHED_IN_FAILED_FOREIGN_REQUEST',
			 'SWITCHED_IN_FINANCIAL_FOREIGN_AUTHORIZATION',
			 'SWITCHED_IN_FINANCIAL_DOMESTIC_REQUEST',
			 'SWITCHED_OUT_FINANCIAL_FOREIGN_AUTHORIZATION',
			 'SWITCHED_OUT_FINANCIAL_FOREIGN_COMPLETION',
			 'VISA ATM ROU BILLING',
			 'SWITCHED_IN_FINANCIAL_DOMESTIC_AUTHORIZATION',
			 'SWITCHED_IN_FAILED_FOREIGN_AUTHORIZATION',
			 'MASTERCARD ATM ROU BILLING',
			 'SWITCHED_OUT_FINANCIAL_FOREIGN_REQUEST',
			 'REWARD MONEY (SPEND) POS FEE SETTLEMENT',
			 'SWITCHED_OUT_FAILED_FOREIGN_REQUEST',
			 'SWITCHED_IN_FINANCIAL_FOREIGN_REQUEST',
			 'REWARD MONEY (SPEND) WEB FEE SETTLEMENT',
			 'SWITCHED_IN_NONFINANCIAL_FOREIGN_REQUEST',
			 'MASTERCARD POS PURCHASE PTSP BILLING') 
			 		 group by  	BANK_CODE,trxn_category
			 		 
					
			 		 SELECT BANK_CODE, trxn_category, sum(trxn_amount)	amount	 into temp_breakdown_20170704 FROM  [172.75.75.19].postilion_office.dbo.settlement_summary_breakdown (nolock)
			 		 WHERE trxn_date = '20170704' and trxn_category  NOT IN  
			 		
			 		('SWITCHED_OUT_NONFINANCIAL_FOREIGN_REQUEST',
			 'SWITCHED_IN_FAILED_DOMESTIC_AUTHORIZATION',
			 'MASTERCARD POS PURCHASE PROCESSOR BILLING',
			 'SWITCHED_IN_FAILED_FOREIGN_REQUEST',
			 'SWITCHED_IN_FINANCIAL_FOREIGN_AUTHORIZATION',
			 'SWITCHED_IN_FINANCIAL_DOMESTIC_REQUEST',
			 'SWITCHED_OUT_FINANCIAL_FOREIGN_AUTHORIZATION',
			 'SWITCHED_OUT_FINANCIAL_FOREIGN_COMPLETION',
			 'VISA ATM ROU BILLING',
			 'SWITCHED_IN_FINANCIAL_DOMESTIC_AUTHORIZATION',
			 'SWITCHED_IN_FAILED_FOREIGN_AUTHORIZATION',
			 'MASTERCARD ATM ROU BILLING',
			 'SWITCHED_OUT_FINANCIAL_FOREIGN_REQUEST',
			 'REWARD MONEY (SPEND) POS FEE SETTLEMENT',
			 'SWITCHED_OUT_FAILED_FOREIGN_REQUEST',
			 'SWITCHED_IN_FINANCIAL_FOREIGN_REQUEST',
			 'REWARD MONEY (SPEND) WEB FEE SETTLEMENT',
			 'SWITCHED_IN_NONFINANCIAL_FOREIGN_REQUEST',
			 'MASTERCARD POS PURCHASE PTSP BILLING') 
			 		 group by  	BANK_CODE,trxn_category
			 		 
			 			 
			 		--SELECT * FROM temp_details_table_20170427 WHERE bank_code = 'fbn' order by trxn_category
			 		--SELECT * FROM  temp_breakdown_20170427 WHERE bank_code = 'fbn' order by trxn_category
 
 		SELECT * FROM  temp_details_table_20170704_local  order by bank_code, trxn_category asc
			 		SELECT * FROM temp_details_table_20170704  order by  bank_code, trxn_category asc