USE postilion_office;
DBCC FREESYSTEMCACHE ('ALL') WITH MARK_IN_USE_FOR_REMOVAL;
DBCC FREESESSIONCACHE WITH NO_INFOMSGS;
DBCC FREEPROCCACHE WITH NO_INFOMSGS;
DBCC UPDATEUSAGE (postilion_office);
exec sp_updatestats;
