SELECT * FROM   XLS_ADMIN.MD_MEDIA
SELECT * FROM   XLS_ADMIN.TC_TXN_ATTRIBUTE
SELECT * FROM   XLS_ADMIN.TC_TXN
SELECT * FROM   XLS_ADMIN.TC_TXN_AMOUNT 
SELECT * FROM   XLS_ADMIN.TC_SETTLEMENT
SELECT * FROM   XLS_ADMIN.MD_BUCKET_ATTRIBUTE
SELECT * FROM   XLS_ADMIN.TERMINAL
SELECT * FROM   XLS_ADMIN.MERCHANT 
SELECT * FROM   XLS_ADMIN.V_XLS_ENTITY_EXP
SELECT * FROM   XLS_ADMIN.POOL 
SELECT * FROM   XLS_ADMIN.REPORT_TXN 
SELECT * FROM   XLS_ADMIN.MERCHANT
SELECT * FROM   XLS_ADMIN.TERMINAL
SELECT * FROM   XLS_ADMIN.CAMPAIGN 

                                            