USE [master]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2008]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2009]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2010]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2011]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2012]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2013]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2014]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2015]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2016]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2017]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2018]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2019]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2020]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2021]
GO
ALTER DATABASE [quickteller] ADD FILEGROUP [Transaction_2022]
GO
USE [master]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2008', FILENAME = N'F:\SQLSERVER\DATA\Transaction_File_2008.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2008]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2009', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2009.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2009]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2010', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2010.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2010]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2011', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2011.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2011]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2012', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2012.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2012]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2013', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2013.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2013]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2014', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2014.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2014]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2015', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2015.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2015]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2016', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2016.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2016]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2017', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2017.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2017]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2018', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2018.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2018]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2019', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2019.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2019]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2020', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2020.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2020]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2021', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2021.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2021]
GO
ALTER DATABASE [quickteller] ADD FILE ( NAME = N'Transaction_File_2022', FILENAME = N'D:\SQLSERVER\DATA\Transaction_File_2022.ndf' , SIZE = 3072KB , FILEGROWTH = 262144KB ) TO FILEGROUP [Transaction_2022]
GO













